/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.coupon;

import com.chargebee.v4.internal.JsonUtil;
import java.sql.Timestamp;
import java.util.List;

public class Coupon {

  private String id;
  private String name;
  private String invoiceName;
  private DiscountType discountType;
  private Number discountPercentage;
  private Long discountAmount;
  private Integer discountQuantity;
  private String currencyCode;
  private DurationType durationType;
  @Deprecated private Integer durationMonth;
  private Timestamp validFrom;
  private Timestamp validTill;
  private Integer maxRedemptions;
  private Status status;
  @Deprecated private ApplyDiscountOn applyDiscountOn;
  private ApplyOn applyOn;
  private Timestamp createdAt;
  private Timestamp archivedAt;
  private Long resourceVersion;
  private Timestamp updatedAt;
  private Integer period;
  private PeriodUnit periodUnit;
  private Integer redemptions;
  private String invoiceNotes;
  private java.util.Map<String, Object> metaData;
  private Boolean deleted;
  private List<ItemConstraints> itemConstraints;
  private List<ItemConstraintCriteria> itemConstraintCriteria;
  private List<CouponConstraints> couponConstraints;
  private List<String> planIds;
  private AddonConstraint addonConstraint;
  private PlanConstraint planConstraint;
  private Boolean includedInMrr;
  private List<String> addonIds;

  private java.util.Map<String, Object> customFields = new java.util.HashMap<>();

  public String getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public String getInvoiceName() {
    return invoiceName;
  }

  public DiscountType getDiscountType() {
    return discountType;
  }

  public Number getDiscountPercentage() {
    return discountPercentage;
  }

  public Long getDiscountAmount() {
    return discountAmount;
  }

  public Integer getDiscountQuantity() {
    return discountQuantity;
  }

  public String getCurrencyCode() {
    return currencyCode;
  }

  public DurationType getDurationType() {
    return durationType;
  }

  @Deprecated
  public Integer getDurationMonth() {
    return durationMonth;
  }

  public Timestamp getValidFrom() {
    return validFrom;
  }

  public Timestamp getValidTill() {
    return validTill;
  }

  public Integer getMaxRedemptions() {
    return maxRedemptions;
  }

  public Status getStatus() {
    return status;
  }

  @Deprecated
  public ApplyDiscountOn getApplyDiscountOn() {
    return applyDiscountOn;
  }

  public ApplyOn getApplyOn() {
    return applyOn;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public Timestamp getArchivedAt() {
    return archivedAt;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public Timestamp getUpdatedAt() {
    return updatedAt;
  }

  public Integer getPeriod() {
    return period;
  }

  public PeriodUnit getPeriodUnit() {
    return periodUnit;
  }

  public Integer getRedemptions() {
    return redemptions;
  }

  public String getInvoiceNotes() {
    return invoiceNotes;
  }

  public java.util.Map<String, Object> getMetaData() {
    return metaData;
  }

  public Boolean getDeleted() {
    return deleted;
  }

  public List<ItemConstraints> getItemConstraints() {
    return itemConstraints;
  }

  public List<ItemConstraintCriteria> getItemConstraintCriteria() {
    return itemConstraintCriteria;
  }

  public List<CouponConstraints> getCouponConstraints() {
    return couponConstraints;
  }

  public List<String> getPlanIds() {
    return planIds;
  }

  public AddonConstraint getAddonConstraint() {
    return addonConstraint;
  }

  public PlanConstraint getPlanConstraint() {
    return planConstraint;
  }

  public Boolean getIncludedInMrr() {
    return includedInMrr;
  }

  public List<String> getAddonIds() {
    return addonIds;
  }

  /**
   * Returns a map of custom fields. Custom fields are dynamic properties that follow the pattern
   * cf_* (e.g., cf_custom_field_name).
   *
   * @return map containing all custom fields
   */
  public java.util.Map<String, Object> getCustomFields() {
    return customFields;
  }

  /**
   * Returns the value of a specific custom field.
   *
   * @param fieldName the name of the custom field (e.g., "cf_custom_field_name")
   * @return the value of the custom field, or null if not present
   */
  public Object getCustomField(String fieldName) {
    return customFields.get(fieldName);
  }

  public enum DiscountType {
    FIXED_AMOUNT("fixed_amount"),

    PERCENTAGE("percentage"),

    OFFER_QUANTITY("offer_quantity"),

    /** An enum member indicating that DiscountType was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    DiscountType(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static DiscountType fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (DiscountType enumValue : DiscountType.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum DurationType {
    ONE_TIME("one_time"),

    FOREVER("forever"),

    LIMITED_PERIOD("limited_period"),

    /** An enum member indicating that DurationType was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    DurationType(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static DurationType fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (DurationType enumValue : DurationType.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum Status {
    ACTIVE("active"),

    EXPIRED("expired"),

    ARCHIVED("archived"),

    DELETED("deleted"),

    FUTURE("future"),

    /** An enum member indicating that Status was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Status(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Status fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Status enumValue : Status.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum ApplyDiscountOn {
    PLANS("plans"),

    PLANS_AND_ADDONS("plans_and_addons"),

    PLANS_WITH_QUANTITY("plans_with_quantity"),

    NOT_APPLICABLE("not_applicable"),

    /** An enum member indicating that ApplyDiscountOn was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    ApplyDiscountOn(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static ApplyDiscountOn fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (ApplyDiscountOn enumValue : ApplyDiscountOn.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum ApplyOn {
    INVOICE_AMOUNT("invoice_amount"),

    SPECIFIED_ITEMS_TOTAL("specified_items_total"),

    EACH_SPECIFIED_ITEM("each_specified_item"),

    EACH_UNIT_OF_SPECIFIED_ITEMS("each_unit_of_specified_items"),

    /** An enum member indicating that ApplyOn was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    ApplyOn(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static ApplyOn fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (ApplyOn enumValue : ApplyOn.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum PeriodUnit {
    DAY("day"),

    WEEK("week"),

    MONTH("month"),

    YEAR("year"),

    /** An enum member indicating that PeriodUnit was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    PeriodUnit(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static PeriodUnit fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (PeriodUnit enumValue : PeriodUnit.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum AddonConstraint {
    NONE("none"),

    ALL("all"),

    SPECIFIC("specific"),

    NOT_APPLICABLE("not_applicable"),

    /** An enum member indicating that AddonConstraint was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    AddonConstraint(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static AddonConstraint fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (AddonConstraint enumValue : AddonConstraint.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum PlanConstraint {
    NONE("none"),

    ALL("all"),

    SPECIFIC("specific"),

    NOT_APPLICABLE("not_applicable"),

    /** An enum member indicating that PlanConstraint was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    PlanConstraint(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static PlanConstraint fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (PlanConstraint enumValue : PlanConstraint.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static Coupon fromJson(String json) {
    Coupon obj = new Coupon();

    // Parse JSON to extract all keys for custom field extraction
    java.util.Set<String> knownFields = new java.util.HashSet<>();

    knownFields.add("id");

    knownFields.add("name");

    knownFields.add("invoice_name");

    knownFields.add("discount_type");

    knownFields.add("discount_percentage");

    knownFields.add("discount_amount");

    knownFields.add("discount_quantity");

    knownFields.add("currency_code");

    knownFields.add("duration_type");

    knownFields.add("duration_month");

    knownFields.add("valid_from");

    knownFields.add("valid_till");

    knownFields.add("max_redemptions");

    knownFields.add("status");

    knownFields.add("apply_discount_on");

    knownFields.add("apply_on");

    knownFields.add("created_at");

    knownFields.add("archived_at");

    knownFields.add("resource_version");

    knownFields.add("updated_at");

    knownFields.add("period");

    knownFields.add("period_unit");

    knownFields.add("redemptions");

    knownFields.add("invoice_notes");

    knownFields.add("meta_data");

    knownFields.add("deleted");

    knownFields.add("item_constraints");

    knownFields.add("item_constraint_criteria");

    knownFields.add("coupon_constraints");

    knownFields.add("plan_ids");

    knownFields.add("addon_constraint");

    knownFields.add("plan_constraint");

    knownFields.add("included_in_mrr");

    knownFields.add("addon_ids");

    obj.id = JsonUtil.getString(json, "id");

    obj.name = JsonUtil.getString(json, "name");

    obj.invoiceName = JsonUtil.getString(json, "invoice_name");

    obj.discountType = DiscountType.fromString(JsonUtil.getString(json, "discount_type"));

    obj.discountPercentage = JsonUtil.getNumber(json, "discount_percentage");

    obj.discountAmount = JsonUtil.getLong(json, "discount_amount");

    obj.discountQuantity = JsonUtil.getInteger(json, "discount_quantity");

    obj.currencyCode = JsonUtil.getString(json, "currency_code");

    obj.durationType = DurationType.fromString(JsonUtil.getString(json, "duration_type"));

    obj.durationMonth = JsonUtil.getInteger(json, "duration_month");

    obj.validFrom = JsonUtil.getTimestamp(json, "valid_from");

    obj.validTill = JsonUtil.getTimestamp(json, "valid_till");

    obj.maxRedemptions = JsonUtil.getInteger(json, "max_redemptions");

    obj.status = Status.fromString(JsonUtil.getString(json, "status"));

    obj.applyDiscountOn = ApplyDiscountOn.fromString(JsonUtil.getString(json, "apply_discount_on"));

    obj.applyOn = ApplyOn.fromString(JsonUtil.getString(json, "apply_on"));

    obj.createdAt = JsonUtil.getTimestamp(json, "created_at");

    obj.archivedAt = JsonUtil.getTimestamp(json, "archived_at");

    obj.resourceVersion = JsonUtil.getLong(json, "resource_version");

    obj.updatedAt = JsonUtil.getTimestamp(json, "updated_at");

    obj.period = JsonUtil.getInteger(json, "period");

    obj.periodUnit = PeriodUnit.fromString(JsonUtil.getString(json, "period_unit"));

    obj.redemptions = JsonUtil.getInteger(json, "redemptions");

    obj.invoiceNotes = JsonUtil.getString(json, "invoice_notes");

    String __metaDataJson = JsonUtil.getObject(json, "meta_data");
    obj.metaData =
        __metaDataJson != null
            ? JsonUtil.parseJsonObjectToMap(__metaDataJson)
            : new java.util.HashMap<>();

    obj.deleted = JsonUtil.getBoolean(json, "deleted");

    obj.itemConstraints =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "item_constraints")).stream()
            .map(ItemConstraints::fromJson)
            .collect(java.util.stream.Collectors.toList());

    obj.itemConstraintCriteria =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "item_constraint_criteria")).stream()
            .map(ItemConstraintCriteria::fromJson)
            .collect(java.util.stream.Collectors.toList());

    obj.couponConstraints =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "coupon_constraints")).stream()
            .map(CouponConstraints::fromJson)
            .collect(java.util.stream.Collectors.toList());

    obj.planIds = JsonUtil.parseArrayOfString(JsonUtil.getArray(json, "plan_ids"));

    obj.addonConstraint = AddonConstraint.fromString(JsonUtil.getString(json, "addon_constraint"));

    obj.planConstraint = PlanConstraint.fromString(JsonUtil.getString(json, "plan_constraint"));

    obj.includedInMrr = JsonUtil.getBoolean(json, "included_in_mrr");

    obj.addonIds = JsonUtil.parseArrayOfString(JsonUtil.getArray(json, "addon_ids"));

    // Extract custom fields (fields starting with cf_)
    obj.customFields = extractCustomFields(json, knownFields);

    return obj;
  }

  /**
   * Helper method to extract custom fields from JSON. Custom fields are fields that start with
   * "cf_" and are not in the known fields set.
   *
   * @param json JSON string to parse
   * @param knownFields set of known field names
   * @return map of custom fields
   */
  private static java.util.Map<String, Object> extractCustomFields(
      String json, java.util.Set<String> knownFields) {
    java.util.Map<String, Object> customFields = new java.util.HashMap<>();
    try {
      // Parse the entire JSON as a map
      java.util.Map<String, Object> allFields = JsonUtil.parseJsonObjectToMap(json);
      if (allFields != null) {
        for (java.util.Map.Entry<String, Object> entry : allFields.entrySet()) {
          String key = entry.getKey();
          // Include fields that start with "cf_" and are not in knownFields
          if (key != null && key.startsWith("cf_") && !knownFields.contains(key)) {
            customFields.put(key, entry.getValue());
          }
        }
      }
    } catch (Exception e) {
      // If parsing fails, return empty map
    }
    return customFields;
  }

  public static class ItemConstraints {

    private ItemType itemType;
    private Constraint constraint;
    private List<Object> itemPriceIds;

    public ItemType getItemType() {
      return itemType;
    }

    public Constraint getConstraint() {
      return constraint;
    }

    public List<Object> getItemPriceIds() {
      return itemPriceIds;
    }

    public enum ItemType {
      PLAN("plan"),

      ADDON("addon"),

      CHARGE("charge"),

      /** An enum member indicating that ItemType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ItemType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ItemType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ItemType enumValue : ItemType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum Constraint {
      NONE("none"),

      ALL("all"),

      SPECIFIC("specific"),

      CRITERIA("criteria"),

      /** An enum member indicating that Constraint was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      Constraint(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static Constraint fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (Constraint enumValue : Constraint.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static ItemConstraints fromJson(String json) {
      ItemConstraints obj = new ItemConstraints();

      obj.itemType = ItemType.fromString(JsonUtil.getString(json, "item_type"));

      obj.constraint = Constraint.fromString(JsonUtil.getString(json, "constraint"));

      String __itemPriceIdsJson = JsonUtil.getArray(json, "item_price_ids");
      obj.itemPriceIds =
          __itemPriceIdsJson != null
              ? JsonUtil.parseObjectArray(__itemPriceIdsJson).stream()
                  .map(JsonUtil::parseJsonObjectToMap)
                  .collect(java.util.stream.Collectors.toList())
              : null;

      return obj;
    }
  }

  public static class ItemConstraintCriteria {

    private ItemType itemType;
    private List<Object> currencies;
    private List<Object> itemFamilyIds;
    private List<Object> itemPricePeriods;

    public ItemType getItemType() {
      return itemType;
    }

    public List<Object> getCurrencies() {
      return currencies;
    }

    public List<Object> getItemFamilyIds() {
      return itemFamilyIds;
    }

    public List<Object> getItemPricePeriods() {
      return itemPricePeriods;
    }

    public enum ItemType {
      PLAN("plan"),

      ADDON("addon"),

      CHARGE("charge"),

      /** An enum member indicating that ItemType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ItemType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ItemType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ItemType enumValue : ItemType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static ItemConstraintCriteria fromJson(String json) {
      ItemConstraintCriteria obj = new ItemConstraintCriteria();

      obj.itemType = ItemType.fromString(JsonUtil.getString(json, "item_type"));

      String __currenciesJson = JsonUtil.getArray(json, "currencies");
      obj.currencies =
          __currenciesJson != null
              ? JsonUtil.parseObjectArray(__currenciesJson).stream()
                  .map(JsonUtil::parseJsonObjectToMap)
                  .collect(java.util.stream.Collectors.toList())
              : null;

      String __itemFamilyIdsJson = JsonUtil.getArray(json, "item_family_ids");
      obj.itemFamilyIds =
          __itemFamilyIdsJson != null
              ? JsonUtil.parseObjectArray(__itemFamilyIdsJson).stream()
                  .map(JsonUtil::parseJsonObjectToMap)
                  .collect(java.util.stream.Collectors.toList())
              : null;

      String __itemPricePeriodsJson = JsonUtil.getArray(json, "item_price_periods");
      obj.itemPricePeriods =
          __itemPricePeriodsJson != null
              ? JsonUtil.parseObjectArray(__itemPricePeriodsJson).stream()
                  .map(JsonUtil::parseJsonObjectToMap)
                  .collect(java.util.stream.Collectors.toList())
              : null;

      return obj;
    }
  }

  public static class CouponConstraints {

    private EntityType entityType;
    private Type type;
    private String value;

    public EntityType getEntityType() {
      return entityType;
    }

    public Type getType() {
      return type;
    }

    public String getValue() {
      return value;
    }

    public enum EntityType {
      CUSTOMER("customer"),

      /** An enum member indicating that EntityType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      EntityType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static EntityType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (EntityType enumValue : EntityType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum Type {
      MAX_REDEMPTIONS("max_redemptions"),

      UNIQUE_BY("unique_by"),

      EXISTING_CUSTOMER("existing_customer"),

      NEW_CUSTOMER("new_customer"),

      /** An enum member indicating that Type was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      Type(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static Type fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (Type enumValue : Type.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static CouponConstraints fromJson(String json) {
      CouponConstraints obj = new CouponConstraints();

      obj.entityType = EntityType.fromString(JsonUtil.getString(json, "entity_type"));

      obj.type = Type.fromString(JsonUtil.getString(json, "type"));

      obj.value = JsonUtil.getString(json, "value");

      return obj;
    }
  }
}
