/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.core.models.export.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class ExportDifferentialPricesParams {

  private final Map<String, Object> formData;

  private ExportDifferentialPricesParams(ExportDifferentialPricesBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for ExportDifferentialPricesParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static ExportDifferentialPricesBuilder builder() {
    return new ExportDifferentialPricesBuilder();
  }

  public static final class ExportDifferentialPricesBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private ExportDifferentialPricesBuilder() {}

    public ExportDifferentialPricesBuilder itemId(ItemIdParams value) {
      formData.put("item_id", value);
      return this;
    }

    public ExportDifferentialPricesBuilder differentialPrice(DifferentialPriceParams value) {
      formData.put("differential_price", value);
      return this;
    }

    public ExportDifferentialPricesParams build() {
      return new ExportDifferentialPricesParams(this);
    }
  }

  public static final class ItemIdParams {

    private final Map<String, Object> formData;

    private ItemIdParams(ItemIdBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for ItemIdParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ItemIdBuilder builder() {
      return new ItemIdBuilder();
    }

    public static final class ItemIdBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private ItemIdBuilder() {}

      public ItemIdBuilder is(String value) {

        formData.put("is", value);

        return this;
      }

      public ItemIdBuilder isNot(String value) {

        formData.put("is_not", value);

        return this;
      }

      public ItemIdBuilder startsWith(String value) {

        formData.put("starts_with", value);

        return this;
      }

      public ItemIdBuilder in(String value) {

        formData.put("in", value);

        return this;
      }

      public ItemIdBuilder notIn(String value) {

        formData.put("not_in", value);

        return this;
      }

      public ItemIdParams build() {
        return new ItemIdParams(this);
      }
    }
  }

  public static final class DifferentialPriceParams {

    private final Map<String, Object> formData;

    private DifferentialPriceParams(DifferentialPriceBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for DifferentialPriceParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static DifferentialPriceBuilder builder() {
      return new DifferentialPriceBuilder();
    }

    public static final class DifferentialPriceBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private DifferentialPriceBuilder() {}

      public DifferentialPriceBuilder itemPriceId(ItemPriceIdParams value) {
        formData.put("item_price_id", value);
        return this;
      }

      public DifferentialPriceBuilder id(IdParams value) {
        formData.put("id", value);
        return this;
      }

      public DifferentialPriceBuilder parentItemId(ParentItemIdParams value) {
        formData.put("parent_item_id", value);
        return this;
      }

      public DifferentialPriceParams build() {
        return new DifferentialPriceParams(this);
      }
    }
  }

  public static final class ItemPriceIdParams {

    private final Map<String, Object> formData;

    private ItemPriceIdParams(ItemPriceIdBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for ItemPriceIdParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ItemPriceIdBuilder builder() {
      return new ItemPriceIdBuilder();
    }

    public static final class ItemPriceIdBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private ItemPriceIdBuilder() {}

      public ItemPriceIdBuilder is(String value) {

        formData.put("is", value);

        return this;
      }

      public ItemPriceIdBuilder isNot(String value) {

        formData.put("is_not", value);

        return this;
      }

      public ItemPriceIdBuilder startsWith(String value) {

        formData.put("starts_with", value);

        return this;
      }

      public ItemPriceIdBuilder in(String value) {

        formData.put("in", value);

        return this;
      }

      public ItemPriceIdBuilder notIn(String value) {

        formData.put("not_in", value);

        return this;
      }

      public ItemPriceIdParams build() {
        return new ItemPriceIdParams(this);
      }
    }
  }

  public static final class IdParams {

    private final Map<String, Object> formData;

    private IdParams(IdBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for IdParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static IdBuilder builder() {
      return new IdBuilder();
    }

    public static final class IdBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private IdBuilder() {}

      public IdBuilder is(String value) {

        formData.put("is", value);

        return this;
      }

      public IdBuilder isNot(String value) {

        formData.put("is_not", value);

        return this;
      }

      public IdBuilder startsWith(String value) {

        formData.put("starts_with", value);

        return this;
      }

      public IdBuilder in(String value) {

        formData.put("in", value);

        return this;
      }

      public IdBuilder notIn(String value) {

        formData.put("not_in", value);

        return this;
      }

      public IdParams build() {
        return new IdParams(this);
      }
    }
  }

  public static final class ParentItemIdParams {

    private final Map<String, Object> formData;

    private ParentItemIdParams(ParentItemIdBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for ParentItemIdParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ParentItemIdBuilder builder() {
      return new ParentItemIdBuilder();
    }

    public static final class ParentItemIdBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private ParentItemIdBuilder() {}

      public ParentItemIdBuilder is(String value) {

        formData.put("is", value);

        return this;
      }

      public ParentItemIdBuilder isNot(String value) {

        formData.put("is_not", value);

        return this;
      }

      public ParentItemIdBuilder startsWith(String value) {

        formData.put("starts_with", value);

        return this;
      }

      public ParentItemIdBuilder in(String value) {

        formData.put("in", value);

        return this;
      }

      public ParentItemIdBuilder notIn(String value) {

        formData.put("not_in", value);

        return this;
      }

      public ParentItemIdParams build() {
        return new ParentItemIdParams(this);
      }
    }
  }
}
