/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.omnichannelSubscription.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class OmnichannelTransactionsForOmnichannelSubscriptionParams {

  private final Map<String, Object> queryParams;

  private OmnichannelTransactionsForOmnichannelSubscriptionParams(
      OmnichannelTransactionsForOmnichannelSubscriptionBuilder builder) {
    this.queryParams = Collections.unmodifiableMap(new LinkedHashMap<>(builder.queryParams));
  }

  /** Get the query parameters for this request. */
  public Map<String, Object> toQueryParams() {
    return queryParams;
  }

  public OmnichannelTransactionsForOmnichannelSubscriptionBuilder toBuilder() {
    OmnichannelTransactionsForOmnichannelSubscriptionBuilder builder =
        new OmnichannelTransactionsForOmnichannelSubscriptionBuilder();
    builder.queryParams.putAll(queryParams);
    return builder;
  }

  /** Create a new builder for OmnichannelTransactionsForOmnichannelSubscriptionParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static OmnichannelTransactionsForOmnichannelSubscriptionBuilder builder() {
    return new OmnichannelTransactionsForOmnichannelSubscriptionBuilder();
  }

  public static final class OmnichannelTransactionsForOmnichannelSubscriptionBuilder {
    private final Map<String, Object> queryParams = new LinkedHashMap<>();

    private OmnichannelTransactionsForOmnichannelSubscriptionBuilder() {}

    public OmnichannelTransactionsForOmnichannelSubscriptionBuilder limit(Integer value) {
      queryParams.put("limit", value);
      return this;
    }

    public OmnichannelTransactionsForOmnichannelSubscriptionBuilder offset(String value) {
      queryParams.put("offset", value);
      return this;
    }

    public OmnichannelTransactionsForOmnichannelSubscriptionParams build() {
      return new OmnichannelTransactionsForOmnichannelSubscriptionParams(this);
    }
  }
}
