/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.core.services;

import com.chargebee.client.ChargebeeClient;
import com.chargebee.client.request.RequestOptions;
import com.chargebee.transport.Response;

import com.chargebee.core.models.item.params.ItemListParams;

import com.chargebee.core.models.item.params.ItemCreateParams;

import com.chargebee.core.models.item.params.ItemUpdateParams;

import com.chargebee.core.responses.item.ItemListResponse;

import com.chargebee.core.responses.item.ItemCreateResponse;

import com.chargebee.core.responses.item.ItemDeleteResponse;

import com.chargebee.core.responses.item.ItemRetrieveResponse;

import com.chargebee.core.responses.item.ItemUpdateResponse;

public final class ItemService extends BaseService<ItemService> {

  private final ServiceConfig config;

  public ItemService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private ItemService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private ItemService(ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  ItemService with(RequestOptions newOptions) {
    return new ItemService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public ItemService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /** list a item using immutable params (executes immediately) - returns raw Response. */
  Response listRaw(ItemListParams params) throws Exception {

    return get("/items", params != null ? params.toQueryParams() : null);
  }

  /** list a item without params (executes immediately) - returns raw Response. */
  Response listRaw() throws Exception {

    return get("/items", null);
  }

  /** list a item using raw JSON payload (executes immediately) - returns raw Response. */
  Response listRaw(String jsonPayload) throws Exception {

    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public ItemListResponse list(ItemListParams params) throws Exception {
    Response response = listRaw(params);

    return ItemListResponse.fromJson(response.getBodyAsString(), this, params);
  }

  public ItemListResponse list() throws Exception {
    Response response = listRaw();
    return ItemListResponse.fromJson(response.getBodyAsString(), this, null);
  }

  /** create a item using immutable params (executes immediately) - returns raw Response. */
  Response createRaw(ItemCreateParams params) throws Exception {

    return post("/items", params != null ? params.toFormData() : null);
  }

  /** create a item using raw JSON payload (executes immediately) - returns raw Response. */
  Response createRaw(String jsonPayload) throws Exception {

    return postJson("/items", jsonPayload);
  }

  public ItemCreateResponse create(ItemCreateParams params) throws Exception {
    Response response = createRaw(params);

    return parseResponse(response, ItemCreateResponse.class);
  }

  /** delete a item (executes immediately) - returns raw Response. */
  Response deleteRaw(String itemId) throws Exception {
    String path = buildPathWithParams("/items/{item-id}/delete", "item-id", itemId);

    return post(path, null);
  }

  public ItemDeleteResponse delete(String itemId) throws Exception {
    Response response = deleteRaw(itemId);
    return parseResponse(response, ItemDeleteResponse.class);
  }

  /** retrieve a item (executes immediately) - returns raw Response. */
  Response retrieveRaw(String itemId) throws Exception {
    String path = buildPathWithParams("/items/{item-id}", "item-id", itemId);

    return get(path, null);
  }

  public ItemRetrieveResponse retrieve(String itemId) throws Exception {
    Response response = retrieveRaw(itemId);
    return parseResponse(response, ItemRetrieveResponse.class);
  }

  /** update a item (executes immediately) - returns raw Response. */
  Response updateRaw(String itemId) throws Exception {
    String path = buildPathWithParams("/items/{item-id}", "item-id", itemId);

    return post(path, null);
  }

  /** update a item using immutable params (executes immediately) - returns raw Response. */
  Response updateRaw(String itemId, ItemUpdateParams params) throws Exception {
    String path = buildPathWithParams("/items/{item-id}", "item-id", itemId);
    return post(path, params.toFormData());
  }

  /** update a item using raw JSON payload (executes immediately) - returns raw Response. */
  Response updateRaw(String itemId, String jsonPayload) throws Exception {
    String path = buildPathWithParams("/items/{item-id}", "item-id", itemId);
    return postJson(path, jsonPayload);
  }

  public ItemUpdateResponse update(String itemId, ItemUpdateParams params) throws Exception {
    Response response = updateRaw(itemId, params);
    return parseResponse(response, ItemUpdateResponse.class);
  }
}
