/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.models.offerEvent.params;

import com.chargebee.v4.internal.Recommended;

import java.util.LinkedHashMap;
import java.util.Map;

public final class OfferEventCreateParams {

  private final String personalizedOfferId;

  private final Type type;

  private OfferEventCreateParams(OfferEventCreateBuilder builder) {

    this.personalizedOfferId = builder.personalizedOfferId;

    this.type = builder.type;
  }

  public String getPersonalizedOfferId() {
    return personalizedOfferId;
  }

  public Type getType() {
    return type;
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    Map<String, Object> formData = new LinkedHashMap<>();

    if (this.personalizedOfferId != null) {

      formData.put("personalized_offer_id", this.personalizedOfferId);
    }

    if (this.type != null) {

      formData.put("type", this.type);
    }

    return formData;
  }

  /** Create a new builder for OfferEventCreateParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static OfferEventCreateBuilder builder() {
    return new OfferEventCreateBuilder();
  }

  public static final class OfferEventCreateBuilder {

    private String personalizedOfferId;

    private Type type;

    private OfferEventCreateBuilder() {}

    public OfferEventCreateBuilder personalizedOfferId(String value) {
      this.personalizedOfferId = value;
      return this;
    }

    public OfferEventCreateBuilder type(Type value) {
      this.type = value;
      return this;
    }

    public OfferEventCreateParams build() {
      return new OfferEventCreateParams(this);
    }
  }

  public enum Type {
    VIEWED("viewed"),

    DISMISSED("dismissed"),

    /** An enum member indicating that Type was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Type(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Type fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Type enumValue : Type.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }
}
