/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.gatewayErrorDetail;

import com.chargebee.v4.internal.JsonUtil;

public class GatewayErrorDetail {

  private String requestId;
  private String errorCategory;
  private String errorCode;
  private String errorMessage;
  private String declineCode;
  private String declineMessage;
  private String networkErrorCode;
  private String networkErrorMessage;
  private String errorField;
  private String recommendationCode;
  private String recommendationMessage;
  private String processorErrorCode;
  private String processorErrorMessage;
  private String errorCauseId;
  private String processorAdviceCode;

  public String getRequestId() {
    return requestId;
  }

  public String getErrorCategory() {
    return errorCategory;
  }

  public String getErrorCode() {
    return errorCode;
  }

  public String getErrorMessage() {
    return errorMessage;
  }

  public String getDeclineCode() {
    return declineCode;
  }

  public String getDeclineMessage() {
    return declineMessage;
  }

  public String getNetworkErrorCode() {
    return networkErrorCode;
  }

  public String getNetworkErrorMessage() {
    return networkErrorMessage;
  }

  public String getErrorField() {
    return errorField;
  }

  public String getRecommendationCode() {
    return recommendationCode;
  }

  public String getRecommendationMessage() {
    return recommendationMessage;
  }

  public String getProcessorErrorCode() {
    return processorErrorCode;
  }

  public String getProcessorErrorMessage() {
    return processorErrorMessage;
  }

  public String getErrorCauseId() {
    return errorCauseId;
  }

  public String getProcessorAdviceCode() {
    return processorAdviceCode;
  }

  public static GatewayErrorDetail fromJson(String json) {
    GatewayErrorDetail obj = new GatewayErrorDetail();

    obj.requestId = JsonUtil.getString(json, "request_id");

    obj.errorCategory = JsonUtil.getString(json, "error_category");

    obj.errorCode = JsonUtil.getString(json, "error_code");

    obj.errorMessage = JsonUtil.getString(json, "error_message");

    obj.declineCode = JsonUtil.getString(json, "decline_code");

    obj.declineMessage = JsonUtil.getString(json, "decline_message");

    obj.networkErrorCode = JsonUtil.getString(json, "network_error_code");

    obj.networkErrorMessage = JsonUtil.getString(json, "network_error_message");

    obj.errorField = JsonUtil.getString(json, "error_field");

    obj.recommendationCode = JsonUtil.getString(json, "recommendation_code");

    obj.recommendationMessage = JsonUtil.getString(json, "recommendation_message");

    obj.processorErrorCode = JsonUtil.getString(json, "processor_error_code");

    obj.processorErrorMessage = JsonUtil.getString(json, "processor_error_message");

    obj.errorCauseId = JsonUtil.getString(json, "error_cause_id");

    obj.processorAdviceCode = JsonUtil.getString(json, "processor_advice_code");

    return obj;
  }

  @Override
  public String toString() {
    return "GatewayErrorDetail{"
        + "requestId="
        + requestId
        + ", errorCategory="
        + errorCategory
        + ", errorCode="
        + errorCode
        + ", errorMessage="
        + errorMessage
        + ", declineCode="
        + declineCode
        + ", declineMessage="
        + declineMessage
        + ", networkErrorCode="
        + networkErrorCode
        + ", networkErrorMessage="
        + networkErrorMessage
        + ", errorField="
        + errorField
        + ", recommendationCode="
        + recommendationCode
        + ", recommendationMessage="
        + recommendationMessage
        + ", processorErrorCode="
        + processorErrorCode
        + ", processorErrorMessage="
        + processorErrorMessage
        + ", errorCauseId="
        + errorCauseId
        + ", processorAdviceCode="
        + processorAdviceCode
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    GatewayErrorDetail that = (GatewayErrorDetail) o;
    return java.util.Objects.equals(requestId, that.requestId)
        && java.util.Objects.equals(errorCategory, that.errorCategory)
        && java.util.Objects.equals(errorCode, that.errorCode)
        && java.util.Objects.equals(errorMessage, that.errorMessage)
        && java.util.Objects.equals(declineCode, that.declineCode)
        && java.util.Objects.equals(declineMessage, that.declineMessage)
        && java.util.Objects.equals(networkErrorCode, that.networkErrorCode)
        && java.util.Objects.equals(networkErrorMessage, that.networkErrorMessage)
        && java.util.Objects.equals(errorField, that.errorField)
        && java.util.Objects.equals(recommendationCode, that.recommendationCode)
        && java.util.Objects.equals(recommendationMessage, that.recommendationMessage)
        && java.util.Objects.equals(processorErrorCode, that.processorErrorCode)
        && java.util.Objects.equals(processorErrorMessage, that.processorErrorMessage)
        && java.util.Objects.equals(errorCauseId, that.errorCauseId)
        && java.util.Objects.equals(processorAdviceCode, that.processorAdviceCode);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(
        requestId,
        errorCategory,
        errorCode,
        errorMessage,
        declineCode,
        declineMessage,
        networkErrorCode,
        networkErrorMessage,
        errorField,
        recommendationCode,
        recommendationMessage,
        processorErrorCode,
        processorErrorMessage,
        errorCauseId,
        processorAdviceCode);
  }
}
