/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.models.quote.params;

import com.chargebee.v4.internal.Recommended;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.List;
import java.sql.Timestamp;

public final class QuoteEditForChargeItemsAndChargesParams {

  private final String poNumber;

  private final String notes;

  private final Timestamp expiresAt;

  private final String currencyCode;

  private final String coupon;

  private final List<String> couponIds;

  private final BillingAddressParams billingAddress;

  private final ShippingAddressParams shippingAddress;

  private final List<ItemPricesParams> itemPrices;

  private final List<ItemTiersParams> itemTiers;

  private final List<ChargesParams> charges;

  private final List<DiscountsParams> discounts;

  private final List<TaxProvidersFieldsParams> taxProvidersFields;

  private QuoteEditForChargeItemsAndChargesParams(
      QuoteEditForChargeItemsAndChargesBuilder builder) {

    this.poNumber = builder.poNumber;

    this.notes = builder.notes;

    this.expiresAt = builder.expiresAt;

    this.currencyCode = builder.currencyCode;

    this.coupon = builder.coupon;

    this.couponIds = builder.couponIds;

    this.billingAddress = builder.billingAddress;

    this.shippingAddress = builder.shippingAddress;

    this.itemPrices = builder.itemPrices;

    this.itemTiers = builder.itemTiers;

    this.charges = builder.charges;

    this.discounts = builder.discounts;

    this.taxProvidersFields = builder.taxProvidersFields;
  }

  public String getPoNumber() {
    return poNumber;
  }

  public String getNotes() {
    return notes;
  }

  public Timestamp getExpiresAt() {
    return expiresAt;
  }

  public String getCurrencyCode() {
    return currencyCode;
  }

  public String getCoupon() {
    return coupon;
  }

  public List<String> getCouponIds() {
    return couponIds;
  }

  public BillingAddressParams getBillingAddress() {
    return billingAddress;
  }

  public ShippingAddressParams getShippingAddress() {
    return shippingAddress;
  }

  public List<ItemPricesParams> getItemPrices() {
    return itemPrices;
  }

  public List<ItemTiersParams> getItemTiers() {
    return itemTiers;
  }

  public List<ChargesParams> getCharges() {
    return charges;
  }

  public List<DiscountsParams> getDiscounts() {
    return discounts;
  }

  public List<TaxProvidersFieldsParams> getTaxProvidersFields() {
    return taxProvidersFields;
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    Map<String, Object> formData = new LinkedHashMap<>();

    if (this.poNumber != null) {

      formData.put("po_number", this.poNumber);
    }

    if (this.notes != null) {

      formData.put("notes", this.notes);
    }

    if (this.expiresAt != null) {

      formData.put("expires_at", this.expiresAt);
    }

    if (this.currencyCode != null) {

      formData.put("currency_code", this.currencyCode);
    }

    if (this.coupon != null) {

      formData.put("coupon", this.coupon);
    }

    if (this.couponIds != null) {

      formData.put("coupon_ids", this.couponIds);
    }

    if (this.billingAddress != null) {

      // Single object
      Map<String, Object> nestedData = this.billingAddress.toFormData();
      for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
        String nestedKey = "billing_address[" + entry.getKey() + "]";
        formData.put(nestedKey, entry.getValue());
      }
    }

    if (this.shippingAddress != null) {

      // Single object
      Map<String, Object> nestedData = this.shippingAddress.toFormData();
      for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
        String nestedKey = "shipping_address[" + entry.getKey() + "]";
        formData.put(nestedKey, entry.getValue());
      }
    }

    if (this.itemPrices != null) {

      // List of objects
      for (int i = 0; i < this.itemPrices.size(); i++) {
        ItemPricesParams item = this.itemPrices.get(i);
        if (item != null) {
          Map<String, Object> itemData = item.toFormData();
          for (Map.Entry<String, Object> entry : itemData.entrySet()) {
            String indexedKey = "item_prices[" + entry.getKey() + "][" + i + "]";
            formData.put(indexedKey, entry.getValue());
          }
        }
      }
    }

    if (this.itemTiers != null) {

      // List of objects
      for (int i = 0; i < this.itemTiers.size(); i++) {
        ItemTiersParams item = this.itemTiers.get(i);
        if (item != null) {
          Map<String, Object> itemData = item.toFormData();
          for (Map.Entry<String, Object> entry : itemData.entrySet()) {
            String indexedKey = "item_tiers[" + entry.getKey() + "][" + i + "]";
            formData.put(indexedKey, entry.getValue());
          }
        }
      }
    }

    if (this.charges != null) {

      // List of objects
      for (int i = 0; i < this.charges.size(); i++) {
        ChargesParams item = this.charges.get(i);
        if (item != null) {
          Map<String, Object> itemData = item.toFormData();
          for (Map.Entry<String, Object> entry : itemData.entrySet()) {
            String indexedKey = "charges[" + entry.getKey() + "][" + i + "]";
            formData.put(indexedKey, entry.getValue());
          }
        }
      }
    }

    if (this.discounts != null) {

      // List of objects
      for (int i = 0; i < this.discounts.size(); i++) {
        DiscountsParams item = this.discounts.get(i);
        if (item != null) {
          Map<String, Object> itemData = item.toFormData();
          for (Map.Entry<String, Object> entry : itemData.entrySet()) {
            String indexedKey = "discounts[" + entry.getKey() + "][" + i + "]";
            formData.put(indexedKey, entry.getValue());
          }
        }
      }
    }

    if (this.taxProvidersFields != null) {

      // List of objects
      for (int i = 0; i < this.taxProvidersFields.size(); i++) {
        TaxProvidersFieldsParams item = this.taxProvidersFields.get(i);
        if (item != null) {
          Map<String, Object> itemData = item.toFormData();
          for (Map.Entry<String, Object> entry : itemData.entrySet()) {
            String indexedKey = "tax_providers_fields[" + entry.getKey() + "][" + i + "]";
            formData.put(indexedKey, entry.getValue());
          }
        }
      }
    }

    return formData;
  }

  /** Create a new builder for QuoteEditForChargeItemsAndChargesParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static QuoteEditForChargeItemsAndChargesBuilder builder() {
    return new QuoteEditForChargeItemsAndChargesBuilder();
  }

  public static final class QuoteEditForChargeItemsAndChargesBuilder {

    private String poNumber;

    private String notes;

    private Timestamp expiresAt;

    private String currencyCode;

    private String coupon;

    private List<String> couponIds;

    private BillingAddressParams billingAddress;

    private ShippingAddressParams shippingAddress;

    private List<ItemPricesParams> itemPrices;

    private List<ItemTiersParams> itemTiers;

    private List<ChargesParams> charges;

    private List<DiscountsParams> discounts;

    private List<TaxProvidersFieldsParams> taxProvidersFields;

    private QuoteEditForChargeItemsAndChargesBuilder() {}

    public QuoteEditForChargeItemsAndChargesBuilder poNumber(String value) {
      this.poNumber = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder notes(String value) {
      this.notes = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder expiresAt(Timestamp value) {
      this.expiresAt = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder currencyCode(String value) {
      this.currencyCode = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder coupon(String value) {
      this.coupon = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder couponIds(List<String> value) {
      this.couponIds = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder billingAddress(BillingAddressParams value) {
      this.billingAddress = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder shippingAddress(ShippingAddressParams value) {
      this.shippingAddress = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder itemPrices(List<ItemPricesParams> value) {
      this.itemPrices = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder itemTiers(List<ItemTiersParams> value) {
      this.itemTiers = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder charges(List<ChargesParams> value) {
      this.charges = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder discounts(List<DiscountsParams> value) {
      this.discounts = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesBuilder taxProvidersFields(
        List<TaxProvidersFieldsParams> value) {
      this.taxProvidersFields = value;
      return this;
    }

    public QuoteEditForChargeItemsAndChargesParams build() {
      return new QuoteEditForChargeItemsAndChargesParams(this);
    }
  }

  public static final class BillingAddressParams {

    private final String firstName;

    private final String lastName;

    private final String email;

    private final String company;

    private final String phone;

    private final String line1;

    private final String line2;

    private final String line3;

    private final String city;

    private final String stateCode;

    private final String state;

    private final String zip;

    private final String country;

    private final ValidationStatus validationStatus;

    private BillingAddressParams(BillingAddressBuilder builder) {

      this.firstName = builder.firstName;

      this.lastName = builder.lastName;

      this.email = builder.email;

      this.company = builder.company;

      this.phone = builder.phone;

      this.line1 = builder.line1;

      this.line2 = builder.line2;

      this.line3 = builder.line3;

      this.city = builder.city;

      this.stateCode = builder.stateCode;

      this.state = builder.state;

      this.zip = builder.zip;

      this.country = builder.country;

      this.validationStatus = builder.validationStatus;
    }

    public String getFirstName() {
      return firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public String getEmail() {
      return email;
    }

    public String getCompany() {
      return company;
    }

    public String getPhone() {
      return phone;
    }

    public String getLine1() {
      return line1;
    }

    public String getLine2() {
      return line2;
    }

    public String getLine3() {
      return line3;
    }

    public String getCity() {
      return city;
    }

    public String getStateCode() {
      return stateCode;
    }

    public String getState() {
      return state;
    }

    public String getZip() {
      return zip;
    }

    public String getCountry() {
      return country;
    }

    public ValidationStatus getValidationStatus() {
      return validationStatus;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.firstName != null) {

        formData.put("first_name", this.firstName);
      }

      if (this.lastName != null) {

        formData.put("last_name", this.lastName);
      }

      if (this.email != null) {

        formData.put("email", this.email);
      }

      if (this.company != null) {

        formData.put("company", this.company);
      }

      if (this.phone != null) {

        formData.put("phone", this.phone);
      }

      if (this.line1 != null) {

        formData.put("line1", this.line1);
      }

      if (this.line2 != null) {

        formData.put("line2", this.line2);
      }

      if (this.line3 != null) {

        formData.put("line3", this.line3);
      }

      if (this.city != null) {

        formData.put("city", this.city);
      }

      if (this.stateCode != null) {

        formData.put("state_code", this.stateCode);
      }

      if (this.state != null) {

        formData.put("state", this.state);
      }

      if (this.zip != null) {

        formData.put("zip", this.zip);
      }

      if (this.country != null) {

        formData.put("country", this.country);
      }

      if (this.validationStatus != null) {

        formData.put("validation_status", this.validationStatus);
      }

      return formData;
    }

    /** Create a new builder for BillingAddressParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static BillingAddressBuilder builder() {
      return new BillingAddressBuilder();
    }

    public static final class BillingAddressBuilder {

      private String firstName;

      private String lastName;

      private String email;

      private String company;

      private String phone;

      private String line1;

      private String line2;

      private String line3;

      private String city;

      private String stateCode;

      private String state;

      private String zip;

      private String country;

      private ValidationStatus validationStatus;

      private BillingAddressBuilder() {}

      public BillingAddressBuilder firstName(String value) {
        this.firstName = value;
        return this;
      }

      public BillingAddressBuilder lastName(String value) {
        this.lastName = value;
        return this;
      }

      public BillingAddressBuilder email(String value) {
        this.email = value;
        return this;
      }

      public BillingAddressBuilder company(String value) {
        this.company = value;
        return this;
      }

      public BillingAddressBuilder phone(String value) {
        this.phone = value;
        return this;
      }

      public BillingAddressBuilder line1(String value) {
        this.line1 = value;
        return this;
      }

      public BillingAddressBuilder line2(String value) {
        this.line2 = value;
        return this;
      }

      public BillingAddressBuilder line3(String value) {
        this.line3 = value;
        return this;
      }

      public BillingAddressBuilder city(String value) {
        this.city = value;
        return this;
      }

      public BillingAddressBuilder stateCode(String value) {
        this.stateCode = value;
        return this;
      }

      public BillingAddressBuilder state(String value) {
        this.state = value;
        return this;
      }

      public BillingAddressBuilder zip(String value) {
        this.zip = value;
        return this;
      }

      public BillingAddressBuilder country(String value) {
        this.country = value;
        return this;
      }

      public BillingAddressBuilder validationStatus(ValidationStatus value) {
        this.validationStatus = value;
        return this;
      }

      public BillingAddressParams build() {
        return new BillingAddressParams(this);
      }
    }

    public enum ValidationStatus {
      NOT_VALIDATED("not_validated"),

      VALID("valid"),

      PARTIALLY_VALID("partially_valid"),

      INVALID("invalid"),

      /** An enum member indicating that ValidationStatus was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ValidationStatus(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ValidationStatus fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ValidationStatus enumValue : ValidationStatus.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class ShippingAddressParams {

    private final String firstName;

    private final String lastName;

    private final String email;

    private final String company;

    private final String phone;

    private final String line1;

    private final String line2;

    private final String line3;

    private final String city;

    private final String stateCode;

    private final String state;

    private final String zip;

    private final String country;

    private final ValidationStatus validationStatus;

    private ShippingAddressParams(ShippingAddressBuilder builder) {

      this.firstName = builder.firstName;

      this.lastName = builder.lastName;

      this.email = builder.email;

      this.company = builder.company;

      this.phone = builder.phone;

      this.line1 = builder.line1;

      this.line2 = builder.line2;

      this.line3 = builder.line3;

      this.city = builder.city;

      this.stateCode = builder.stateCode;

      this.state = builder.state;

      this.zip = builder.zip;

      this.country = builder.country;

      this.validationStatus = builder.validationStatus;
    }

    public String getFirstName() {
      return firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public String getEmail() {
      return email;
    }

    public String getCompany() {
      return company;
    }

    public String getPhone() {
      return phone;
    }

    public String getLine1() {
      return line1;
    }

    public String getLine2() {
      return line2;
    }

    public String getLine3() {
      return line3;
    }

    public String getCity() {
      return city;
    }

    public String getStateCode() {
      return stateCode;
    }

    public String getState() {
      return state;
    }

    public String getZip() {
      return zip;
    }

    public String getCountry() {
      return country;
    }

    public ValidationStatus getValidationStatus() {
      return validationStatus;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.firstName != null) {

        formData.put("first_name", this.firstName);
      }

      if (this.lastName != null) {

        formData.put("last_name", this.lastName);
      }

      if (this.email != null) {

        formData.put("email", this.email);
      }

      if (this.company != null) {

        formData.put("company", this.company);
      }

      if (this.phone != null) {

        formData.put("phone", this.phone);
      }

      if (this.line1 != null) {

        formData.put("line1", this.line1);
      }

      if (this.line2 != null) {

        formData.put("line2", this.line2);
      }

      if (this.line3 != null) {

        formData.put("line3", this.line3);
      }

      if (this.city != null) {

        formData.put("city", this.city);
      }

      if (this.stateCode != null) {

        formData.put("state_code", this.stateCode);
      }

      if (this.state != null) {

        formData.put("state", this.state);
      }

      if (this.zip != null) {

        formData.put("zip", this.zip);
      }

      if (this.country != null) {

        formData.put("country", this.country);
      }

      if (this.validationStatus != null) {

        formData.put("validation_status", this.validationStatus);
      }

      return formData;
    }

    /** Create a new builder for ShippingAddressParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ShippingAddressBuilder builder() {
      return new ShippingAddressBuilder();
    }

    public static final class ShippingAddressBuilder {

      private String firstName;

      private String lastName;

      private String email;

      private String company;

      private String phone;

      private String line1;

      private String line2;

      private String line3;

      private String city;

      private String stateCode;

      private String state;

      private String zip;

      private String country;

      private ValidationStatus validationStatus;

      private ShippingAddressBuilder() {}

      public ShippingAddressBuilder firstName(String value) {
        this.firstName = value;
        return this;
      }

      public ShippingAddressBuilder lastName(String value) {
        this.lastName = value;
        return this;
      }

      public ShippingAddressBuilder email(String value) {
        this.email = value;
        return this;
      }

      public ShippingAddressBuilder company(String value) {
        this.company = value;
        return this;
      }

      public ShippingAddressBuilder phone(String value) {
        this.phone = value;
        return this;
      }

      public ShippingAddressBuilder line1(String value) {
        this.line1 = value;
        return this;
      }

      public ShippingAddressBuilder line2(String value) {
        this.line2 = value;
        return this;
      }

      public ShippingAddressBuilder line3(String value) {
        this.line3 = value;
        return this;
      }

      public ShippingAddressBuilder city(String value) {
        this.city = value;
        return this;
      }

      public ShippingAddressBuilder stateCode(String value) {
        this.stateCode = value;
        return this;
      }

      public ShippingAddressBuilder state(String value) {
        this.state = value;
        return this;
      }

      public ShippingAddressBuilder zip(String value) {
        this.zip = value;
        return this;
      }

      public ShippingAddressBuilder country(String value) {
        this.country = value;
        return this;
      }

      public ShippingAddressBuilder validationStatus(ValidationStatus value) {
        this.validationStatus = value;
        return this;
      }

      public ShippingAddressParams build() {
        return new ShippingAddressParams(this);
      }
    }

    public enum ValidationStatus {
      NOT_VALIDATED("not_validated"),

      VALID("valid"),

      PARTIALLY_VALID("partially_valid"),

      INVALID("invalid"),

      /** An enum member indicating that ValidationStatus was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ValidationStatus(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ValidationStatus fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ValidationStatus enumValue : ValidationStatus.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class ItemPricesParams {

    private final String itemPriceId;

    private final Integer quantity;

    private final String quantityInDecimal;

    private final Long unitPrice;

    private final String unitPriceInDecimal;

    private final Integer servicePeriodDays;

    private ItemPricesParams(ItemPricesBuilder builder) {

      this.itemPriceId = builder.itemPriceId;

      this.quantity = builder.quantity;

      this.quantityInDecimal = builder.quantityInDecimal;

      this.unitPrice = builder.unitPrice;

      this.unitPriceInDecimal = builder.unitPriceInDecimal;

      this.servicePeriodDays = builder.servicePeriodDays;
    }

    public String getItemPriceId() {
      return itemPriceId;
    }

    public Integer getQuantity() {
      return quantity;
    }

    public String getQuantityInDecimal() {
      return quantityInDecimal;
    }

    public Long getUnitPrice() {
      return unitPrice;
    }

    public String getUnitPriceInDecimal() {
      return unitPriceInDecimal;
    }

    public Integer getServicePeriodDays() {
      return servicePeriodDays;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.itemPriceId != null) {

        formData.put("item_price_id", this.itemPriceId);
      }

      if (this.quantity != null) {

        formData.put("quantity", this.quantity);
      }

      if (this.quantityInDecimal != null) {

        formData.put("quantity_in_decimal", this.quantityInDecimal);
      }

      if (this.unitPrice != null) {

        formData.put("unit_price", this.unitPrice);
      }

      if (this.unitPriceInDecimal != null) {

        formData.put("unit_price_in_decimal", this.unitPriceInDecimal);
      }

      if (this.servicePeriodDays != null) {

        formData.put("service_period_days", this.servicePeriodDays);
      }

      return formData;
    }

    /** Create a new builder for ItemPricesParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ItemPricesBuilder builder() {
      return new ItemPricesBuilder();
    }

    public static final class ItemPricesBuilder {

      private String itemPriceId;

      private Integer quantity;

      private String quantityInDecimal;

      private Long unitPrice;

      private String unitPriceInDecimal;

      private Integer servicePeriodDays;

      private ItemPricesBuilder() {}

      public ItemPricesBuilder itemPriceId(String value) {
        this.itemPriceId = value;
        return this;
      }

      public ItemPricesBuilder quantity(Integer value) {
        this.quantity = value;
        return this;
      }

      public ItemPricesBuilder quantityInDecimal(String value) {
        this.quantityInDecimal = value;
        return this;
      }

      public ItemPricesBuilder unitPrice(Long value) {
        this.unitPrice = value;
        return this;
      }

      public ItemPricesBuilder unitPriceInDecimal(String value) {
        this.unitPriceInDecimal = value;
        return this;
      }

      public ItemPricesBuilder servicePeriodDays(Integer value) {
        this.servicePeriodDays = value;
        return this;
      }

      public ItemPricesParams build() {
        return new ItemPricesParams(this);
      }
    }
  }

  public static final class ItemTiersParams {

    private final String itemPriceId;

    private final Integer startingUnit;

    private final Integer endingUnit;

    private final Long price;

    private final String startingUnitInDecimal;

    private final String endingUnitInDecimal;

    private final String priceInDecimal;

    private final PricingType pricingType;

    private final Integer packageSize;

    private ItemTiersParams(ItemTiersBuilder builder) {

      this.itemPriceId = builder.itemPriceId;

      this.startingUnit = builder.startingUnit;

      this.endingUnit = builder.endingUnit;

      this.price = builder.price;

      this.startingUnitInDecimal = builder.startingUnitInDecimal;

      this.endingUnitInDecimal = builder.endingUnitInDecimal;

      this.priceInDecimal = builder.priceInDecimal;

      this.pricingType = builder.pricingType;

      this.packageSize = builder.packageSize;
    }

    public String getItemPriceId() {
      return itemPriceId;
    }

    public Integer getStartingUnit() {
      return startingUnit;
    }

    public Integer getEndingUnit() {
      return endingUnit;
    }

    public Long getPrice() {
      return price;
    }

    public String getStartingUnitInDecimal() {
      return startingUnitInDecimal;
    }

    public String getEndingUnitInDecimal() {
      return endingUnitInDecimal;
    }

    public String getPriceInDecimal() {
      return priceInDecimal;
    }

    public PricingType getPricingType() {
      return pricingType;
    }

    public Integer getPackageSize() {
      return packageSize;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.itemPriceId != null) {

        formData.put("item_price_id", this.itemPriceId);
      }

      if (this.startingUnit != null) {

        formData.put("starting_unit", this.startingUnit);
      }

      if (this.endingUnit != null) {

        formData.put("ending_unit", this.endingUnit);
      }

      if (this.price != null) {

        formData.put("price", this.price);
      }

      if (this.startingUnitInDecimal != null) {

        formData.put("starting_unit_in_decimal", this.startingUnitInDecimal);
      }

      if (this.endingUnitInDecimal != null) {

        formData.put("ending_unit_in_decimal", this.endingUnitInDecimal);
      }

      if (this.priceInDecimal != null) {

        formData.put("price_in_decimal", this.priceInDecimal);
      }

      if (this.pricingType != null) {

        formData.put("pricing_type", this.pricingType);
      }

      if (this.packageSize != null) {

        formData.put("package_size", this.packageSize);
      }

      return formData;
    }

    /** Create a new builder for ItemTiersParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ItemTiersBuilder builder() {
      return new ItemTiersBuilder();
    }

    public static final class ItemTiersBuilder {

      private String itemPriceId;

      private Integer startingUnit;

      private Integer endingUnit;

      private Long price;

      private String startingUnitInDecimal;

      private String endingUnitInDecimal;

      private String priceInDecimal;

      private PricingType pricingType;

      private Integer packageSize;

      private ItemTiersBuilder() {}

      public ItemTiersBuilder itemPriceId(String value) {
        this.itemPriceId = value;
        return this;
      }

      public ItemTiersBuilder startingUnit(Integer value) {
        this.startingUnit = value;
        return this;
      }

      public ItemTiersBuilder endingUnit(Integer value) {
        this.endingUnit = value;
        return this;
      }

      public ItemTiersBuilder price(Long value) {
        this.price = value;
        return this;
      }

      public ItemTiersBuilder startingUnitInDecimal(String value) {
        this.startingUnitInDecimal = value;
        return this;
      }

      public ItemTiersBuilder endingUnitInDecimal(String value) {
        this.endingUnitInDecimal = value;
        return this;
      }

      public ItemTiersBuilder priceInDecimal(String value) {
        this.priceInDecimal = value;
        return this;
      }

      public ItemTiersBuilder pricingType(PricingType value) {
        this.pricingType = value;
        return this;
      }

      public ItemTiersBuilder packageSize(Integer value) {
        this.packageSize = value;
        return this;
      }

      public ItemTiersParams build() {
        return new ItemTiersParams(this);
      }
    }

    public enum PricingType {
      PER_UNIT("per_unit"),

      FLAT_FEE("flat_fee"),

      PACKAGE("package"),

      /** An enum member indicating that PricingType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      PricingType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PricingType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PricingType enumValue : PricingType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class ChargesParams {

    private final Long amount;

    private final String amountInDecimal;

    private final String description;

    private final AvalaraSaleType avalaraSaleType;

    private final Integer avalaraTransactionType;

    private final Integer avalaraServiceType;

    private final Integer servicePeriod;

    private ChargesParams(ChargesBuilder builder) {

      this.amount = builder.amount;

      this.amountInDecimal = builder.amountInDecimal;

      this.description = builder.description;

      this.avalaraSaleType = builder.avalaraSaleType;

      this.avalaraTransactionType = builder.avalaraTransactionType;

      this.avalaraServiceType = builder.avalaraServiceType;

      this.servicePeriod = builder.servicePeriod;
    }

    public Long getAmount() {
      return amount;
    }

    public String getAmountInDecimal() {
      return amountInDecimal;
    }

    public String getDescription() {
      return description;
    }

    public AvalaraSaleType getAvalaraSaleType() {
      return avalaraSaleType;
    }

    public Integer getAvalaraTransactionType() {
      return avalaraTransactionType;
    }

    public Integer getAvalaraServiceType() {
      return avalaraServiceType;
    }

    public Integer getServicePeriod() {
      return servicePeriod;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.amount != null) {

        formData.put("amount", this.amount);
      }

      if (this.amountInDecimal != null) {

        formData.put("amount_in_decimal", this.amountInDecimal);
      }

      if (this.description != null) {

        formData.put("description", this.description);
      }

      if (this.avalaraSaleType != null) {

        formData.put("avalara_sale_type", this.avalaraSaleType);
      }

      if (this.avalaraTransactionType != null) {

        formData.put("avalara_transaction_type", this.avalaraTransactionType);
      }

      if (this.avalaraServiceType != null) {

        formData.put("avalara_service_type", this.avalaraServiceType);
      }

      if (this.servicePeriod != null) {

        formData.put("service_period", this.servicePeriod);
      }

      return formData;
    }

    /** Create a new builder for ChargesParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ChargesBuilder builder() {
      return new ChargesBuilder();
    }

    public static final class ChargesBuilder {

      private Long amount;

      private String amountInDecimal;

      private String description;

      private AvalaraSaleType avalaraSaleType;

      private Integer avalaraTransactionType;

      private Integer avalaraServiceType;

      private Integer servicePeriod;

      private ChargesBuilder() {}

      public ChargesBuilder amount(Long value) {
        this.amount = value;
        return this;
      }

      public ChargesBuilder amountInDecimal(String value) {
        this.amountInDecimal = value;
        return this;
      }

      public ChargesBuilder description(String value) {
        this.description = value;
        return this;
      }

      public ChargesBuilder avalaraSaleType(AvalaraSaleType value) {
        this.avalaraSaleType = value;
        return this;
      }

      public ChargesBuilder avalaraTransactionType(Integer value) {
        this.avalaraTransactionType = value;
        return this;
      }

      public ChargesBuilder avalaraServiceType(Integer value) {
        this.avalaraServiceType = value;
        return this;
      }

      public ChargesBuilder servicePeriod(Integer value) {
        this.servicePeriod = value;
        return this;
      }

      public ChargesParams build() {
        return new ChargesParams(this);
      }
    }

    public enum AvalaraSaleType {
      WHOLESALE("wholesale"),

      RETAIL("retail"),

      CONSUMED("consumed"),

      VENDOR_USE("vendor_use"),

      /** An enum member indicating that AvalaraSaleType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      AvalaraSaleType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static AvalaraSaleType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (AvalaraSaleType enumValue : AvalaraSaleType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class DiscountsParams {

    private final Double percentage;

    private final Integer quantity;

    private final Long amount;

    private final ApplyOn applyOn;

    private final String itemPriceId;

    private DiscountsParams(DiscountsBuilder builder) {

      this.percentage = builder.percentage;

      this.quantity = builder.quantity;

      this.amount = builder.amount;

      this.applyOn = builder.applyOn;

      this.itemPriceId = builder.itemPriceId;
    }

    public Double getPercentage() {
      return percentage;
    }

    public Integer getQuantity() {
      return quantity;
    }

    public Long getAmount() {
      return amount;
    }

    public ApplyOn getApplyOn() {
      return applyOn;
    }

    public String getItemPriceId() {
      return itemPriceId;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.percentage != null) {

        formData.put("percentage", this.percentage);
      }

      if (this.quantity != null) {

        formData.put("quantity", this.quantity);
      }

      if (this.amount != null) {

        formData.put("amount", this.amount);
      }

      if (this.applyOn != null) {

        formData.put("apply_on", this.applyOn);
      }

      if (this.itemPriceId != null) {

        formData.put("item_price_id", this.itemPriceId);
      }

      return formData;
    }

    /** Create a new builder for DiscountsParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static DiscountsBuilder builder() {
      return new DiscountsBuilder();
    }

    public static final class DiscountsBuilder {

      private Double percentage;

      private Integer quantity;

      private Long amount;

      private ApplyOn applyOn;

      private String itemPriceId;

      private DiscountsBuilder() {}

      public DiscountsBuilder percentage(Double value) {
        this.percentage = value;
        return this;
      }

      public DiscountsBuilder quantity(Integer value) {
        this.quantity = value;
        return this;
      }

      public DiscountsBuilder amount(Long value) {
        this.amount = value;
        return this;
      }

      public DiscountsBuilder applyOn(ApplyOn value) {
        this.applyOn = value;
        return this;
      }

      public DiscountsBuilder itemPriceId(String value) {
        this.itemPriceId = value;
        return this;
      }

      public DiscountsParams build() {
        return new DiscountsParams(this);
      }
    }

    public enum ApplyOn {
      INVOICE_AMOUNT("invoice_amount"),

      SPECIFIC_ITEM_PRICE("specific_item_price"),

      /** An enum member indicating that ApplyOn was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ApplyOn(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ApplyOn fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ApplyOn enumValue : ApplyOn.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class TaxProvidersFieldsParams {

    private final String providerName;

    private final String fieldId;

    private final String fieldValue;

    private TaxProvidersFieldsParams(TaxProvidersFieldsBuilder builder) {

      this.providerName = builder.providerName;

      this.fieldId = builder.fieldId;

      this.fieldValue = builder.fieldValue;
    }

    public String getProviderName() {
      return providerName;
    }

    public String getFieldId() {
      return fieldId;
    }

    public String getFieldValue() {
      return fieldValue;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.providerName != null) {

        formData.put("provider_name", this.providerName);
      }

      if (this.fieldId != null) {

        formData.put("field_id", this.fieldId);
      }

      if (this.fieldValue != null) {

        formData.put("field_value", this.fieldValue);
      }

      return formData;
    }

    /** Create a new builder for TaxProvidersFieldsParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static TaxProvidersFieldsBuilder builder() {
      return new TaxProvidersFieldsBuilder();
    }

    public static final class TaxProvidersFieldsBuilder {

      private String providerName;

      private String fieldId;

      private String fieldValue;

      private TaxProvidersFieldsBuilder() {}

      public TaxProvidersFieldsBuilder providerName(String value) {
        this.providerName = value;
        return this;
      }

      public TaxProvidersFieldsBuilder fieldId(String value) {
        this.fieldId = value;
        return this;
      }

      public TaxProvidersFieldsBuilder fieldValue(String value) {
        this.fieldValue = value;
        return this;
      }

      public TaxProvidersFieldsParams build() {
        return new TaxProvidersFieldsParams(this);
      }
    }
  }
}
