/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.core.models.invoice.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class InvoiceUpdateDetailsParams {

  private final Map<String, Object> formData;

  private InvoiceUpdateDetailsParams(InvoiceUpdateDetailsBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for InvoiceUpdateDetailsParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static InvoiceUpdateDetailsBuilder builder() {
    return new InvoiceUpdateDetailsBuilder();
  }

  public static final class InvoiceUpdateDetailsBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private InvoiceUpdateDetailsBuilder() {}

    public InvoiceUpdateDetailsBuilder vatNumber(String value) {

      formData.put("vat_number", value);

      return this;
    }

    public InvoiceUpdateDetailsBuilder vatNumberPrefix(String value) {

      formData.put("vat_number_prefix", value);

      return this;
    }

    public InvoiceUpdateDetailsBuilder poNumber(String value) {

      formData.put("po_number", value);

      return this;
    }

    public InvoiceUpdateDetailsBuilder comment(String value) {

      formData.put("comment", value);

      return this;
    }

    public InvoiceUpdateDetailsBuilder billingAddress(BillingAddressParams value) {
      if (value != null) {
        Map<String, Object> nestedData = value.toFormData();
        for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
          String nestedKey = "billing_address[" + entry.getKey() + "]";
          formData.put(nestedKey, entry.getValue());
        }
      }
      return this;
    }

    public InvoiceUpdateDetailsBuilder shippingAddress(ShippingAddressParams value) {
      if (value != null) {
        Map<String, Object> nestedData = value.toFormData();
        for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
          String nestedKey = "shipping_address[" + entry.getKey() + "]";
          formData.put(nestedKey, entry.getValue());
        }
      }
      return this;
    }

    public InvoiceUpdateDetailsBuilder statementDescriptor(StatementDescriptorParams value) {
      if (value != null) {
        Map<String, Object> nestedData = value.toFormData();
        for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
          String nestedKey = "statement_descriptor[" + entry.getKey() + "]";
          formData.put(nestedKey, entry.getValue());
        }
      }
      return this;
    }

    /**
     * Add a custom field to the request. Custom fields must start with "cf_".
     *
     * @param fieldName the name of the custom field (e.g., "cf_custom_field_name")
     * @param value the value of the custom field
     * @return this builder
     * @throws IllegalArgumentException if fieldName doesn't start with "cf_"
     */
    public InvoiceUpdateDetailsBuilder customField(String fieldName, Object value) {
      if (fieldName == null || !fieldName.startsWith("cf_")) {
        throw new IllegalArgumentException("Custom field name must start with 'cf_'");
      }
      formData.put(fieldName, value);
      return this;
    }

    /**
     * Add multiple custom fields to the request. All field names must start with "cf_".
     *
     * @param customFields map of custom field names to values
     * @return this builder
     * @throws IllegalArgumentException if any field name doesn't start with "cf_"
     */
    public InvoiceUpdateDetailsBuilder customFields(Map<String, Object> customFields) {
      if (customFields != null) {
        for (Map.Entry<String, Object> entry : customFields.entrySet()) {
          if (entry.getKey() == null || !entry.getKey().startsWith("cf_")) {
            throw new IllegalArgumentException(
                "Custom field name must start with 'cf_': " + entry.getKey());
          }
          formData.put(entry.getKey(), entry.getValue());
        }
      }
      return this;
    }

    public InvoiceUpdateDetailsParams build() {
      return new InvoiceUpdateDetailsParams(this);
    }
  }

  public static final class BillingAddressParams {

    private final Map<String, Object> formData;

    private BillingAddressParams(BillingAddressBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for BillingAddressParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static BillingAddressBuilder builder() {
      return new BillingAddressBuilder();
    }

    public static final class BillingAddressBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private BillingAddressBuilder() {}

      public BillingAddressBuilder firstName(String value) {

        formData.put("first_name", value);

        return this;
      }

      public BillingAddressBuilder lastName(String value) {

        formData.put("last_name", value);

        return this;
      }

      public BillingAddressBuilder email(String value) {

        formData.put("email", value);

        return this;
      }

      public BillingAddressBuilder company(String value) {

        formData.put("company", value);

        return this;
      }

      public BillingAddressBuilder phone(String value) {

        formData.put("phone", value);

        return this;
      }

      public BillingAddressBuilder line1(String value) {

        formData.put("line1", value);

        return this;
      }

      public BillingAddressBuilder line2(String value) {

        formData.put("line2", value);

        return this;
      }

      public BillingAddressBuilder line3(String value) {

        formData.put("line3", value);

        return this;
      }

      public BillingAddressBuilder city(String value) {

        formData.put("city", value);

        return this;
      }

      public BillingAddressBuilder stateCode(String value) {

        formData.put("state_code", value);

        return this;
      }

      public BillingAddressBuilder state(String value) {

        formData.put("state", value);

        return this;
      }

      public BillingAddressBuilder zip(String value) {

        formData.put("zip", value);

        return this;
      }

      public BillingAddressBuilder country(String value) {

        formData.put("country", value);

        return this;
      }

      public BillingAddressBuilder validationStatus(ValidationStatus value) {

        formData.put("validation_status", value);

        return this;
      }

      public BillingAddressParams build() {
        return new BillingAddressParams(this);
      }
    }

    public enum ValidationStatus {
      NOT_VALIDATED("not_validated"),

      VALID("valid"),

      PARTIALLY_VALID("partially_valid"),

      INVALID("invalid"),

      /** An enum member indicating that ValidationStatus was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ValidationStatus(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ValidationStatus fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ValidationStatus enumValue : ValidationStatus.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class ShippingAddressParams {

    private final Map<String, Object> formData;

    private ShippingAddressParams(ShippingAddressBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for ShippingAddressParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ShippingAddressBuilder builder() {
      return new ShippingAddressBuilder();
    }

    public static final class ShippingAddressBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private ShippingAddressBuilder() {}

      public ShippingAddressBuilder firstName(String value) {

        formData.put("first_name", value);

        return this;
      }

      public ShippingAddressBuilder lastName(String value) {

        formData.put("last_name", value);

        return this;
      }

      public ShippingAddressBuilder email(String value) {

        formData.put("email", value);

        return this;
      }

      public ShippingAddressBuilder company(String value) {

        formData.put("company", value);

        return this;
      }

      public ShippingAddressBuilder phone(String value) {

        formData.put("phone", value);

        return this;
      }

      public ShippingAddressBuilder line1(String value) {

        formData.put("line1", value);

        return this;
      }

      public ShippingAddressBuilder line2(String value) {

        formData.put("line2", value);

        return this;
      }

      public ShippingAddressBuilder line3(String value) {

        formData.put("line3", value);

        return this;
      }

      public ShippingAddressBuilder city(String value) {

        formData.put("city", value);

        return this;
      }

      public ShippingAddressBuilder stateCode(String value) {

        formData.put("state_code", value);

        return this;
      }

      public ShippingAddressBuilder state(String value) {

        formData.put("state", value);

        return this;
      }

      public ShippingAddressBuilder zip(String value) {

        formData.put("zip", value);

        return this;
      }

      public ShippingAddressBuilder country(String value) {

        formData.put("country", value);

        return this;
      }

      public ShippingAddressBuilder validationStatus(ValidationStatus value) {

        formData.put("validation_status", value);

        return this;
      }

      public ShippingAddressParams build() {
        return new ShippingAddressParams(this);
      }
    }

    public enum ValidationStatus {
      NOT_VALIDATED("not_validated"),

      VALID("valid"),

      PARTIALLY_VALID("partially_valid"),

      INVALID("invalid"),

      /** An enum member indicating that ValidationStatus was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ValidationStatus(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ValidationStatus fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ValidationStatus enumValue : ValidationStatus.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }

  public static final class StatementDescriptorParams {

    private final Map<String, Object> formData;

    private StatementDescriptorParams(StatementDescriptorBuilder builder) {
      this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      return formData;
    }

    /** Create a new builder for StatementDescriptorParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static StatementDescriptorBuilder builder() {
      return new StatementDescriptorBuilder();
    }

    public static final class StatementDescriptorBuilder {
      private final Map<String, Object> formData = new LinkedHashMap<>();

      private StatementDescriptorBuilder() {}

      public StatementDescriptorBuilder descriptor(String value) {

        formData.put("descriptor", value);

        return this;
      }

      public StatementDescriptorParams build() {
        return new StatementDescriptorParams(this);
      }
    }
  }
}
