package com.chargebee.models.enums;

public enum PaymentMethod {
    CASH,
    CHECK,
    BANK_TRANSFER,
    OTHER,
    CUSTOM,
    CHARGEBACK,
    CARD,
    AMAZON_PAYMENTS,
    PAYPAL_EXPRESS_CHECKOUT,
    DIRECT_DEBIT,
    ALIPAY,
    UNIONPAY,
    APPLE_PAY,
    WECHAT_PAY,
    ACH_CREDIT,
    SEPA_CREDIT,
    IDEAL,
    GOOGLE_PAY,
    SOFORT,
    BANCONTACT,
    GIROPAY,
    DOTPAY,
    UPI,
    NETBANKING_EMANDATES,
    BOLETO,
    VENMO,
    PAY_TO,
    FASTER_PAYMENTS,
    SEPA_INSTANT_TRANSFER,
    AUTOMATED_BANK_TRANSFER,
    KLARNA_PAY_NOW,
    ONLINE_BANKING_POLAND,
    _UNKNOWN; /*Indicates unexpected value for this enum. You can get this when there is a
    java-client version incompatibility. We suggest you to upgrade to the latest version */
}