package com.chargebee.models.enums;

public enum Type {
    CARD,
    PAYPAL_EXPRESS_CHECKOUT,
    AMAZON_PAYMENTS,
    DIRECT_DEBIT,
    GENERIC,
    ALIPAY,
    UNIONPAY,
    APPLE_PAY,
    WECHAT_PAY,
    IDEAL,
    GOOGLE_PAY,
    SOFORT,
    BANCONTACT,
    GIROPAY,
    DOTPAY,
    UPI,
    NETBANKING_EMANDATES,
    VENMO,
    PAY_TO,
    FASTER_PAYMENTS,
    SEPA_INSTANT_TRANSFER,
    AUTOMATED_BANK_TRANSFER,
    KLARNA_PAY_NOW,
    ONLINE_BANKING_POLAND,
    PAYCONIQ_BY_BANCONTACT,
    ELECTRONIC_PAYMENT_STANDARD,
    KBC_PAYMENT_BUTTON,
    PAY_BY_BANK,
    TRUSTLY,
    STABLECOIN,
    KAKAO_PAY,
    NAVER_PAY,
    REVOLUT_PAY,
    CASH_APP_PAY,
    TWINT,
    GO_PAY,
    GRAB_PAY,
    PAY_CO,
    AFTER_PAY,
    SWISH,
    PAYME,
    PIX,
    KLARNA,
    ALIPAY_HK,
    PAYPAY,
    GCASH,
    SOUTH_KOREAN_CARDS,
    FREE_TRIAL,
    PAY_UP_FRONT,
    PAY_AS_YOU_GO,
    USAGE_EXCEEDED,
    _UNKNOWN; /*Indicates unexpected value for this enum. You can get this when there is a
    java-client version incompatibility. We suggest you to upgrade to the latest version */
}