/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.advanceInvoiceSchedule;

import com.chargebee.v4.internal.JsonUtil;
import java.sql.Timestamp;

public class AdvanceInvoiceSchedule {

  private String id;
  private ScheduleType scheduleType;
  private FixedIntervalSchedule fixedIntervalSchedule;
  private SpecificDatesSchedule specificDatesSchedule;

  public String getId() {
    return id;
  }

  public ScheduleType getScheduleType() {
    return scheduleType;
  }

  public FixedIntervalSchedule getFixedIntervalSchedule() {
    return fixedIntervalSchedule;
  }

  public SpecificDatesSchedule getSpecificDatesSchedule() {
    return specificDatesSchedule;
  }

  public enum ScheduleType {
    FIXED_INTERVALS("fixed_intervals"),

    SPECIFIC_DATES("specific_dates"),

    /** An enum member indicating that ScheduleType was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    ScheduleType(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static ScheduleType fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (ScheduleType enumValue : ScheduleType.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static AdvanceInvoiceSchedule fromJson(String json) {
    AdvanceInvoiceSchedule obj = new AdvanceInvoiceSchedule();

    obj.id = JsonUtil.getString(json, "id");

    obj.scheduleType = ScheduleType.fromString(JsonUtil.getString(json, "schedule_type"));

    String __fixedIntervalScheduleJson = JsonUtil.getObject(json, "fixed_interval_schedule");
    if (__fixedIntervalScheduleJson != null) {
      obj.fixedIntervalSchedule = FixedIntervalSchedule.fromJson(__fixedIntervalScheduleJson);
    }

    String __specificDatesScheduleJson = JsonUtil.getObject(json, "specific_dates_schedule");
    if (__specificDatesScheduleJson != null) {
      obj.specificDatesSchedule = SpecificDatesSchedule.fromJson(__specificDatesScheduleJson);
    }

    return obj;
  }

  public static class FixedIntervalSchedule {

    private EndScheduleOn endScheduleOn;
    private Integer numberOfOccurrences;
    private Integer daysBeforeRenewal;
    private Timestamp endDate;
    private Timestamp createdAt;
    private Integer termsToCharge;

    public EndScheduleOn getEndScheduleOn() {
      return endScheduleOn;
    }

    public Integer getNumberOfOccurrences() {
      return numberOfOccurrences;
    }

    public Integer getDaysBeforeRenewal() {
      return daysBeforeRenewal;
    }

    public Timestamp getEndDate() {
      return endDate;
    }

    public Timestamp getCreatedAt() {
      return createdAt;
    }

    public Integer getTermsToCharge() {
      return termsToCharge;
    }

    public enum EndScheduleOn {
      AFTER_NUMBER_OF_INTERVALS("after_number_of_intervals"),

      SPECIFIC_DATE("specific_date"),

      SUBSCRIPTION_END("subscription_end"),

      /** An enum member indicating that EndScheduleOn was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      EndScheduleOn(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static EndScheduleOn fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (EndScheduleOn enumValue : EndScheduleOn.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static FixedIntervalSchedule fromJson(String json) {
      FixedIntervalSchedule obj = new FixedIntervalSchedule();

      obj.endScheduleOn = EndScheduleOn.fromString(JsonUtil.getString(json, "end_schedule_on"));

      obj.numberOfOccurrences = JsonUtil.getInteger(json, "number_of_occurrences");

      obj.daysBeforeRenewal = JsonUtil.getInteger(json, "days_before_renewal");

      obj.endDate = JsonUtil.getTimestamp(json, "end_date");

      obj.createdAt = JsonUtil.getTimestamp(json, "created_at");

      obj.termsToCharge = JsonUtil.getInteger(json, "terms_to_charge");

      return obj;
    }
  }

  public static class SpecificDatesSchedule {

    private Integer termsToCharge;
    private Timestamp date;
    private Timestamp createdAt;

    public Integer getTermsToCharge() {
      return termsToCharge;
    }

    public Timestamp getDate() {
      return date;
    }

    public Timestamp getCreatedAt() {
      return createdAt;
    }

    public static SpecificDatesSchedule fromJson(String json) {
      SpecificDatesSchedule obj = new SpecificDatesSchedule();

      obj.termsToCharge = JsonUtil.getInteger(json, "terms_to_charge");

      obj.date = JsonUtil.getTimestamp(json, "date");

      obj.createdAt = JsonUtil.getTimestamp(json, "created_at");

      return obj;
    }
  }
}
