/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.attachedItem.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class AttachedItemRetrieveParams {

  private final Map<String, Object> queryParams;

  private AttachedItemRetrieveParams(AttachedItemRetrieveBuilder builder) {
    this.queryParams = Collections.unmodifiableMap(new LinkedHashMap<>(builder.queryParams));
  }

  /** Get the query parameters for this request. */
  public Map<String, Object> toQueryParams() {
    return queryParams;
  }

  public AttachedItemRetrieveBuilder toBuilder() {
    AttachedItemRetrieveBuilder builder = new AttachedItemRetrieveBuilder();
    builder.queryParams.putAll(queryParams);
    return builder;
  }

  /** Create a new builder for AttachedItemRetrieveParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static AttachedItemRetrieveBuilder builder() {
    return new AttachedItemRetrieveBuilder();
  }

  public static final class AttachedItemRetrieveBuilder {
    private final Map<String, Object> queryParams = new LinkedHashMap<>();

    private AttachedItemRetrieveBuilder() {}

    public AttachedItemRetrieveBuilder parentItemId(String value) {
      queryParams.put("parent_item_id", value);
      return this;
    }

    public AttachedItemRetrieveParams build() {
      return new AttachedItemRetrieveParams(this);
    }
  }
}
