/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.recordedPurchase;

import com.chargebee.v4.internal.JsonUtil;
import com.google.gson.JsonObject;
import java.sql.Timestamp;
import java.util.List;

public class RecordedPurchase {

  private String id;
  private String customerId;
  private String appId;
  private Source source;
  private Status status;
  private String omnichannelTransactionId;
  private Timestamp createdAt;
  private Long resourceVersion;
  private List<LinkedOmnichannelSubscriptions> linkedOmnichannelSubscriptions;
  private List<LinkedOmnichannelOneTimeOrders> linkedOmnichannelOneTimeOrders;
  private ErrorDetail errorDetail;

  public String getId() {
    return id;
  }

  public String getCustomerId() {
    return customerId;
  }

  public String getAppId() {
    return appId;
  }

  public Source getSource() {
    return source;
  }

  public Status getStatus() {
    return status;
  }

  public String getOmnichannelTransactionId() {
    return omnichannelTransactionId;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public List<LinkedOmnichannelSubscriptions> getLinkedOmnichannelSubscriptions() {
    return linkedOmnichannelSubscriptions;
  }

  public List<LinkedOmnichannelOneTimeOrders> getLinkedOmnichannelOneTimeOrders() {
    return linkedOmnichannelOneTimeOrders;
  }

  public ErrorDetail getErrorDetail() {
    return errorDetail;
  }

  public enum Source {
    APPLE_APP_STORE("apple_app_store"),

    GOOGLE_PLAY_STORE("google_play_store"),

    /** An enum member indicating that Source was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Source(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Source fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Source enumValue : Source.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum Status {
    IN_PROCESS("in_process"),

    COMPLETED("completed"),

    FAILED("failed"),

    IGNORED("ignored"),

    /** An enum member indicating that Status was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Status(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Status fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Status enumValue : Status.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static RecordedPurchase fromJson(String json) {
    return fromJson(JsonUtil.parse(json));
  }

  public static RecordedPurchase fromJson(java.util.Map<String, Object> map) {
    return fromJson(JsonUtil.toJson(map));
  }

  public static RecordedPurchase fromJson(JsonObject jsonObj) {
    RecordedPurchase obj = new RecordedPurchase();

    obj.id = JsonUtil.getString(jsonObj, "id");

    obj.customerId = JsonUtil.getString(jsonObj, "customer_id");

    obj.appId = JsonUtil.getString(jsonObj, "app_id");

    obj.source = Source.fromString(JsonUtil.getString(jsonObj, "source"));

    obj.status = Status.fromString(JsonUtil.getString(jsonObj, "status"));

    obj.omnichannelTransactionId = JsonUtil.getString(jsonObj, "omnichannel_transaction_id");

    obj.createdAt = JsonUtil.getTimestamp(jsonObj, "created_at");

    obj.resourceVersion = JsonUtil.getLong(jsonObj, "resource_version");

    obj.linkedOmnichannelSubscriptions =
        JsonUtil.mapArray(
            JsonUtil.getJsonArray(jsonObj, "linked_omnichannel_subscriptions"),
            LinkedOmnichannelSubscriptions::fromJson);

    obj.linkedOmnichannelOneTimeOrders =
        JsonUtil.mapArray(
            JsonUtil.getJsonArray(jsonObj, "linked_omnichannel_one_time_orders"),
            LinkedOmnichannelOneTimeOrders::fromJson);

    JsonObject __errorDetailObj = JsonUtil.getJsonObject(jsonObj, "error_detail");
    if (__errorDetailObj != null) {
      obj.errorDetail = ErrorDetail.fromJson(__errorDetailObj);
    }

    return obj;
  }

  @Override
  public String toString() {
    return "RecordedPurchase{"
        + "id="
        + id
        + ", customerId="
        + customerId
        + ", appId="
        + appId
        + ", source="
        + source
        + ", status="
        + status
        + ", omnichannelTransactionId="
        + omnichannelTransactionId
        + ", createdAt="
        + createdAt
        + ", resourceVersion="
        + resourceVersion
        + ", linkedOmnichannelSubscriptions="
        + linkedOmnichannelSubscriptions
        + ", linkedOmnichannelOneTimeOrders="
        + linkedOmnichannelOneTimeOrders
        + ", errorDetail="
        + errorDetail
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    RecordedPurchase that = (RecordedPurchase) o;
    return java.util.Objects.equals(id, that.id)
        && java.util.Objects.equals(customerId, that.customerId)
        && java.util.Objects.equals(appId, that.appId)
        && java.util.Objects.equals(source, that.source)
        && java.util.Objects.equals(status, that.status)
        && java.util.Objects.equals(omnichannelTransactionId, that.omnichannelTransactionId)
        && java.util.Objects.equals(createdAt, that.createdAt)
        && java.util.Objects.equals(resourceVersion, that.resourceVersion)
        && java.util.Objects.equals(
            linkedOmnichannelSubscriptions, that.linkedOmnichannelSubscriptions)
        && java.util.Objects.equals(
            linkedOmnichannelOneTimeOrders, that.linkedOmnichannelOneTimeOrders)
        && java.util.Objects.equals(errorDetail, that.errorDetail);
  }

  @Override
  public int hashCode() {

    return java.util.Objects.hash(
        id,
        customerId,
        appId,
        source,
        status,
        omnichannelTransactionId,
        createdAt,
        resourceVersion,
        linkedOmnichannelSubscriptions,
        linkedOmnichannelOneTimeOrders,
        errorDetail);
  }

  public static class LinkedOmnichannelSubscriptions {

    private String omnichannelSubscriptionId;

    public String getOmnichannelSubscriptionId() {
      return omnichannelSubscriptionId;
    }

    public static LinkedOmnichannelSubscriptions fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static LinkedOmnichannelSubscriptions fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static LinkedOmnichannelSubscriptions fromJson(JsonObject jsonObj) {
      LinkedOmnichannelSubscriptions obj = new LinkedOmnichannelSubscriptions();

      obj.omnichannelSubscriptionId = JsonUtil.getString(jsonObj, "omnichannel_subscription_id");

      return obj;
    }

    @Override
    public String toString() {
      return "LinkedOmnichannelSubscriptions{"
          + "omnichannelSubscriptionId="
          + omnichannelSubscriptionId
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      LinkedOmnichannelSubscriptions that = (LinkedOmnichannelSubscriptions) o;
      return java.util.Objects.equals(omnichannelSubscriptionId, that.omnichannelSubscriptionId);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(omnichannelSubscriptionId);
    }
  }

  public static class LinkedOmnichannelOneTimeOrders {

    private String omnichannelOneTimeOrderId;

    public String getOmnichannelOneTimeOrderId() {
      return omnichannelOneTimeOrderId;
    }

    public static LinkedOmnichannelOneTimeOrders fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static LinkedOmnichannelOneTimeOrders fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static LinkedOmnichannelOneTimeOrders fromJson(JsonObject jsonObj) {
      LinkedOmnichannelOneTimeOrders obj = new LinkedOmnichannelOneTimeOrders();

      obj.omnichannelOneTimeOrderId = JsonUtil.getString(jsonObj, "omnichannel_one_time_order_id");

      return obj;
    }

    @Override
    public String toString() {
      return "LinkedOmnichannelOneTimeOrders{"
          + "omnichannelOneTimeOrderId="
          + omnichannelOneTimeOrderId
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      LinkedOmnichannelOneTimeOrders that = (LinkedOmnichannelOneTimeOrders) o;
      return java.util.Objects.equals(omnichannelOneTimeOrderId, that.omnichannelOneTimeOrderId);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(omnichannelOneTimeOrderId);
    }
  }

  public static class ErrorDetail {

    private String errorMessage;

    public String getErrorMessage() {
      return errorMessage;
    }

    public static ErrorDetail fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static ErrorDetail fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static ErrorDetail fromJson(JsonObject jsonObj) {
      ErrorDetail obj = new ErrorDetail();

      obj.errorMessage = JsonUtil.getString(jsonObj, "error_message");

      return obj;
    }

    @Override
    public String toString() {
      return "ErrorDetail{" + "errorMessage=" + errorMessage + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ErrorDetail that = (ErrorDetail) o;
      return java.util.Objects.equals(errorMessage, that.errorMessage);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(errorMessage);
    }
  }
}
