/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.feature;

import com.chargebee.v4.internal.JsonUtil;
import com.google.gson.JsonObject;
import java.sql.Timestamp;
import java.util.List;

public class Feature {

  private String id;
  private String name;
  private String description;
  private Status status;
  private Type type;
  private String unit;
  private Long resourceVersion;
  private Timestamp updatedAt;
  private Timestamp createdAt;
  private Boolean metered;
  private List<Levels> levels;

  private java.util.Map<String, String> customFields = new java.util.HashMap<>();

  public String getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public String getDescription() {
    return description;
  }

  public Status getStatus() {
    return status;
  }

  public Type getType() {
    return type;
  }

  public String getUnit() {
    return unit;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public Timestamp getUpdatedAt() {
    return updatedAt;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public Boolean getMetered() {
    return metered;
  }

  public List<Levels> getLevels() {
    return levels;
  }

  /**
   * Returns a map of custom fields. Custom fields are dynamic properties that follow the pattern
   * cf_* (e.g., cf_custom_field_name).
   *
   * @return map containing all custom fields
   */
  public java.util.Map<String, String> getCustomFields() {
    return customFields;
  }

  /**
   * Returns the value of a specific custom field.
   *
   * @param fieldName the name of the custom field (e.g., "cf_custom_field_name")
   * @return the value of the custom field, or null if not present
   */
  public String getCustomField(String fieldName) {
    return customFields.get(fieldName);
  }

  public enum Status {
    ACTIVE("active"),

    ARCHIVED("archived"),

    DRAFT("draft"),

    /** An enum member indicating that Status was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Status(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Status fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Status enumValue : Status.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum Type {
    SWITCH("switch"),

    CUSTOM("custom"),

    QUANTITY("quantity"),

    RANGE("range"),

    /** An enum member indicating that Type was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Type(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Type fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Type enumValue : Type.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static Feature fromJson(String json) {
    return fromJson(JsonUtil.parse(json));
  }

  public static Feature fromJson(java.util.Map<String, Object> map) {
    return fromJson(JsonUtil.toJson(map));
  }

  public static Feature fromJson(JsonObject jsonObj) {
    Feature obj = new Feature();

    java.util.Set<String> knownFields = new java.util.HashSet<>();

    knownFields.add("id");

    knownFields.add("name");

    knownFields.add("description");

    knownFields.add("status");

    knownFields.add("type");

    knownFields.add("unit");

    knownFields.add("resource_version");

    knownFields.add("updated_at");

    knownFields.add("created_at");

    knownFields.add("metered");

    knownFields.add("levels");

    obj.id = JsonUtil.getString(jsonObj, "id");

    obj.name = JsonUtil.getString(jsonObj, "name");

    obj.description = JsonUtil.getString(jsonObj, "description");

    obj.status = Status.fromString(JsonUtil.getString(jsonObj, "status"));

    obj.type = Type.fromString(JsonUtil.getString(jsonObj, "type"));

    obj.unit = JsonUtil.getString(jsonObj, "unit");

    obj.resourceVersion = JsonUtil.getLong(jsonObj, "resource_version");

    obj.updatedAt = JsonUtil.getTimestamp(jsonObj, "updated_at");

    obj.createdAt = JsonUtil.getTimestamp(jsonObj, "created_at");

    obj.metered = JsonUtil.getBoolean(jsonObj, "metered");

    obj.levels = JsonUtil.mapArray(JsonUtil.getJsonArray(jsonObj, "levels"), Levels::fromJson);

    obj.customFields = JsonUtil.extractCustomFields(jsonObj, knownFields);

    return obj;
  }

  @Override
  public String toString() {
    return "Feature{"
        + "id="
        + id
        + ", name="
        + name
        + ", description="
        + description
        + ", status="
        + status
        + ", type="
        + type
        + ", unit="
        + unit
        + ", resourceVersion="
        + resourceVersion
        + ", updatedAt="
        + updatedAt
        + ", createdAt="
        + createdAt
        + ", metered="
        + metered
        + ", levels="
        + levels
        + ", customFields="
        + customFields
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    Feature that = (Feature) o;
    return java.util.Objects.equals(id, that.id)
        && java.util.Objects.equals(name, that.name)
        && java.util.Objects.equals(description, that.description)
        && java.util.Objects.equals(status, that.status)
        && java.util.Objects.equals(type, that.type)
        && java.util.Objects.equals(unit, that.unit)
        && java.util.Objects.equals(resourceVersion, that.resourceVersion)
        && java.util.Objects.equals(updatedAt, that.updatedAt)
        && java.util.Objects.equals(createdAt, that.createdAt)
        && java.util.Objects.equals(metered, that.metered)
        && java.util.Objects.equals(levels, that.levels)
        && java.util.Objects.equals(customFields, that.customFields);
  }

  @Override
  public int hashCode() {

    return java.util.Objects.hash(
        id,
        name,
        description,
        status,
        type,
        unit,
        resourceVersion,
        updatedAt,
        createdAt,
        metered,
        levels,
        customFields);
  }

  public static class Levels {

    private String name;
    private String value;
    private Integer level;
    private Boolean isUnlimited;

    public String getName() {
      return name;
    }

    public String getValue() {
      return value;
    }

    public Integer getLevel() {
      return level;
    }

    public Boolean getIsUnlimited() {
      return isUnlimited;
    }

    public static Levels fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static Levels fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static Levels fromJson(JsonObject jsonObj) {
      Levels obj = new Levels();

      obj.name = JsonUtil.getString(jsonObj, "name");

      obj.value = JsonUtil.getString(jsonObj, "value");

      obj.level = JsonUtil.getInteger(jsonObj, "level");

      obj.isUnlimited = JsonUtil.getBoolean(jsonObj, "is_unlimited");

      return obj;
    }

    @Override
    public String toString() {
      return "Levels{"
          + "name="
          + name
          + ", value="
          + value
          + ", level="
          + level
          + ", isUnlimited="
          + isUnlimited
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      Levels that = (Levels) o;
      return java.util.Objects.equals(name, that.name)
          && java.util.Objects.equals(value, that.value)
          && java.util.Objects.equals(level, that.level)
          && java.util.Objects.equals(isUnlimited, that.isUnlimited);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(name, value, level, isUnlimited);
    }
  }
}
