/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.models.inAppSubscription.params;

import com.chargebee.v4.internal.Recommended;

import java.util.LinkedHashMap;
import java.util.Map;

public final class InAppSubscriptionImportReceiptParams {

  private final String receipt;

  private final ProductParams product;

  private final CustomerParams customer;

  private InAppSubscriptionImportReceiptParams(InAppSubscriptionImportReceiptBuilder builder) {

    this.receipt = builder.receipt;

    this.product = builder.product;

    this.customer = builder.customer;
  }

  public String getReceipt() {
    return receipt;
  }

  public ProductParams getProduct() {
    return product;
  }

  public CustomerParams getCustomer() {
    return customer;
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    Map<String, Object> formData = new LinkedHashMap<>();

    if (this.receipt != null) {

      formData.put("receipt", this.receipt);
    }

    if (this.product != null) {

      // Single object
      Map<String, Object> nestedData = this.product.toFormData();
      for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
        String nestedKey = "product[" + entry.getKey() + "]";
        formData.put(nestedKey, entry.getValue());
      }
    }

    if (this.customer != null) {

      // Single object
      Map<String, Object> nestedData = this.customer.toFormData();
      for (Map.Entry<String, Object> entry : nestedData.entrySet()) {
        String nestedKey = "customer[" + entry.getKey() + "]";
        formData.put(nestedKey, entry.getValue());
      }
    }

    return formData;
  }

  /** Create a new builder for InAppSubscriptionImportReceiptParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static InAppSubscriptionImportReceiptBuilder builder() {
    return new InAppSubscriptionImportReceiptBuilder();
  }

  public static final class InAppSubscriptionImportReceiptBuilder {

    private String receipt;

    private ProductParams product;

    private CustomerParams customer;

    private InAppSubscriptionImportReceiptBuilder() {}

    public InAppSubscriptionImportReceiptBuilder receipt(String value) {
      this.receipt = value;
      return this;
    }

    public InAppSubscriptionImportReceiptBuilder product(ProductParams value) {
      this.product = value;
      return this;
    }

    public InAppSubscriptionImportReceiptBuilder customer(CustomerParams value) {
      this.customer = value;
      return this;
    }

    public InAppSubscriptionImportReceiptParams build() {
      return new InAppSubscriptionImportReceiptParams(this);
    }
  }

  public static final class ProductParams {

    private final String currencyCode;

    private ProductParams(ProductBuilder builder) {

      this.currencyCode = builder.currencyCode;
    }

    public String getCurrencyCode() {
      return currencyCode;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.currencyCode != null) {

        formData.put("currency_code", this.currencyCode);
      }

      return formData;
    }

    /** Create a new builder for ProductParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static ProductBuilder builder() {
      return new ProductBuilder();
    }

    public static final class ProductBuilder {

      private String currencyCode;

      private ProductBuilder() {}

      public ProductBuilder currencyCode(String value) {
        this.currencyCode = value;
        return this;
      }

      public ProductParams build() {
        return new ProductParams(this);
      }
    }
  }

  public static final class CustomerParams {

    private final String id;

    private final String email;

    private CustomerParams(CustomerBuilder builder) {

      this.id = builder.id;

      this.email = builder.email;
    }

    public String getId() {
      return id;
    }

    public String getEmail() {
      return email;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.id != null) {

        formData.put("id", this.id);
      }

      if (this.email != null) {

        formData.put("email", this.email);
      }

      return formData;
    }

    /** Create a new builder for CustomerParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static CustomerBuilder builder() {
      return new CustomerBuilder();
    }

    public static final class CustomerBuilder {

      private String id;

      private String email;

      private CustomerBuilder() {}

      public CustomerBuilder id(String value) {
        this.id = value;
        return this;
      }

      public CustomerBuilder email(String value) {
        this.email = value;
        return this;
      }

      public CustomerParams build() {
        return new CustomerParams(this);
      }
    }
  }
}
