/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.core.models.addon.params;

import com.chargebee.v4.internal.Recommended;

import java.sql.Timestamp;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class AddonListParams {

  private final Map<String, Object> queryParams;

  private AddonListParams(AddonListBuilder builder) {
    this.queryParams = Collections.unmodifiableMap(new LinkedHashMap<>(builder.queryParams));
  }

  /** Get the query parameters for this request. */
  public Map<String, Object> toQueryParams() {
    return queryParams;
  }

  public AddonListBuilder toBuilder() {
    AddonListBuilder builder = new AddonListBuilder();
    builder.queryParams.putAll(queryParams);
    return builder;
  }

  /** Create a new builder for AddonListParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static AddonListBuilder builder() {
    return new AddonListBuilder();
  }

  public static final class AddonListBuilder {
    private final Map<String, Object> queryParams = new LinkedHashMap<>();

    private AddonListBuilder() {}

    public AddonListBuilder limit(Integer value) {
      queryParams.put("limit", value);
      return this;
    }

    public AddonListBuilder offset(String value) {
      queryParams.put("offset", value);
      return this;
    }

    public IdFilter id() {
      return new IdFilter("id", this);
    }

    public NameFilter name() {
      return new NameFilter("name", this);
    }

    public PricingModelFilter pricingModel() {
      return new PricingModelFilter("pricing_model", this);
    }

    @Deprecated
    public TypeFilter type() {
      return new TypeFilter("type", this);
    }

    public ChargeTypeFilter chargeType() {
      return new ChargeTypeFilter("charge_type", this);
    }

    public PriceFilter price() {
      return new PriceFilter("price", this);
    }

    public PeriodFilter period() {
      return new PeriodFilter("period", this);
    }

    public PeriodUnitFilter periodUnit() {
      return new PeriodUnitFilter("period_unit", this);
    }

    public StatusFilter status() {
      return new StatusFilter("status", this);
    }

    public UpdatedAtFilter updatedAt() {
      return new UpdatedAtFilter("updated_at", this);
    }

    public CurrencyCodeFilter currencyCode() {
      return new CurrencyCodeFilter("currency_code", this);
    }

    public ChannelFilter channel() {
      return new ChannelFilter("channel", this);
    }

    public AddonListBuilder includeDeleted(Boolean value) {
      queryParams.put("include_deleted", value);
      return this;
    }

    public AddonListParams build() {
      return new AddonListParams(this);
    }

    public static final class IdFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      IdFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder startsWith(String value) {
        builder.queryParams.put(fieldName + "[starts_with]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class NameFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      NameFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder startsWith(String value) {
        builder.queryParams.put(fieldName + "[starts_with]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class PricingModelFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      PricingModelFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class TypeFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      TypeFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class ChargeTypeFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      ChargeTypeFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class PriceFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      PriceFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder between(Timestamp start, Timestamp end) {
        builder.queryParams.put(
            fieldName + "[between]",
            "[" + (start.getTime() / 1000) + "," + (end.getTime() / 1000) + "]");
        return builder;
      }
    }

    public static final class PeriodFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      PeriodFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder between(Timestamp start, Timestamp end) {
        builder.queryParams.put(
            fieldName + "[between]",
            "[" + (start.getTime() / 1000) + "," + (end.getTime() / 1000) + "]");
        return builder;
      }
    }

    public static final class PeriodUnitFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      PeriodUnitFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class StatusFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      StatusFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class UpdatedAtFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      UpdatedAtFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder after(Timestamp timestamp) {
        builder.queryParams.put(fieldName + "[after]", timestamp.getTime() / 1000);
        return builder;
      }

      public AddonListBuilder before(Timestamp timestamp) {
        builder.queryParams.put(fieldName + "[before]", timestamp.getTime() / 1000);
        return builder;
      }

      public AddonListBuilder on(Timestamp timestamp) {
        builder.queryParams.put(fieldName + "[on]", timestamp.getTime() / 1000);
        return builder;
      }

      public AddonListBuilder between(Timestamp start, Timestamp end) {
        builder.queryParams.put(
            fieldName + "[between]",
            "[" + (start.getTime() / 1000) + "," + (end.getTime() / 1000) + "]");
        return builder;
      }
    }

    public static final class CurrencyCodeFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      CurrencyCodeFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder startsWith(String value) {
        builder.queryParams.put(fieldName + "[starts_with]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public static final class ChannelFilter {
      private final String fieldName;
      private final AddonListBuilder builder;

      ChannelFilter(String fieldName, AddonListBuilder builder) {
        this.fieldName = fieldName;
        this.builder = builder;
      }

      public AddonListBuilder is(String value) {
        builder.queryParams.put(fieldName + "[is]", value);
        return builder;
      }

      public AddonListBuilder isNot(String value) {
        builder.queryParams.put(fieldName + "[is_not]", value);
        return builder;
      }

      public AddonListBuilder in(String... values) {
        builder.queryParams.put(fieldName + "[in]", "[" + String.join(",", values) + "]");
        return builder;
      }

      public AddonListBuilder notIn(String... values) {
        builder.queryParams.put(fieldName + "[not_in]", "[" + String.join(",", values) + "]");
        return builder;
      }
    }

    public enum PricingModelIs {
      FLAT_FEE("flat_fee"),

      PER_UNIT("per_unit"),

      TIERED("tiered"),

      VOLUME("volume"),

      STAIRSTEP("stairstep"),

      /** An enum member indicating that PricingModelIs was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      PricingModelIs(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PricingModelIs fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PricingModelIs enumValue : PricingModelIs.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum PricingModelIsNot {
      FLAT_FEE("flat_fee"),

      PER_UNIT("per_unit"),

      TIERED("tiered"),

      VOLUME("volume"),

      STAIRSTEP("stairstep"),

      /**
       * An enum member indicating that PricingModelIsNot was instantiated with an unknown value.
       */
      _UNKNOWN(null);
      private final String value;

      PricingModelIsNot(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PricingModelIsNot fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PricingModelIsNot enumValue : PricingModelIsNot.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum TypeIs {
      ON_OFF("on_off"),

      QUANTITY("quantity"),

      TIERED("tiered"),

      VOLUME("volume"),

      STAIRSTEP("stairstep"),

      /** An enum member indicating that TypeIs was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      TypeIs(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static TypeIs fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (TypeIs enumValue : TypeIs.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum TypeIsNot {
      ON_OFF("on_off"),

      QUANTITY("quantity"),

      TIERED("tiered"),

      VOLUME("volume"),

      STAIRSTEP("stairstep"),

      /** An enum member indicating that TypeIsNot was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      TypeIsNot(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static TypeIsNot fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (TypeIsNot enumValue : TypeIsNot.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum ChargeTypeIs {
      RECURRING("recurring"),

      NON_RECURRING("non_recurring"),

      /** An enum member indicating that ChargeTypeIs was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ChargeTypeIs(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ChargeTypeIs fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ChargeTypeIs enumValue : ChargeTypeIs.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum ChargeTypeIsNot {
      RECURRING("recurring"),

      NON_RECURRING("non_recurring"),

      /** An enum member indicating that ChargeTypeIsNot was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ChargeTypeIsNot(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ChargeTypeIsNot fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ChargeTypeIsNot enumValue : ChargeTypeIsNot.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum PeriodUnitIs {
      DAY("day"),

      WEEK("week"),

      MONTH("month"),

      YEAR("year"),

      NOT_APPLICABLE("not_applicable"),

      /** An enum member indicating that PeriodUnitIs was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      PeriodUnitIs(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PeriodUnitIs fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PeriodUnitIs enumValue : PeriodUnitIs.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum PeriodUnitIsNot {
      DAY("day"),

      WEEK("week"),

      MONTH("month"),

      YEAR("year"),

      NOT_APPLICABLE("not_applicable"),

      /** An enum member indicating that PeriodUnitIsNot was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      PeriodUnitIsNot(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PeriodUnitIsNot fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PeriodUnitIsNot enumValue : PeriodUnitIsNot.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum StatusIs {
      ACTIVE("active"),

      ARCHIVED("archived"),

      DELETED("deleted"),

      /** An enum member indicating that StatusIs was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      StatusIs(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static StatusIs fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (StatusIs enumValue : StatusIs.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum StatusIsNot {
      ACTIVE("active"),

      ARCHIVED("archived"),

      DELETED("deleted"),

      /** An enum member indicating that StatusIsNot was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      StatusIsNot(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static StatusIsNot fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (StatusIsNot enumValue : StatusIsNot.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum ChannelIs {
      WEB("web"),

      APP_STORE("app_store"),

      PLAY_STORE("play_store"),

      /** An enum member indicating that ChannelIs was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ChannelIs(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ChannelIs fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ChannelIs enumValue : ChannelIs.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum ChannelIsNot {
      WEB("web"),

      APP_STORE("app_store"),

      PLAY_STORE("play_store"),

      /** An enum member indicating that ChannelIsNot was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ChannelIsNot(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ChannelIsNot fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ChannelIsNot enumValue : ChannelIsNot.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }
}
