/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.core.services;

import com.chargebee.v4.client.ChargebeeClient;
import com.chargebee.v4.client.request.RequestOptions;
import com.chargebee.v4.transport.Response;

import com.chargebee.v4.core.models.subscriptionEntitlement.params.SubscriptionEntitlementSetSubscriptionEntitlementAvailabilityParams;

import com.chargebee.v4.core.models.subscriptionEntitlement.params.SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionParams;

import com.chargebee.v4.core.responses.subscriptionEntitlement.SubscriptionEntitlementSetSubscriptionEntitlementAvailabilityResponse;

import com.chargebee.v4.core.responses.subscriptionEntitlement.SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionResponse;

public final class SubscriptionEntitlementService
    extends BaseService<SubscriptionEntitlementService> {

  private final ServiceConfig config;

  public SubscriptionEntitlementService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private SubscriptionEntitlementService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private SubscriptionEntitlementService(
      ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  SubscriptionEntitlementService with(RequestOptions newOptions) {
    return new SubscriptionEntitlementService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public SubscriptionEntitlementService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /**
   * setSubscriptionEntitlementAvailability a subscriptionEntitlement (executes immediately) -
   * returns raw Response.
   */
  Response setSubscriptionEntitlementAvailabilityRaw(String subscriptionId) throws Exception {
    String path =
        buildPathWithParams(
            "/subscriptions/{subscription-id}/subscription_entitlements/set_availability",
            "subscription-id",
            subscriptionId);

    return post(path, null);
  }

  /**
   * setSubscriptionEntitlementAvailability a subscriptionEntitlement using immutable params
   * (executes immediately) - returns raw Response.
   */
  Response setSubscriptionEntitlementAvailabilityRaw(
      String subscriptionId,
      SubscriptionEntitlementSetSubscriptionEntitlementAvailabilityParams params)
      throws Exception {
    String path =
        buildPathWithParams(
            "/subscriptions/{subscription-id}/subscription_entitlements/set_availability",
            "subscription-id",
            subscriptionId);
    return post(path, params.toFormData());
  }

  /**
   * setSubscriptionEntitlementAvailability a subscriptionEntitlement using raw JSON payload
   * (executes immediately) - returns raw Response.
   */
  Response setSubscriptionEntitlementAvailabilityRaw(String subscriptionId, String jsonPayload)
      throws Exception {
    String path =
        buildPathWithParams(
            "/subscriptions/{subscription-id}/subscription_entitlements/set_availability",
            "subscription-id",
            subscriptionId);
    return postJson(path, jsonPayload);
  }

  public SubscriptionEntitlementSetSubscriptionEntitlementAvailabilityResponse
      setSubscriptionEntitlementAvailability(
          String subscriptionId,
          SubscriptionEntitlementSetSubscriptionEntitlementAvailabilityParams params)
          throws Exception {
    Response response = setSubscriptionEntitlementAvailabilityRaw(subscriptionId, params);
    return SubscriptionEntitlementSetSubscriptionEntitlementAvailabilityResponse.fromJson(
        response.getBodyAsString(), response);
  }

  /**
   * subscriptionEntitlementsForSubscription a subscriptionEntitlement using immutable params
   * (executes immediately) - returns raw Response.
   */
  Response subscriptionEntitlementsForSubscriptionRaw(
      String subscriptionId,
      SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionParams params)
      throws Exception {
    String path =
        buildPathWithParams(
            "/subscriptions/{subscription-id}/subscription_entitlements",
            "subscription-id",
            subscriptionId);
    return get(path, params != null ? params.toQueryParams() : null);
  }

  /**
   * subscriptionEntitlementsForSubscription a subscriptionEntitlement without params (executes
   * immediately) - returns raw Response.
   */
  Response subscriptionEntitlementsForSubscriptionRaw(String subscriptionId) throws Exception {
    String path =
        buildPathWithParams(
            "/subscriptions/{subscription-id}/subscription_entitlements",
            "subscription-id",
            subscriptionId);
    return get(path, null);
  }

  /**
   * subscriptionEntitlementsForSubscription a subscriptionEntitlement using raw JSON payload
   * (executes immediately) - returns raw Response.
   */
  Response subscriptionEntitlementsForSubscriptionRaw(String subscriptionId, String jsonPayload)
      throws Exception {
    String path =
        buildPathWithParams(
            "/subscriptions/{subscription-id}/subscription_entitlements",
            "subscription-id",
            subscriptionId);
    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionResponse
      subscriptionEntitlementsForSubscription(
          String subscriptionId,
          SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionParams params)
          throws Exception {
    Response response = subscriptionEntitlementsForSubscriptionRaw(subscriptionId, params);
    return SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionResponse.fromJson(
        response.getBodyAsString(), this, params, subscriptionId, response);
  }

  public SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionResponse
      subscriptionEntitlementsForSubscription(String subscriptionId) throws Exception {
    Response response = subscriptionEntitlementsForSubscriptionRaw(subscriptionId);
    return SubscriptionEntitlementSubscriptionEntitlementsForSubscriptionResponse.fromJson(
        response.getBodyAsString(), this, null, subscriptionId, response);
  }
}
