/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.core.models.subscriptionEntitlementsCreatedDetail;

import com.chargebee.v4.internal.JsonUtil;

public class SubscriptionEntitlementsCreatedDetail {

  private String subscriptionId;
  private Boolean hasNext;

  public String getSubscriptionId() {
    return subscriptionId;
  }

  public Boolean getHasNext() {
    return hasNext;
  }

  public static SubscriptionEntitlementsCreatedDetail fromJson(String json) {
    SubscriptionEntitlementsCreatedDetail obj = new SubscriptionEntitlementsCreatedDetail();

    obj.subscriptionId = JsonUtil.getString(json, "subscription_id");

    obj.hasNext = JsonUtil.getBoolean(json, "has_next");

    return obj;
  }
}
