/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.core.models.promotionalCredit.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class PromotionalCreditAddParams {

  private final Map<String, Object> formData;

  private PromotionalCreditAddParams(PromotionalCreditAddBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for PromotionalCreditAddParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static PromotionalCreditAddBuilder builder() {
    return new PromotionalCreditAddBuilder();
  }

  public static final class PromotionalCreditAddBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private PromotionalCreditAddBuilder() {}

    public PromotionalCreditAddBuilder customerId(String value) {

      formData.put("customer_id", value);

      return this;
    }

    public PromotionalCreditAddBuilder amount(Long value) {

      formData.put("amount", value);

      return this;
    }

    public PromotionalCreditAddBuilder amountInDecimal(String value) {

      formData.put("amount_in_decimal", value);

      return this;
    }

    public PromotionalCreditAddBuilder currencyCode(String value) {

      formData.put("currency_code", value);

      return this;
    }

    public PromotionalCreditAddBuilder description(String value) {

      formData.put("description", value);

      return this;
    }

    public PromotionalCreditAddBuilder creditType(CreditType value) {

      formData.put("credit_type", value);

      return this;
    }

    public PromotionalCreditAddBuilder reference(String value) {

      formData.put("reference", value);

      return this;
    }

    public PromotionalCreditAddParams build() {
      return new PromotionalCreditAddParams(this);
    }

    public enum CreditType {
      LoyaltyCredits("loyalty_credits"),

      ReferralRewards("referral_rewards"),

      General("general"),

      /** An enum member indicating that CreditType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      CreditType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static CreditType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (CreditType enumValue : CreditType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }
}
