/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.billingConfiguration;

import com.chargebee.v4.internal.JsonUtil;
import java.sql.Timestamp;
import java.util.List;

public class BillingConfiguration {

  private Boolean isCalendarBillingEnabled;
  private List<BillingDates> billingDates;

  public Boolean getIsCalendarBillingEnabled() {
    return isCalendarBillingEnabled;
  }

  public List<BillingDates> getBillingDates() {
    return billingDates;
  }

  public static BillingConfiguration fromJson(String json) {
    BillingConfiguration obj = new BillingConfiguration();

    obj.isCalendarBillingEnabled = JsonUtil.getBoolean(json, "is_calendar_billing_enabled");

    obj.billingDates =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "billing_dates")).stream()
            .map(BillingDates::fromJson)
            .collect(java.util.stream.Collectors.toList());

    return obj;
  }

  public static class BillingDates {

    private Timestamp startDate;
    private Timestamp endDate;

    public Timestamp getStartDate() {
      return startDate;
    }

    public Timestamp getEndDate() {
      return endDate;
    }

    public static BillingDates fromJson(String json) {
      BillingDates obj = new BillingDates();

      obj.startDate = JsonUtil.getTimestamp(json, "start_date");

      obj.endDate = JsonUtil.getTimestamp(json, "end_date");

      return obj;
    }
  }
}
