/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.models.entitlement.params;

import com.chargebee.v4.internal.Recommended;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.List;

public final class EntitlementCreateParams {

  private final Action action;

  private final String changeReason;

  private final List<EntitlementsParams> entitlements;

  private EntitlementCreateParams(EntitlementCreateBuilder builder) {

    this.action = builder.action;

    this.changeReason = builder.changeReason;

    this.entitlements = builder.entitlements;
  }

  public Action getAction() {
    return action;
  }

  public String getChangeReason() {
    return changeReason;
  }

  public List<EntitlementsParams> getEntitlements() {
    return entitlements;
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    Map<String, Object> formData = new LinkedHashMap<>();

    if (this.action != null) {

      formData.put("action", this.action);
    }

    if (this.changeReason != null) {

      formData.put("change_reason", this.changeReason);
    }

    if (this.entitlements != null) {

      // List of objects
      for (int i = 0; i < this.entitlements.size(); i++) {
        EntitlementsParams item = this.entitlements.get(i);
        if (item != null) {
          Map<String, Object> itemData = item.toFormData();
          for (Map.Entry<String, Object> entry : itemData.entrySet()) {
            String indexedKey = "entitlements[" + entry.getKey() + "][" + i + "]";
            formData.put(indexedKey, entry.getValue());
          }
        }
      }
    }

    return formData;
  }

  /** Create a new builder for EntitlementCreateParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static EntitlementCreateBuilder builder() {
    return new EntitlementCreateBuilder();
  }

  public static final class EntitlementCreateBuilder {

    private Action action;

    private String changeReason;

    private List<EntitlementsParams> entitlements;

    private EntitlementCreateBuilder() {}

    public EntitlementCreateBuilder action(Action value) {
      this.action = value;
      return this;
    }

    public EntitlementCreateBuilder changeReason(String value) {
      this.changeReason = value;
      return this;
    }

    public EntitlementCreateBuilder entitlements(List<EntitlementsParams> value) {
      this.entitlements = value;
      return this;
    }

    public EntitlementCreateParams build() {
      return new EntitlementCreateParams(this);
    }
  }

  public enum Action {
    UPSERT("upsert"),

    REMOVE("remove"),

    /** An enum member indicating that Action was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Action(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Action fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Action enumValue : Action.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static final class EntitlementsParams {

    private final String entityId;

    private final String featureId;

    private final EntityType entityType;

    private final String value;

    private final Boolean applyGrandfathering;

    private EntitlementsParams(EntitlementsBuilder builder) {

      this.entityId = builder.entityId;

      this.featureId = builder.featureId;

      this.entityType = builder.entityType;

      this.value = builder.value;

      this.applyGrandfathering = builder.applyGrandfathering;
    }

    public String getEntityId() {
      return entityId;
    }

    public String getFeatureId() {
      return featureId;
    }

    public EntityType getEntityType() {
      return entityType;
    }

    public String getValue() {
      return value;
    }

    public Boolean getApplyGrandfathering() {
      return applyGrandfathering;
    }

    /** Get the form data for this request. */
    public Map<String, Object> toFormData() {
      Map<String, Object> formData = new LinkedHashMap<>();

      if (this.entityId != null) {

        formData.put("entity_id", this.entityId);
      }

      if (this.featureId != null) {

        formData.put("feature_id", this.featureId);
      }

      if (this.entityType != null) {

        formData.put("entity_type", this.entityType);
      }

      if (this.value != null) {

        formData.put("value", this.value);
      }

      if (this.applyGrandfathering != null) {

        formData.put("apply_grandfathering", this.applyGrandfathering);
      }

      return formData;
    }

    /** Create a new builder for EntitlementsParams. */
    @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
    public static EntitlementsBuilder builder() {
      return new EntitlementsBuilder();
    }

    public static final class EntitlementsBuilder {

      private String entityId;

      private String featureId;

      private EntityType entityType;

      private String value;

      private Boolean applyGrandfathering;

      private EntitlementsBuilder() {}

      public EntitlementsBuilder entityId(String value) {
        this.entityId = value;
        return this;
      }

      public EntitlementsBuilder featureId(String value) {
        this.featureId = value;
        return this;
      }

      public EntitlementsBuilder entityType(EntityType value) {
        this.entityType = value;
        return this;
      }

      public EntitlementsBuilder value(String value) {
        this.value = value;
        return this;
      }

      public EntitlementsBuilder applyGrandfathering(Boolean value) {
        this.applyGrandfathering = value;
        return this;
      }

      public EntitlementsParams build() {
        return new EntitlementsParams(this);
      }
    }

    public enum EntityType {
      PLAN("plan"),

      ADDON("addon"),

      CHARGE("charge"),

      PLAN_PRICE("plan_price"),

      ADDON_PRICE("addon_price"),

      /** An enum member indicating that EntityType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      EntityType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static EntityType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (EntityType enumValue : EntityType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }
}
