/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.core.models.invoice.params;

import com.chargebee.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class InvoiceInvoicesForSubscriptionParams {

  private final Map<String, Object> queryParams;

  private InvoiceInvoicesForSubscriptionParams(InvoiceInvoicesForSubscriptionBuilder builder) {
    this.queryParams = Collections.unmodifiableMap(new LinkedHashMap<>(builder.queryParams));
  }

  /** Get the query parameters for this request. */
  public Map<String, Object> toQueryParams() {
    return queryParams;
  }

  public InvoiceInvoicesForSubscriptionBuilder toBuilder() {
    InvoiceInvoicesForSubscriptionBuilder builder = new InvoiceInvoicesForSubscriptionBuilder();
    builder.queryParams.putAll(queryParams);
    return builder;
  }

  /** Create a new builder for InvoiceInvoicesForSubscriptionParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static InvoiceInvoicesForSubscriptionBuilder builder() {
    return new InvoiceInvoicesForSubscriptionBuilder();
  }

  public static final class InvoiceInvoicesForSubscriptionBuilder {
    private final Map<String, Object> queryParams = new LinkedHashMap<>();

    private InvoiceInvoicesForSubscriptionBuilder() {}

    public InvoiceInvoicesForSubscriptionBuilder limit(Integer value) {
      queryParams.put("limit", value);
      return this;
    }

    public InvoiceInvoicesForSubscriptionBuilder offset(String value) {
      queryParams.put("offset", value);
      return this;
    }

    public InvoiceInvoicesForSubscriptionParams build() {
      return new InvoiceInvoicesForSubscriptionParams(this);
    }

    // Field-specific filter classes for fluent API

    // Sort builder classes for fluent API

  }
}
