/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.services;

import com.chargebee.v4.client.ChargebeeClient;
import com.chargebee.v4.client.request.RequestOptions;
import com.chargebee.v4.exceptions.ChargebeeException;
import com.chargebee.v4.transport.Response;

import com.chargebee.v4.models.brandConfiguration.params.BrandConfigurationRetrieveParams;

import com.chargebee.v4.models.brandConfiguration.responses.BrandConfigurationRetrieveResponse;

public final class BrandConfigurationService extends BaseService<BrandConfigurationService> {

  private final ServiceConfig config;

  public BrandConfigurationService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private BrandConfigurationService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private BrandConfigurationService(
      ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  BrandConfigurationService with(RequestOptions newOptions) {
    return new BrandConfigurationService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public BrandConfigurationService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /**
   * retrieve a brandConfiguration using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response retrieveRaw(BrandConfigurationRetrieveParams params) throws ChargebeeException {

    return get("/brand_configurations", params != null ? params.toQueryParams() : null);
  }

  /**
   * retrieve a brandConfiguration using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response retrieveRaw(String jsonPayload) throws ChargebeeException {

    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public BrandConfigurationRetrieveResponse retrieve(BrandConfigurationRetrieveParams params)
      throws ChargebeeException {
    Response response = retrieveRaw(params);

    return BrandConfigurationRetrieveResponse.fromJson(response.getBodyAsString(), response);
  }
}
