/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.services;

import com.chargebee.v4.client.ChargebeeClient;
import com.chargebee.v4.client.request.RequestOptions;
import com.chargebee.v4.transport.Response;

import com.chargebee.v4.models.businessProfile.params.BusinessProfileExecuteParams;

import com.chargebee.v4.models.businessProfile.responses.BusinessProfileExecuteResponse;

public final class BusinessProfileService extends BaseService<BusinessProfileService> {

  private final ServiceConfig config;

  public BusinessProfileService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private BusinessProfileService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private BusinessProfileService(
      ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  BusinessProfileService with(RequestOptions newOptions) {
    return new BusinessProfileService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public BusinessProfileService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /**
   * execute a businessProfile using immutable params (executes immediately) - returns raw Response.
   */
  Response executeRaw(BusinessProfileExecuteParams params) throws Exception {

    return get("/business_profiles", params != null ? params.toQueryParams() : null);
  }

  /**
   * execute a businessProfile using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response executeRaw(String jsonPayload) throws Exception {

    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public BusinessProfileExecuteResponse execute(BusinessProfileExecuteParams params)
      throws Exception {
    Response response = executeRaw(params);

    return BusinessProfileExecuteResponse.fromJson(response.getBodyAsString(), response);
  }
}
