/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.services;

import com.chargebee.v4.client.ChargebeeClient;
import com.chargebee.v4.client.request.RequestOptions;
import com.chargebee.v4.exceptions.ChargebeeException;
import com.chargebee.v4.transport.Response;
import java.util.concurrent.CompletableFuture;

import com.chargebee.v4.models.coupon.params.CouponListParams;

import com.chargebee.v4.models.coupon.params.CouponCreateParams;

import com.chargebee.v4.models.coupon.params.CouponUpdateForItemsParams;

import com.chargebee.v4.models.coupon.params.CouponCopyParams;

import com.chargebee.v4.models.coupon.params.CouponUpdateParams;

import com.chargebee.v4.models.coupon.params.CouponCreateForItemsParams;

import com.chargebee.v4.models.coupon.responses.CouponListResponse;

import com.chargebee.v4.models.coupon.responses.CouponCreateResponse;

import com.chargebee.v4.models.coupon.responses.CouponUpdateForItemsResponse;

import com.chargebee.v4.models.coupon.responses.CouponUnarchiveResponse;

import com.chargebee.v4.models.coupon.responses.CouponDeleteResponse;

import com.chargebee.v4.models.coupon.responses.CouponCopyResponse;

import com.chargebee.v4.models.coupon.responses.CouponRetrieveResponse;

import com.chargebee.v4.models.coupon.responses.CouponUpdateResponse;

import com.chargebee.v4.models.coupon.responses.CouponCreateForItemsResponse;

public final class CouponService extends BaseService<CouponService> {

  private final ServiceConfig config;

  public CouponService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private CouponService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private CouponService(ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  CouponService with(RequestOptions newOptions) {
    return new CouponService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public CouponService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /** list a coupon using immutable params (executes immediately) - returns raw Response. */
  Response listRaw(CouponListParams params) throws ChargebeeException {

    return get("coupon", "list", "/coupons", params != null ? params.toQueryParams() : null);
  }

  /** list a coupon without params (executes immediately) - returns raw Response. */
  Response listRaw() throws ChargebeeException {

    return get("coupon", "list", "/coupons", null);
  }

  /** list a coupon using raw JSON payload (executes immediately) - returns raw Response. */
  Response listRaw(String jsonPayload) throws ChargebeeException {

    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public CouponListResponse list(CouponListParams params) throws ChargebeeException {
    Response response = listRaw(params);

    return CouponListResponse.fromJson(response.getBodyAsString(), this, params, response);
  }

  /** Async variant of list for coupon with params. */
  public CompletableFuture<CouponListResponse> listAsync(CouponListParams params) {

    return getAsync("coupon", "list", "/coupons", params != null ? params.toQueryParams() : null)
        .thenApply(
            response ->
                CouponListResponse.fromJson(response.getBodyAsString(), this, params, response));
  }

  public CouponListResponse list() throws ChargebeeException {
    Response response = listRaw();

    return CouponListResponse.fromJson(response.getBodyAsString(), this, null, response);
  }

  /** Async variant of list for coupon without params. */
  public CompletableFuture<CouponListResponse> listAsync() {

    return getAsync("coupon", "list", "/coupons", null)
        .thenApply(
            response ->
                CouponListResponse.fromJson(response.getBodyAsString(), this, null, response));
  }

  /** create a coupon using immutable params (executes immediately) - returns raw Response. */
  Response createRaw(CouponCreateParams params) throws ChargebeeException {

    return post("coupon", "create", "/coupons", params != null ? params.toFormData() : null);
  }

  /** create a coupon using raw JSON payload (executes immediately) - returns raw Response. */
  Response createRaw(String jsonPayload) throws ChargebeeException {

    return postJson("coupon", "create", "/coupons", jsonPayload);
  }

  public CouponCreateResponse create(CouponCreateParams params) throws ChargebeeException {
    Response response = createRaw(params);

    return CouponCreateResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of create for coupon with params. */
  public CompletableFuture<CouponCreateResponse> createAsync(CouponCreateParams params) {

    return postAsync("coupon", "create", "/coupons", params != null ? params.toFormData() : null)
        .thenApply(response -> CouponCreateResponse.fromJson(response.getBodyAsString(), response));
  }

  /** updateForItems a coupon (executes immediately) - returns raw Response. */
  Response updateForItemsRaw(String couponId) throws ChargebeeException {
    String path =
        buildPathWithParams("/coupons/{coupon-id}/update_for_items", "coupon-id", couponId);

    return post("coupon", "updateForItems", path, null);
  }

  /**
   * updateForItems a coupon using immutable params (executes immediately) - returns raw Response.
   */
  Response updateForItemsRaw(String couponId, CouponUpdateForItemsParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/coupons/{coupon-id}/update_for_items", "coupon-id", couponId);
    return post("coupon", "updateForItems", path, params.toFormData());
  }

  /**
   * updateForItems a coupon using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response updateForItemsRaw(String couponId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/coupons/{coupon-id}/update_for_items", "coupon-id", couponId);
    return postJson("coupon", "updateForItems", path, jsonPayload);
  }

  public CouponUpdateForItemsResponse updateForItems(
      String couponId, CouponUpdateForItemsParams params) throws ChargebeeException {
    Response response = updateForItemsRaw(couponId, params);
    return CouponUpdateForItemsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of updateForItems for coupon with params. */
  public CompletableFuture<CouponUpdateForItemsResponse> updateForItemsAsync(
      String couponId, CouponUpdateForItemsParams params) {
    String path =
        buildPathWithParams("/coupons/{coupon-id}/update_for_items", "coupon-id", couponId);
    return postAsync("coupon", "updateForItems", path, params.toFormData())
        .thenApply(
            response ->
                CouponUpdateForItemsResponse.fromJson(response.getBodyAsString(), response));
  }

  public CouponUpdateForItemsResponse updateForItems(String couponId) throws ChargebeeException {
    Response response = updateForItemsRaw(couponId);
    return CouponUpdateForItemsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of updateForItems for coupon without params. */
  public CompletableFuture<CouponUpdateForItemsResponse> updateForItemsAsync(String couponId) {
    String path =
        buildPathWithParams("/coupons/{coupon-id}/update_for_items", "coupon-id", couponId);

    return postAsync("coupon", "updateForItems", path, null)
        .thenApply(
            response ->
                CouponUpdateForItemsResponse.fromJson(response.getBodyAsString(), response));
  }

  /** unarchive a coupon (executes immediately) - returns raw Response. */
  Response unarchiveRaw(String couponId) throws ChargebeeException {
    String path = buildPathWithParams("/coupons/{coupon-id}/unarchive", "coupon-id", couponId);

    return post("coupon", "unarchive", path, null);
  }

  public CouponUnarchiveResponse unarchive(String couponId) throws ChargebeeException {
    Response response = unarchiveRaw(couponId);
    return CouponUnarchiveResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of unarchive for coupon without params. */
  public CompletableFuture<CouponUnarchiveResponse> unarchiveAsync(String couponId) {
    String path = buildPathWithParams("/coupons/{coupon-id}/unarchive", "coupon-id", couponId);

    return postAsync("coupon", "unarchive", path, null)
        .thenApply(
            response -> CouponUnarchiveResponse.fromJson(response.getBodyAsString(), response));
  }

  /** delete a coupon (executes immediately) - returns raw Response. */
  Response deleteRaw(String couponId) throws ChargebeeException {
    String path = buildPathWithParams("/coupons/{coupon-id}/delete", "coupon-id", couponId);

    return post("coupon", "delete", path, null);
  }

  public CouponDeleteResponse delete(String couponId) throws ChargebeeException {
    Response response = deleteRaw(couponId);
    return CouponDeleteResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of delete for coupon without params. */
  public CompletableFuture<CouponDeleteResponse> deleteAsync(String couponId) {
    String path = buildPathWithParams("/coupons/{coupon-id}/delete", "coupon-id", couponId);

    return postAsync("coupon", "delete", path, null)
        .thenApply(response -> CouponDeleteResponse.fromJson(response.getBodyAsString(), response));
  }

  /** copy a coupon using immutable params (executes immediately) - returns raw Response. */
  Response copyRaw(CouponCopyParams params) throws ChargebeeException {

    return post("coupon", "copy", "/coupons/copy", params != null ? params.toFormData() : null);
  }

  /** copy a coupon using raw JSON payload (executes immediately) - returns raw Response. */
  Response copyRaw(String jsonPayload) throws ChargebeeException {

    return postJson("coupon", "copy", "/coupons/copy", jsonPayload);
  }

  public CouponCopyResponse copy(CouponCopyParams params) throws ChargebeeException {
    Response response = copyRaw(params);

    return CouponCopyResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of copy for coupon with params. */
  public CompletableFuture<CouponCopyResponse> copyAsync(CouponCopyParams params) {

    return postAsync("coupon", "copy", "/coupons/copy", params != null ? params.toFormData() : null)
        .thenApply(response -> CouponCopyResponse.fromJson(response.getBodyAsString(), response));
  }

  /** retrieve a coupon (executes immediately) - returns raw Response. */
  Response retrieveRaw(String couponId) throws ChargebeeException {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);

    return get("coupon", "retrieve", path, null);
  }

  public CouponRetrieveResponse retrieve(String couponId) throws ChargebeeException {
    Response response = retrieveRaw(couponId);
    return CouponRetrieveResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of retrieve for coupon without params. */
  public CompletableFuture<CouponRetrieveResponse> retrieveAsync(String couponId) {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);

    return getAsync("coupon", "retrieve", path, null)
        .thenApply(
            response -> CouponRetrieveResponse.fromJson(response.getBodyAsString(), response));
  }

  /** update a coupon (executes immediately) - returns raw Response. */
  Response updateRaw(String couponId) throws ChargebeeException {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);

    return post("coupon", "update", path, null);
  }

  /** update a coupon using immutable params (executes immediately) - returns raw Response. */
  Response updateRaw(String couponId, CouponUpdateParams params) throws ChargebeeException {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);
    return post("coupon", "update", path, params.toFormData());
  }

  /** update a coupon using raw JSON payload (executes immediately) - returns raw Response. */
  Response updateRaw(String couponId, String jsonPayload) throws ChargebeeException {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);
    return postJson("coupon", "update", path, jsonPayload);
  }

  public CouponUpdateResponse update(String couponId, CouponUpdateParams params)
      throws ChargebeeException {
    Response response = updateRaw(couponId, params);
    return CouponUpdateResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of update for coupon with params. */
  public CompletableFuture<CouponUpdateResponse> updateAsync(
      String couponId, CouponUpdateParams params) {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);
    return postAsync("coupon", "update", path, params.toFormData())
        .thenApply(response -> CouponUpdateResponse.fromJson(response.getBodyAsString(), response));
  }

  public CouponUpdateResponse update(String couponId) throws ChargebeeException {
    Response response = updateRaw(couponId);
    return CouponUpdateResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of update for coupon without params. */
  public CompletableFuture<CouponUpdateResponse> updateAsync(String couponId) {
    String path = buildPathWithParams("/coupons/{coupon-id}", "coupon-id", couponId);

    return postAsync("coupon", "update", path, null)
        .thenApply(response -> CouponUpdateResponse.fromJson(response.getBodyAsString(), response));
  }

  /**
   * createForItems a coupon using immutable params (executes immediately) - returns raw Response.
   */
  Response createForItemsRaw(CouponCreateForItemsParams params) throws ChargebeeException {

    return post(
        "coupon",
        "createForItems",
        "/coupons/create_for_items",
        params != null ? params.toFormData() : null);
  }

  /**
   * createForItems a coupon using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response createForItemsRaw(String jsonPayload) throws ChargebeeException {

    return postJson("coupon", "createForItems", "/coupons/create_for_items", jsonPayload);
  }

  public CouponCreateForItemsResponse createForItems(CouponCreateForItemsParams params)
      throws ChargebeeException {
    Response response = createForItemsRaw(params);

    return CouponCreateForItemsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** Async variant of createForItems for coupon with params. */
  public CompletableFuture<CouponCreateForItemsResponse> createForItemsAsync(
      CouponCreateForItemsParams params) {

    return postAsync(
            "coupon",
            "createForItems",
            "/coupons/create_for_items",
            params != null ? params.toFormData() : null)
        .thenApply(
            response ->
                CouponCreateForItemsResponse.fromJson(response.getBodyAsString(), response));
  }
}
