/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.services;

import com.chargebee.v4.client.ChargebeeClient;
import com.chargebee.v4.client.request.RequestOptions;
import com.chargebee.v4.exceptions.ChargebeeException;
import com.chargebee.v4.transport.Response;

import com.chargebee.v4.models.customer.params.CustomerDeleteParams;

import com.chargebee.v4.models.customer.params.CustomerAddPromotionalCreditsParams;

import com.chargebee.v4.models.customer.params.CustomerRelationshipsParams;

import com.chargebee.v4.models.customer.params.CustomerDeleteContactParams;

import com.chargebee.v4.models.customer.params.CustomerAssignPaymentRoleParams;

import com.chargebee.v4.models.customer.params.CustomerMoveParams;

import com.chargebee.v4.models.customer.params.CustomerHierarchyParams;

import com.chargebee.v4.models.customer.params.CustomerUpdatePaymentMethodParams;

import com.chargebee.v4.models.customer.params.CustomerUpdateParams;

import com.chargebee.v4.models.customer.params.CustomerListHierarchyDetailParams;

import com.chargebee.v4.models.customer.params.CustomerChangeBillingDateParams;

import com.chargebee.v4.models.customer.params.CustomerListParams;

import com.chargebee.v4.models.customer.params.CustomerCreateParams;

import com.chargebee.v4.models.customer.params.CustomerAddContactParams;

import com.chargebee.v4.models.customer.params.ContactsForCustomerParams;

import com.chargebee.v4.models.customer.params.CustomerDeductPromotionalCreditsParams;

import com.chargebee.v4.models.customer.params.CustomerMergeParams;

import com.chargebee.v4.models.customer.params.CustomerCollectPaymentParams;

import com.chargebee.v4.models.customer.params.CustomerRecordExcessPaymentParams;

import com.chargebee.v4.models.customer.params.CustomerSetPromotionalCreditsParams;

import com.chargebee.v4.models.customer.params.CustomerUpdateContactParams;

import com.chargebee.v4.models.customer.params.CustomerUpdateHierarchySettingsParams;

import com.chargebee.v4.models.customer.params.CustomerUpdateBillingInfoParams;

import com.chargebee.v4.models.customer.responses.CustomerDeleteResponse;

import com.chargebee.v4.models.customer.responses.CustomerAddPromotionalCreditsResponse;

import com.chargebee.v4.models.customer.responses.CustomerRelationshipsResponse;

import com.chargebee.v4.models.customer.responses.CustomerDeleteRelationshipResponse;

import com.chargebee.v4.models.customer.responses.CustomerDeleteContactResponse;

import com.chargebee.v4.models.customer.responses.CustomerAssignPaymentRoleResponse;

import com.chargebee.v4.models.customer.responses.CustomerMoveResponse;

import com.chargebee.v4.models.customer.responses.CustomerHierarchyResponse;

import com.chargebee.v4.models.customer.responses.CustomerUpdatePaymentMethodResponse;

import com.chargebee.v4.models.customer.responses.CustomerRetrieveResponse;

import com.chargebee.v4.models.customer.responses.CustomerUpdateResponse;

import com.chargebee.v4.models.customer.responses.CustomerListHierarchyDetailResponse;

import com.chargebee.v4.models.customer.responses.CustomerChangeBillingDateResponse;

import com.chargebee.v4.models.customer.responses.CustomerListResponse;

import com.chargebee.v4.models.customer.responses.CustomerCreateResponse;

import com.chargebee.v4.models.customer.responses.CustomerAddContactResponse;

import com.chargebee.v4.models.customer.responses.ContactsForCustomerResponse;

import com.chargebee.v4.models.customer.responses.CustomerDeductPromotionalCreditsResponse;

import com.chargebee.v4.models.customer.responses.CustomerClearPersonalDataResponse;

import com.chargebee.v4.models.customer.responses.CustomerMergeResponse;

import com.chargebee.v4.models.customer.responses.CustomerCollectPaymentResponse;

import com.chargebee.v4.models.customer.responses.CustomerRecordExcessPaymentResponse;

import com.chargebee.v4.models.customer.responses.CustomerSetPromotionalCreditsResponse;

import com.chargebee.v4.models.customer.responses.CustomerUpdateContactResponse;

import com.chargebee.v4.models.customer.responses.CustomerUpdateHierarchySettingsResponse;

import com.chargebee.v4.models.customer.responses.CustomerUpdateBillingInfoResponse;

public final class CustomerService extends BaseService<CustomerService> {

  private final ServiceConfig config;

  public CustomerService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private CustomerService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private CustomerService(ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  CustomerService with(RequestOptions newOptions) {
    return new CustomerService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public CustomerService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /** delete a customer (executes immediately) - returns raw Response. */
  Response deleteRaw(String customerId) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}/delete", "customer-id", customerId);

    return post(path, null);
  }

  /** delete a customer using immutable params (executes immediately) - returns raw Response. */
  Response deleteRaw(String customerId, CustomerDeleteParams params) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}/delete", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /** delete a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response deleteRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}/delete", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerDeleteResponse delete(String customerId, CustomerDeleteParams params)
      throws ChargebeeException {
    Response response = deleteRaw(customerId, params);
    return CustomerDeleteResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerDeleteResponse delete(String customerId) throws ChargebeeException {
    Response response = deleteRaw(customerId);
    return CustomerDeleteResponse.fromJson(response.getBodyAsString(), response);
  }

  /** addPromotionalCredits a customer (executes immediately) - returns raw Response. */
  Response addPromotionalCreditsRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/add_promotional_credits", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * addPromotionalCredits a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response addPromotionalCreditsRaw(String customerId, CustomerAddPromotionalCreditsParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/add_promotional_credits", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * addPromotionalCredits a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response addPromotionalCreditsRaw(String customerId, String jsonPayload)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/add_promotional_credits", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerAddPromotionalCreditsResponse addPromotionalCredits(
      String customerId, CustomerAddPromotionalCreditsParams params) throws ChargebeeException {
    Response response = addPromotionalCreditsRaw(customerId, params);
    return CustomerAddPromotionalCreditsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** relationships a customer (executes immediately) - returns raw Response. */
  Response relationshipsRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/relationships", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * relationships a customer using immutable params (executes immediately) - returns raw Response.
   */
  Response relationshipsRaw(String customerId, CustomerRelationshipsParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/relationships", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * relationships a customer using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response relationshipsRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/relationships", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerRelationshipsResponse relationships(
      String customerId, CustomerRelationshipsParams params) throws ChargebeeException {
    Response response = relationshipsRaw(customerId, params);
    return CustomerRelationshipsResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerRelationshipsResponse relationships(String customerId) throws ChargebeeException {
    Response response = relationshipsRaw(customerId);
    return CustomerRelationshipsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** deleteRelationship a customer (executes immediately) - returns raw Response. */
  Response deleteRelationshipRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/delete_relationship", "customer-id", customerId);

    return post(path, null);
  }

  public CustomerDeleteRelationshipResponse deleteRelationship(String customerId)
      throws ChargebeeException {
    Response response = deleteRelationshipRaw(customerId);
    return CustomerDeleteRelationshipResponse.fromJson(response.getBodyAsString(), response);
  }

  /** deleteContact a customer (executes immediately) - returns raw Response. */
  Response deleteContactRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/delete_contact", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * deleteContact a customer using immutable params (executes immediately) - returns raw Response.
   */
  Response deleteContactRaw(String customerId, CustomerDeleteContactParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/delete_contact", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * deleteContact a customer using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response deleteContactRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/delete_contact", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerDeleteContactResponse deleteContact(
      String customerId, CustomerDeleteContactParams params) throws ChargebeeException {
    Response response = deleteContactRaw(customerId, params);
    return CustomerDeleteContactResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerDeleteContactResponse deleteContact(String customerId) throws ChargebeeException {
    Response response = deleteContactRaw(customerId);
    return CustomerDeleteContactResponse.fromJson(response.getBodyAsString(), response);
  }

  /** assignPaymentRole a customer (executes immediately) - returns raw Response. */
  Response assignPaymentRoleRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/assign_payment_role", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * assignPaymentRole a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response assignPaymentRoleRaw(String customerId, CustomerAssignPaymentRoleParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/assign_payment_role", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * assignPaymentRole a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response assignPaymentRoleRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/assign_payment_role", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerAssignPaymentRoleResponse assignPaymentRole(
      String customerId, CustomerAssignPaymentRoleParams params) throws ChargebeeException {
    Response response = assignPaymentRoleRaw(customerId, params);
    return CustomerAssignPaymentRoleResponse.fromJson(response.getBodyAsString(), response);
  }

  /** move a customer using immutable params (executes immediately) - returns raw Response. */
  Response moveRaw(CustomerMoveParams params) throws ChargebeeException {

    return post("/customers/move", params != null ? params.toFormData() : null);
  }

  /** move a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response moveRaw(String jsonPayload) throws ChargebeeException {

    return postJson("/customers/move", jsonPayload);
  }

  public CustomerMoveResponse move(CustomerMoveParams params) throws ChargebeeException {
    Response response = moveRaw(params);

    return CustomerMoveResponse.fromJson(response.getBodyAsString(), response);
  }

  /** hierarchy a customer (executes immediately) - returns raw Response. */
  Response hierarchyRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/hierarchy", "customer-id", customerId);

    return get(path, null);
  }

  /** hierarchy a customer using immutable params (executes immediately) - returns raw Response. */
  Response hierarchyRaw(String customerId, CustomerHierarchyParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/hierarchy", "customer-id", customerId);
    return get(path, params != null ? params.toQueryParams() : null);
  }

  public CustomerHierarchyResponse hierarchy(String customerId, CustomerHierarchyParams params)
      throws ChargebeeException {
    Response response = hierarchyRaw(customerId, params);
    return CustomerHierarchyResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerHierarchyResponse hierarchy(String customerId) throws ChargebeeException {
    Response response = hierarchyRaw(customerId);
    return CustomerHierarchyResponse.fromJson(response.getBodyAsString(), response);
  }

  /** updatePaymentMethod a customer (executes immediately) - returns raw Response. */
  Response updatePaymentMethodRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_payment_method", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * updatePaymentMethod a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response updatePaymentMethodRaw(String customerId, CustomerUpdatePaymentMethodParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_payment_method", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * updatePaymentMethod a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response updatePaymentMethodRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_payment_method", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerUpdatePaymentMethodResponse updatePaymentMethod(
      String customerId, CustomerUpdatePaymentMethodParams params) throws ChargebeeException {
    Response response = updatePaymentMethodRaw(customerId, params);
    return CustomerUpdatePaymentMethodResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerUpdatePaymentMethodResponse updatePaymentMethod(String customerId)
      throws ChargebeeException {
    Response response = updatePaymentMethodRaw(customerId);
    return CustomerUpdatePaymentMethodResponse.fromJson(response.getBodyAsString(), response);
  }

  /** retrieve a customer (executes immediately) - returns raw Response. */
  Response retrieveRaw(String customerId) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}", "customer-id", customerId);

    return get(path, null);
  }

  public CustomerRetrieveResponse retrieve(String customerId) throws ChargebeeException {
    Response response = retrieveRaw(customerId);
    return CustomerRetrieveResponse.fromJson(response.getBodyAsString(), response);
  }

  /** update a customer (executes immediately) - returns raw Response. */
  Response updateRaw(String customerId) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}", "customer-id", customerId);

    return post(path, null);
  }

  /** update a customer using immutable params (executes immediately) - returns raw Response. */
  Response updateRaw(String customerId, CustomerUpdateParams params) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /** update a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response updateRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path = buildPathWithParams("/customers/{customer-id}", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerUpdateResponse update(String customerId, CustomerUpdateParams params)
      throws ChargebeeException {
    Response response = updateRaw(customerId, params);
    return CustomerUpdateResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerUpdateResponse update(String customerId) throws ChargebeeException {
    Response response = updateRaw(customerId);
    return CustomerUpdateResponse.fromJson(response.getBodyAsString(), response);
  }

  /**
   * listHierarchyDetail a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response listHierarchyDetailRaw(String customerId, CustomerListHierarchyDetailParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/hierarchy_detail", "customer-id", customerId);
    return get(path, params != null ? params.toQueryParams() : null);
  }

  /**
   * listHierarchyDetail a customer without params (executes immediately) - returns raw Response.
   */
  Response listHierarchyDetailRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/hierarchy_detail", "customer-id", customerId);
    return get(path, null);
  }

  /**
   * listHierarchyDetail a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response listHierarchyDetailRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/hierarchy_detail", "customer-id", customerId);
    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public CustomerListHierarchyDetailResponse listHierarchyDetail(
      String customerId, CustomerListHierarchyDetailParams params) throws ChargebeeException {
    Response response = listHierarchyDetailRaw(customerId, params);
    return CustomerListHierarchyDetailResponse.fromJson(
        response.getBodyAsString(), this, params, customerId, response);
  }

  public CustomerListHierarchyDetailResponse listHierarchyDetail(String customerId)
      throws ChargebeeException {
    Response response = listHierarchyDetailRaw(customerId);
    return CustomerListHierarchyDetailResponse.fromJson(
        response.getBodyAsString(), this, null, customerId, response);
  }

  /** changeBillingDate a customer (executes immediately) - returns raw Response. */
  Response changeBillingDateRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/change_billing_date", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * changeBillingDate a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response changeBillingDateRaw(String customerId, CustomerChangeBillingDateParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/change_billing_date", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * changeBillingDate a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response changeBillingDateRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/change_billing_date", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerChangeBillingDateResponse changeBillingDate(
      String customerId, CustomerChangeBillingDateParams params) throws ChargebeeException {
    Response response = changeBillingDateRaw(customerId, params);
    return CustomerChangeBillingDateResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerChangeBillingDateResponse changeBillingDate(String customerId)
      throws ChargebeeException {
    Response response = changeBillingDateRaw(customerId);
    return CustomerChangeBillingDateResponse.fromJson(response.getBodyAsString(), response);
  }

  /** list a customer using immutable params (executes immediately) - returns raw Response. */
  Response listRaw(CustomerListParams params) throws ChargebeeException {

    return get("/customers", params != null ? params.toQueryParams() : null);
  }

  /** list a customer without params (executes immediately) - returns raw Response. */
  Response listRaw() throws ChargebeeException {

    return get("/customers", null);
  }

  /** list a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response listRaw(String jsonPayload) throws ChargebeeException {

    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public CustomerListResponse list(CustomerListParams params) throws ChargebeeException {
    Response response = listRaw(params);

    return CustomerListResponse.fromJson(response.getBodyAsString(), this, params, response);
  }

  public CustomerListResponse list() throws ChargebeeException {
    Response response = listRaw();

    return CustomerListResponse.fromJson(response.getBodyAsString(), this, null, response);
  }

  /** create a customer using immutable params (executes immediately) - returns raw Response. */
  Response createRaw(CustomerCreateParams params) throws ChargebeeException {

    return post("/customers", params != null ? params.toFormData() : null);
  }

  /** create a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response createRaw(String jsonPayload) throws ChargebeeException {

    return postJson("/customers", jsonPayload);
  }

  public CustomerCreateResponse create(CustomerCreateParams params) throws ChargebeeException {
    Response response = createRaw(params);

    return CustomerCreateResponse.fromJson(response.getBodyAsString(), response);
  }

  /** addContact a customer (executes immediately) - returns raw Response. */
  Response addContactRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/add_contact", "customer-id", customerId);

    return post(path, null);
  }

  /** addContact a customer using immutable params (executes immediately) - returns raw Response. */
  Response addContactRaw(String customerId, CustomerAddContactParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/add_contact", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /** addContact a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response addContactRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/add_contact", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerAddContactResponse addContact(String customerId, CustomerAddContactParams params)
      throws ChargebeeException {
    Response response = addContactRaw(customerId, params);
    return CustomerAddContactResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerAddContactResponse addContact(String customerId) throws ChargebeeException {
    Response response = addContactRaw(customerId);
    return CustomerAddContactResponse.fromJson(response.getBodyAsString(), response);
  }

  /**
   * contactsForCustomer a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response contactsForCustomerRaw(String customerId, ContactsForCustomerParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/contacts", "customer-id", customerId);
    return get(path, params != null ? params.toQueryParams() : null);
  }

  /**
   * contactsForCustomer a customer without params (executes immediately) - returns raw Response.
   */
  Response contactsForCustomerRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/contacts", "customer-id", customerId);
    return get(path, null);
  }

  /**
   * contactsForCustomer a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response contactsForCustomerRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/contacts", "customer-id", customerId);
    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public ContactsForCustomerResponse contactsForCustomer(
      String customerId, ContactsForCustomerParams params) throws ChargebeeException {
    Response response = contactsForCustomerRaw(customerId, params);
    return ContactsForCustomerResponse.fromJson(
        response.getBodyAsString(), this, params, customerId, response);
  }

  public ContactsForCustomerResponse contactsForCustomer(String customerId)
      throws ChargebeeException {
    Response response = contactsForCustomerRaw(customerId);
    return ContactsForCustomerResponse.fromJson(
        response.getBodyAsString(), this, null, customerId, response);
  }

  /** deductPromotionalCredits a customer (executes immediately) - returns raw Response. */
  Response deductPromotionalCreditsRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/deduct_promotional_credits", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * deductPromotionalCredits a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response deductPromotionalCreditsRaw(
      String customerId, CustomerDeductPromotionalCreditsParams params) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/deduct_promotional_credits", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * deductPromotionalCredits a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response deductPromotionalCreditsRaw(String customerId, String jsonPayload)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/deduct_promotional_credits", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerDeductPromotionalCreditsResponse deductPromotionalCredits(
      String customerId, CustomerDeductPromotionalCreditsParams params) throws ChargebeeException {
    Response response = deductPromotionalCreditsRaw(customerId, params);
    return CustomerDeductPromotionalCreditsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** clearPersonalData a customer (executes immediately) - returns raw Response. */
  Response clearPersonalDataRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/clear_personal_data", "customer-id", customerId);

    return post(path, null);
  }

  public CustomerClearPersonalDataResponse clearPersonalData(String customerId)
      throws ChargebeeException {
    Response response = clearPersonalDataRaw(customerId);
    return CustomerClearPersonalDataResponse.fromJson(response.getBodyAsString(), response);
  }

  /** merge a customer using immutable params (executes immediately) - returns raw Response. */
  Response mergeRaw(CustomerMergeParams params) throws ChargebeeException {

    return post("/customers/merge", params != null ? params.toFormData() : null);
  }

  /** merge a customer using raw JSON payload (executes immediately) - returns raw Response. */
  Response mergeRaw(String jsonPayload) throws ChargebeeException {

    return postJson("/customers/merge", jsonPayload);
  }

  public CustomerMergeResponse merge(CustomerMergeParams params) throws ChargebeeException {
    Response response = mergeRaw(params);

    return CustomerMergeResponse.fromJson(response.getBodyAsString(), response);
  }

  /** collectPayment a customer (executes immediately) - returns raw Response. */
  Response collectPaymentRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/collect_payment", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * collectPayment a customer using immutable params (executes immediately) - returns raw Response.
   */
  Response collectPaymentRaw(String customerId, CustomerCollectPaymentParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/collect_payment", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * collectPayment a customer using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response collectPaymentRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/collect_payment", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerCollectPaymentResponse collectPayment(
      String customerId, CustomerCollectPaymentParams params) throws ChargebeeException {
    Response response = collectPaymentRaw(customerId, params);
    return CustomerCollectPaymentResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerCollectPaymentResponse collectPayment(String customerId)
      throws ChargebeeException {
    Response response = collectPaymentRaw(customerId);
    return CustomerCollectPaymentResponse.fromJson(response.getBodyAsString(), response);
  }

  /** recordExcessPayment a customer (executes immediately) - returns raw Response. */
  Response recordExcessPaymentRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/record_excess_payment", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * recordExcessPayment a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response recordExcessPaymentRaw(String customerId, CustomerRecordExcessPaymentParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/record_excess_payment", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * recordExcessPayment a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response recordExcessPaymentRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/record_excess_payment", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerRecordExcessPaymentResponse recordExcessPayment(
      String customerId, CustomerRecordExcessPaymentParams params) throws ChargebeeException {
    Response response = recordExcessPaymentRaw(customerId, params);
    return CustomerRecordExcessPaymentResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerRecordExcessPaymentResponse recordExcessPayment(String customerId)
      throws ChargebeeException {
    Response response = recordExcessPaymentRaw(customerId);
    return CustomerRecordExcessPaymentResponse.fromJson(response.getBodyAsString(), response);
  }

  /** setPromotionalCredits a customer (executes immediately) - returns raw Response. */
  Response setPromotionalCreditsRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/set_promotional_credits", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * setPromotionalCredits a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response setPromotionalCreditsRaw(String customerId, CustomerSetPromotionalCreditsParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/set_promotional_credits", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * setPromotionalCredits a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response setPromotionalCreditsRaw(String customerId, String jsonPayload)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/set_promotional_credits", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerSetPromotionalCreditsResponse setPromotionalCredits(
      String customerId, CustomerSetPromotionalCreditsParams params) throws ChargebeeException {
    Response response = setPromotionalCreditsRaw(customerId, params);
    return CustomerSetPromotionalCreditsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** updateContact a customer (executes immediately) - returns raw Response. */
  Response updateContactRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/update_contact", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * updateContact a customer using immutable params (executes immediately) - returns raw Response.
   */
  Response updateContactRaw(String customerId, CustomerUpdateContactParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/update_contact", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * updateContact a customer using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response updateContactRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams("/customers/{customer-id}/update_contact", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerUpdateContactResponse updateContact(
      String customerId, CustomerUpdateContactParams params) throws ChargebeeException {
    Response response = updateContactRaw(customerId, params);
    return CustomerUpdateContactResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerUpdateContactResponse updateContact(String customerId) throws ChargebeeException {
    Response response = updateContactRaw(customerId);
    return CustomerUpdateContactResponse.fromJson(response.getBodyAsString(), response);
  }

  /** updateHierarchySettings a customer (executes immediately) - returns raw Response. */
  Response updateHierarchySettingsRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_hierarchy_settings", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * updateHierarchySettings a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response updateHierarchySettingsRaw(
      String customerId, CustomerUpdateHierarchySettingsParams params) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_hierarchy_settings", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * updateHierarchySettings a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response updateHierarchySettingsRaw(String customerId, String jsonPayload)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_hierarchy_settings", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerUpdateHierarchySettingsResponse updateHierarchySettings(
      String customerId, CustomerUpdateHierarchySettingsParams params) throws ChargebeeException {
    Response response = updateHierarchySettingsRaw(customerId, params);
    return CustomerUpdateHierarchySettingsResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerUpdateHierarchySettingsResponse updateHierarchySettings(String customerId)
      throws ChargebeeException {
    Response response = updateHierarchySettingsRaw(customerId);
    return CustomerUpdateHierarchySettingsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** updateBillingInfo a customer (executes immediately) - returns raw Response. */
  Response updateBillingInfoRaw(String customerId) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_billing_info", "customer-id", customerId);

    return post(path, null);
  }

  /**
   * updateBillingInfo a customer using immutable params (executes immediately) - returns raw
   * Response.
   */
  Response updateBillingInfoRaw(String customerId, CustomerUpdateBillingInfoParams params)
      throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_billing_info", "customer-id", customerId);
    return post(path, params.toFormData());
  }

  /**
   * updateBillingInfo a customer using raw JSON payload (executes immediately) - returns raw
   * Response.
   */
  Response updateBillingInfoRaw(String customerId, String jsonPayload) throws ChargebeeException {
    String path =
        buildPathWithParams(
            "/customers/{customer-id}/update_billing_info", "customer-id", customerId);
    return postJson(path, jsonPayload);
  }

  public CustomerUpdateBillingInfoResponse updateBillingInfo(
      String customerId, CustomerUpdateBillingInfoParams params) throws ChargebeeException {
    Response response = updateBillingInfoRaw(customerId, params);
    return CustomerUpdateBillingInfoResponse.fromJson(response.getBodyAsString(), response);
  }

  public CustomerUpdateBillingInfoResponse updateBillingInfo(String customerId)
      throws ChargebeeException {
    Response response = updateBillingInfoRaw(customerId);
    return CustomerUpdateBillingInfoResponse.fromJson(response.getBodyAsString(), response);
  }
}
