/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.services;

import com.chargebee.v4.client.ChargebeeClient;
import com.chargebee.v4.client.request.RequestOptions;
import com.chargebee.v4.transport.Response;

import com.chargebee.v4.models.gift.params.GiftCreateForItemsParams;

import com.chargebee.v4.models.gift.params.UpdateGiftForGiftParams;

import com.chargebee.v4.models.gift.params.GiftListParams;

import com.chargebee.v4.models.gift.params.GiftCreateParams;

import com.chargebee.v4.models.gift.responses.GiftCreateForItemsResponse;

import com.chargebee.v4.models.gift.responses.CancelForGiftResponse;

import com.chargebee.v4.models.gift.responses.UpdateGiftForGiftResponse;

import com.chargebee.v4.models.gift.responses.GiftListResponse;

import com.chargebee.v4.models.gift.responses.GiftCreateResponse;

import com.chargebee.v4.models.gift.responses.GiftRetrieveResponse;

import com.chargebee.v4.models.gift.responses.ClaimForGiftResponse;

public final class GiftService extends BaseService<GiftService> {

  private final ServiceConfig config;

  public GiftService(ChargebeeClient client) {
    super(client);
    this.config = ServiceConfig.defaultConfig();
  }

  private GiftService(ChargebeeClient client, RequestOptions options) {
    super(client, options);
    this.config = ServiceConfig.defaultConfig();
  }

  private GiftService(ChargebeeClient client, RequestOptions options, ServiceConfig config) {
    super(client, options);
    this.config = config;
  }

  @Override
  GiftService with(RequestOptions newOptions) {
    return new GiftService(client, newOptions, config);
  }

  /**
   * Apply per-request options for this service instance. Users can chain .withOptions or .options
   * to set headers and other options.
   */
  public GiftService withOptions(RequestOptions options) {
    return with(options);
  }

  // === Operations ===

  /** createForItems a gift using immutable params (executes immediately) - returns raw Response. */
  Response createForItemsRaw(GiftCreateForItemsParams params) throws Exception {

    return post("/gifts/create_for_items", params != null ? params.toFormData() : null);
  }

  /** createForItems a gift using raw JSON payload (executes immediately) - returns raw Response. */
  Response createForItemsRaw(String jsonPayload) throws Exception {

    return postJson("/gifts/create_for_items", jsonPayload);
  }

  public GiftCreateForItemsResponse createForItems(GiftCreateForItemsParams params)
      throws Exception {
    Response response = createForItemsRaw(params);

    return GiftCreateForItemsResponse.fromJson(response.getBodyAsString(), response);
  }

  /** cancelForGift a gift (executes immediately) - returns raw Response. */
  Response cancelForGiftRaw(String giftId) throws Exception {
    String path = buildPathWithParams("/gifts/{gift-id}/cancel", "gift-id", giftId);

    return post(path, null);
  }

  public CancelForGiftResponse cancelForGift(String giftId) throws Exception {
    Response response = cancelForGiftRaw(giftId);
    return CancelForGiftResponse.fromJson(response.getBodyAsString(), response);
  }

  /** updateGiftForGift a gift (executes immediately) - returns raw Response. */
  Response updateGiftForGiftRaw(String giftId) throws Exception {
    String path = buildPathWithParams("/gifts/{gift-id}/update_gift", "gift-id", giftId);

    return post(path, null);
  }

  /**
   * updateGiftForGift a gift using immutable params (executes immediately) - returns raw Response.
   */
  Response updateGiftForGiftRaw(String giftId, UpdateGiftForGiftParams params) throws Exception {
    String path = buildPathWithParams("/gifts/{gift-id}/update_gift", "gift-id", giftId);
    return post(path, params.toFormData());
  }

  /**
   * updateGiftForGift a gift using raw JSON payload (executes immediately) - returns raw Response.
   */
  Response updateGiftForGiftRaw(String giftId, String jsonPayload) throws Exception {
    String path = buildPathWithParams("/gifts/{gift-id}/update_gift", "gift-id", giftId);
    return postJson(path, jsonPayload);
  }

  public UpdateGiftForGiftResponse updateGiftForGift(String giftId, UpdateGiftForGiftParams params)
      throws Exception {
    Response response = updateGiftForGiftRaw(giftId, params);
    return UpdateGiftForGiftResponse.fromJson(response.getBodyAsString(), response);
  }

  /** list a gift using immutable params (executes immediately) - returns raw Response. */
  Response listRaw(GiftListParams params) throws Exception {

    return get("/gifts", params != null ? params.toQueryParams() : null);
  }

  /** list a gift without params (executes immediately) - returns raw Response. */
  Response listRaw() throws Exception {

    return get("/gifts", null);
  }

  /** list a gift using raw JSON payload (executes immediately) - returns raw Response. */
  Response listRaw(String jsonPayload) throws Exception {

    throw new UnsupportedOperationException("JSON payload not supported for GET operations");
  }

  public GiftListResponse list(GiftListParams params) throws Exception {
    Response response = listRaw(params);

    return GiftListResponse.fromJson(response.getBodyAsString(), this, params, response);
  }

  public GiftListResponse list() throws Exception {
    Response response = listRaw();
    return GiftListResponse.fromJson(response.getBodyAsString(), this, null, response);
  }

  /** create a gift using immutable params (executes immediately) - returns raw Response. */
  Response createRaw(GiftCreateParams params) throws Exception {

    return post("/gifts", params != null ? params.toFormData() : null);
  }

  /** create a gift using raw JSON payload (executes immediately) - returns raw Response. */
  Response createRaw(String jsonPayload) throws Exception {

    return postJson("/gifts", jsonPayload);
  }

  public GiftCreateResponse create(GiftCreateParams params) throws Exception {
    Response response = createRaw(params);

    return GiftCreateResponse.fromJson(response.getBodyAsString(), response);
  }

  /** retrieve a gift (executes immediately) - returns raw Response. */
  Response retrieveRaw(String giftId) throws Exception {
    String path = buildPathWithParams("/gifts/{gift-id}", "gift-id", giftId);

    return get(path, null);
  }

  public GiftRetrieveResponse retrieve(String giftId) throws Exception {
    Response response = retrieveRaw(giftId);
    return GiftRetrieveResponse.fromJson(response.getBodyAsString(), response);
  }

  /** claimForGift a gift (executes immediately) - returns raw Response. */
  Response claimForGiftRaw(String giftId) throws Exception {
    String path = buildPathWithParams("/gifts/{gift-id}/claim", "gift-id", giftId);

    return post(path, null);
  }

  public ClaimForGiftResponse claimForGift(String giftId) throws Exception {
    Response response = claimForGiftRaw(giftId);
    return ClaimForGiftResponse.fromJson(response.getBodyAsString(), response);
  }
}
