/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.ledgerAccountBalance.params;

import com.chargebee.v4.internal.Recommended;
import com.chargebee.v4.filters.StringFilter;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class ListLedgerAccountBalancesParams {

  private final Map<String, Object> queryParams;

  private ListLedgerAccountBalancesParams(ListLedgerAccountBalancesBuilder builder) {
    this.queryParams = Collections.unmodifiableMap(new LinkedHashMap<>(builder.queryParams));
  }

  /** Get the query parameters for this request. */
  public Map<String, Object> toQueryParams() {
    return queryParams;
  }

  public ListLedgerAccountBalancesBuilder toBuilder() {
    ListLedgerAccountBalancesBuilder builder = new ListLedgerAccountBalancesBuilder();
    builder.queryParams.putAll(queryParams);
    return builder;
  }

  /** Create a new builder for ListLedgerAccountBalancesParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static ListLedgerAccountBalancesBuilder builder() {
    return new ListLedgerAccountBalancesBuilder();
  }

  public static final class ListLedgerAccountBalancesBuilder {
    private final Map<String, Object> queryParams = new LinkedHashMap<>();

    private ListLedgerAccountBalancesBuilder() {}

    public ListLedgerAccountBalancesBuilder limit(Integer value) {
      queryParams.put("limit", value);
      return this;
    }

    public ListLedgerAccountBalancesBuilder offset(String value) {
      queryParams.put("offset", value);
      return this;
    }

    public SubscriptionIdFilter subscriptionId() {
      return new SubscriptionIdFilter("subscription_id", this, queryParams);
    }

    public UnitIdFilter unitId() {
      return new UnitIdFilter("unit_id", this, queryParams);
    }

    public ListLedgerAccountBalancesParams build() {
      return new ListLedgerAccountBalancesParams(this);
    }

    public static final class SubscriptionIdFilter
        extends StringFilter<ListLedgerAccountBalancesBuilder> {
      SubscriptionIdFilter(
          String fieldName, ListLedgerAccountBalancesBuilder builder, Map<String, Object> params) {
        super(fieldName, builder, params);
      }
    }

    public static final class UnitIdFilter extends StringFilter<ListLedgerAccountBalancesBuilder> {
      UnitIdFilter(
          String fieldName, ListLedgerAccountBalancesBuilder builder, Map<String, Object> params) {
        super(fieldName, builder, params);
      }
    }
  }
}
