/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.core.models.subscription.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.sql.Timestamp;

public final class SubscriptionRegenerateInvoiceParams {

  private final Map<String, Object> formData;

  private SubscriptionRegenerateInvoiceParams(SubscriptionRegenerateInvoiceBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for SubscriptionRegenerateInvoiceParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static SubscriptionRegenerateInvoiceBuilder builder() {
    return new SubscriptionRegenerateInvoiceBuilder();
  }

  public static final class SubscriptionRegenerateInvoiceBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private SubscriptionRegenerateInvoiceBuilder() {}

    public SubscriptionRegenerateInvoiceBuilder dateFrom(Timestamp value) {

      formData.put("date_from", value);

      return this;
    }

    public SubscriptionRegenerateInvoiceBuilder dateTo(Timestamp value) {

      formData.put("date_to", value);

      return this;
    }

    public SubscriptionRegenerateInvoiceBuilder prorate(Boolean value) {

      formData.put("prorate", value);

      return this;
    }

    public SubscriptionRegenerateInvoiceBuilder invoiceImmediately(Boolean value) {

      formData.put("invoice_immediately", value);

      return this;
    }

    public SubscriptionRegenerateInvoiceParams build() {
      return new SubscriptionRegenerateInvoiceParams(this);
    }
  }
}
