/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.core.models.customer;

import com.chargebee.internal.JsonUtil;
import java.sql.Timestamp;
import java.util.List;

public class Customer {

  private String id;
  private String firstName;
  private String lastName;
  private String email;
  private String phone;
  private String company;
  private String vatNumber;
  private AutoCollection autoCollection;
  private OfflinePaymentMethod offlinePaymentMethod;
  private Integer netTermDays;
  private Timestamp vatNumberValidatedTime;
  private VatNumberStatus vatNumberStatus;
  private Boolean allowDirectDebit;
  private Boolean isLocationValid;
  private Timestamp createdAt;
  private String createdFromIp;
  private List<String> exemptionDetails;
  private Taxability taxability;
  private EntityCode entityCode;
  private String exemptNumber;
  private Long resourceVersion;
  private Timestamp updatedAt;
  private String locale;
  private Integer billingDate;
  private Integer billingMonth;
  private BillingDateMode billingDateMode;
  private BillingDayOfWeek billingDayOfWeek;
  private BillingDayOfWeekMode billingDayOfWeekMode;
  private PiiCleared piiCleared;
  private Boolean autoCloseInvoices;
  private Channel channel;
  private String activeId;
  private CardStatus cardStatus;
  private FraudFlag fraudFlag;
  private String primaryPaymentSourceId;
  private String backupPaymentSourceId;
  private String invoiceNotes;
  private String businessEntityId;
  private String preferredCurrencyCode;
  private Long promotionalCredits;
  private Long unbilledCharges;
  private Long refundableCredits;
  private Long excessPayments;
  private Boolean isEinvoiceEnabled;
  private EinvoicingMethod einvoicingMethod;
  private Object metaData;
  private Boolean deleted;
  private Boolean registeredForGst;
  private Boolean consolidatedInvoicing;
  private CustomerType customerType;
  private Boolean businessCustomerWithoutVatNumber;
  private String clientProfileId;
  private Boolean useDefaultHierarchySettings;
  private String vatNumberPrefix;
  private String entityIdentifierScheme;
  private String entityIdentifierStandard;
  private BillingAddress billingAddress;
  private List<ReferralUrls> referralUrls;
  private List<Contacts> contacts;
  private PaymentMethod paymentMethod;
  private List<Balances> balances;
  private List<EntityIdentifiers> entityIdentifiers;
  private List<TaxProvidersFields> taxProvidersFields;
  private Relationship relationship;
  private ParentAccountAccess parentAccountAccess;
  private ChildAccountAccess childAccountAccess;

  public String getId() {
    return id;
  }

  public String getFirstName() {
    return firstName;
  }

  public String getLastName() {
    return lastName;
  }

  public String getEmail() {
    return email;
  }

  public String getPhone() {
    return phone;
  }

  public String getCompany() {
    return company;
  }

  public String getVatNumber() {
    return vatNumber;
  }

  public AutoCollection getAutoCollection() {
    return autoCollection;
  }

  public OfflinePaymentMethod getOfflinePaymentMethod() {
    return offlinePaymentMethod;
  }

  public Integer getNetTermDays() {
    return netTermDays;
  }

  public Timestamp getVatNumberValidatedTime() {
    return vatNumberValidatedTime;
  }

  public VatNumberStatus getVatNumberStatus() {
    return vatNumberStatus;
  }

  public Boolean getAllowDirectDebit() {
    return allowDirectDebit;
  }

  public Boolean getIsLocationValid() {
    return isLocationValid;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public String getCreatedFromIp() {
    return createdFromIp;
  }

  public List<String> getExemptionDetails() {
    return exemptionDetails;
  }

  public Taxability getTaxability() {
    return taxability;
  }

  public EntityCode getEntityCode() {
    return entityCode;
  }

  public String getExemptNumber() {
    return exemptNumber;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public Timestamp getUpdatedAt() {
    return updatedAt;
  }

  public String getLocale() {
    return locale;
  }

  public Integer getBillingDate() {
    return billingDate;
  }

  public Integer getBillingMonth() {
    return billingMonth;
  }

  public BillingDateMode getBillingDateMode() {
    return billingDateMode;
  }

  public BillingDayOfWeek getBillingDayOfWeek() {
    return billingDayOfWeek;
  }

  public BillingDayOfWeekMode getBillingDayOfWeekMode() {
    return billingDayOfWeekMode;
  }

  public PiiCleared getPiiCleared() {
    return piiCleared;
  }

  public Boolean getAutoCloseInvoices() {
    return autoCloseInvoices;
  }

  public Channel getChannel() {
    return channel;
  }

  public String getActiveId() {
    return activeId;
  }

  public CardStatus getCardStatus() {
    return cardStatus;
  }

  public FraudFlag getFraudFlag() {
    return fraudFlag;
  }

  public String getPrimaryPaymentSourceId() {
    return primaryPaymentSourceId;
  }

  public String getBackupPaymentSourceId() {
    return backupPaymentSourceId;
  }

  public String getInvoiceNotes() {
    return invoiceNotes;
  }

  public String getBusinessEntityId() {
    return businessEntityId;
  }

  public String getPreferredCurrencyCode() {
    return preferredCurrencyCode;
  }

  public Long getPromotionalCredits() {
    return promotionalCredits;
  }

  public Long getUnbilledCharges() {
    return unbilledCharges;
  }

  public Long getRefundableCredits() {
    return refundableCredits;
  }

  public Long getExcessPayments() {
    return excessPayments;
  }

  public Boolean getIsEinvoiceEnabled() {
    return isEinvoiceEnabled;
  }

  public EinvoicingMethod getEinvoicingMethod() {
    return einvoicingMethod;
  }

  public Object getMetaData() {
    return metaData;
  }

  public Boolean getDeleted() {
    return deleted;
  }

  public Boolean getRegisteredForGst() {
    return registeredForGst;
  }

  public Boolean getConsolidatedInvoicing() {
    return consolidatedInvoicing;
  }

  public CustomerType getCustomerType() {
    return customerType;
  }

  public Boolean getBusinessCustomerWithoutVatNumber() {
    return businessCustomerWithoutVatNumber;
  }

  public String getClientProfileId() {
    return clientProfileId;
  }

  public Boolean getUseDefaultHierarchySettings() {
    return useDefaultHierarchySettings;
  }

  public String getVatNumberPrefix() {
    return vatNumberPrefix;
  }

  public String getEntityIdentifierScheme() {
    return entityIdentifierScheme;
  }

  public String getEntityIdentifierStandard() {
    return entityIdentifierStandard;
  }

  public BillingAddress getBillingAddress() {
    return billingAddress;
  }

  public List<ReferralUrls> getReferralUrls() {
    return referralUrls;
  }

  public List<Contacts> getContacts() {
    return contacts;
  }

  public PaymentMethod getPaymentMethod() {
    return paymentMethod;
  }

  public List<Balances> getBalances() {
    return balances;
  }

  public List<EntityIdentifiers> getEntityIdentifiers() {
    return entityIdentifiers;
  }

  public List<TaxProvidersFields> getTaxProvidersFields() {
    return taxProvidersFields;
  }

  public Relationship getRelationship() {
    return relationship;
  }

  public ParentAccountAccess getParentAccountAccess() {
    return parentAccountAccess;
  }

  public ChildAccountAccess getChildAccountAccess() {
    return childAccountAccess;
  }

  public enum AutoCollection {
    On("on"),

    Off("off"),

    /** An enum member indicating that AutoCollection was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    AutoCollection(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static AutoCollection fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (AutoCollection enumValue : AutoCollection.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum OfflinePaymentMethod {
    NoPreference("no_preference"),

    Cash("cash"),

    Check("check"),

    BankTransfer("bank_transfer"),

    AchCredit("ach_credit"),

    SepaCredit("sepa_credit"),

    Boleto("boleto"),

    UsAutomatedBankTransfer("us_automated_bank_transfer"),

    EuAutomatedBankTransfer("eu_automated_bank_transfer"),

    UkAutomatedBankTransfer("uk_automated_bank_transfer"),

    JpAutomatedBankTransfer("jp_automated_bank_transfer"),

    MxAutomatedBankTransfer("mx_automated_bank_transfer"),

    Custom("custom"),

    /**
     * An enum member indicating that OfflinePaymentMethod was instantiated with an unknown value.
     */
    _UNKNOWN(null);
    private final String value;

    OfflinePaymentMethod(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static OfflinePaymentMethod fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (OfflinePaymentMethod enumValue : OfflinePaymentMethod.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum VatNumberStatus {
    Valid("valid"),

    Invalid("invalid"),

    NotValidated("not_validated"),

    Undetermined("undetermined"),

    /** An enum member indicating that VatNumberStatus was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    VatNumberStatus(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static VatNumberStatus fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (VatNumberStatus enumValue : VatNumberStatus.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum Taxability {
    Taxable("taxable"),

    Exempt("exempt"),

    /** An enum member indicating that Taxability was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Taxability(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Taxability fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Taxability enumValue : Taxability.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum EntityCode {
    A("a"),

    B("b"),

    C("c"),

    D("d"),

    E("e"),

    F("f"),

    G("g"),

    H("h"),

    I("i"),

    J("j"),

    K("k"),

    L("l"),

    M("m"),

    N("n"),

    P("p"),

    Q("q"),

    R("r"),

    Med1("med1"),

    Med2("med2"),

    /** An enum member indicating that EntityCode was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    EntityCode(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static EntityCode fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (EntityCode enumValue : EntityCode.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum BillingDateMode {
    UsingDefaults("using_defaults"),

    ManuallySet("manually_set"),

    /** An enum member indicating that BillingDateMode was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    BillingDateMode(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static BillingDateMode fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (BillingDateMode enumValue : BillingDateMode.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum BillingDayOfWeek {
    Sunday("sunday"),

    Monday("monday"),

    Tuesday("tuesday"),

    Wednesday("wednesday"),

    Thursday("thursday"),

    Friday("friday"),

    Saturday("saturday"),

    /** An enum member indicating that BillingDayOfWeek was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    BillingDayOfWeek(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static BillingDayOfWeek fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (BillingDayOfWeek enumValue : BillingDayOfWeek.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum BillingDayOfWeekMode {
    UsingDefaults("using_defaults"),

    ManuallySet("manually_set"),

    /**
     * An enum member indicating that BillingDayOfWeekMode was instantiated with an unknown value.
     */
    _UNKNOWN(null);
    private final String value;

    BillingDayOfWeekMode(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static BillingDayOfWeekMode fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (BillingDayOfWeekMode enumValue : BillingDayOfWeekMode.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum PiiCleared {
    Active("active"),

    ScheduledForClear("scheduled_for_clear"),

    Cleared("cleared"),

    /** An enum member indicating that PiiCleared was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    PiiCleared(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static PiiCleared fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (PiiCleared enumValue : PiiCleared.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum Channel {
    Web("web"),

    AppStore("app_store"),

    PlayStore("play_store"),

    /** An enum member indicating that Channel was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Channel(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Channel fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Channel enumValue : Channel.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum CardStatus {
    NoCard("no_card"),

    Valid("valid"),

    Expiring("expiring"),

    Expired("expired"),

    PendingVerification("pending_verification"),

    Invalid("invalid"),

    /** An enum member indicating that CardStatus was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    CardStatus(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static CardStatus fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (CardStatus enumValue : CardStatus.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum FraudFlag {
    Safe("safe"),

    Suspicious("suspicious"),

    Fraudulent("fraudulent"),

    /** An enum member indicating that FraudFlag was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    FraudFlag(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static FraudFlag fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (FraudFlag enumValue : FraudFlag.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum EinvoicingMethod {
    Automatic("automatic"),

    Manual("manual"),

    SiteDefault("site_default"),

    /** An enum member indicating that EinvoicingMethod was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    EinvoicingMethod(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static EinvoicingMethod fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (EinvoicingMethod enumValue : EinvoicingMethod.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum CustomerType {
    Residential("residential"),

    Business("business"),

    SeniorCitizen("senior_citizen"),

    Industrial("industrial"),

    /** An enum member indicating that CustomerType was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    CustomerType(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static CustomerType fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (CustomerType enumValue : CustomerType.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static Customer fromJson(String json) {
    Customer obj = new Customer();

    obj.id = JsonUtil.getString(json, "id");

    obj.firstName = JsonUtil.getString(json, "first_name");

    obj.lastName = JsonUtil.getString(json, "last_name");

    obj.email = JsonUtil.getString(json, "email");

    obj.phone = JsonUtil.getString(json, "phone");

    obj.company = JsonUtil.getString(json, "company");

    obj.vatNumber = JsonUtil.getString(json, "vat_number");

    obj.autoCollection = AutoCollection.fromString(JsonUtil.getString(json, "auto_collection"));

    obj.offlinePaymentMethod =
        OfflinePaymentMethod.fromString(JsonUtil.getString(json, "offline_payment_method"));

    obj.netTermDays = JsonUtil.getInteger(json, "net_term_days");

    obj.vatNumberValidatedTime = JsonUtil.getTimestamp(json, "vat_number_validated_time");

    obj.vatNumberStatus = VatNumberStatus.fromString(JsonUtil.getString(json, "vat_number_status"));

    obj.allowDirectDebit = JsonUtil.getBoolean(json, "allow_direct_debit");

    obj.isLocationValid = JsonUtil.getBoolean(json, "is_location_valid");

    obj.createdAt = JsonUtil.getTimestamp(json, "created_at");

    obj.createdFromIp = JsonUtil.getString(json, "created_from_ip");

    obj.exemptionDetails =
        JsonUtil.parseArrayOfString(JsonUtil.getArray(json, "exemption_details"));

    obj.taxability = Taxability.fromString(JsonUtil.getString(json, "taxability"));

    obj.entityCode = EntityCode.fromString(JsonUtil.getString(json, "entity_code"));

    obj.exemptNumber = JsonUtil.getString(json, "exempt_number");

    obj.resourceVersion = JsonUtil.getLong(json, "resource_version");

    obj.updatedAt = JsonUtil.getTimestamp(json, "updated_at");

    obj.locale = JsonUtil.getString(json, "locale");

    obj.billingDate = JsonUtil.getInteger(json, "billing_date");

    obj.billingMonth = JsonUtil.getInteger(json, "billing_month");

    obj.billingDateMode = BillingDateMode.fromString(JsonUtil.getString(json, "billing_date_mode"));

    obj.billingDayOfWeek =
        BillingDayOfWeek.fromString(JsonUtil.getString(json, "billing_day_of_week"));

    obj.billingDayOfWeekMode =
        BillingDayOfWeekMode.fromString(JsonUtil.getString(json, "billing_day_of_week_mode"));

    obj.piiCleared = PiiCleared.fromString(JsonUtil.getString(json, "pii_cleared"));

    obj.autoCloseInvoices = JsonUtil.getBoolean(json, "auto_close_invoices");

    obj.channel = Channel.fromString(JsonUtil.getString(json, "channel"));

    obj.activeId = JsonUtil.getString(json, "active_id");

    obj.cardStatus = CardStatus.fromString(JsonUtil.getString(json, "card_status"));

    obj.fraudFlag = FraudFlag.fromString(JsonUtil.getString(json, "fraud_flag"));

    obj.primaryPaymentSourceId = JsonUtil.getString(json, "primary_payment_source_id");

    obj.backupPaymentSourceId = JsonUtil.getString(json, "backup_payment_source_id");

    obj.invoiceNotes = JsonUtil.getString(json, "invoice_notes");

    obj.businessEntityId = JsonUtil.getString(json, "business_entity_id");

    obj.preferredCurrencyCode = JsonUtil.getString(json, "preferred_currency_code");

    obj.promotionalCredits = JsonUtil.getLong(json, "promotional_credits");

    obj.unbilledCharges = JsonUtil.getLong(json, "unbilled_charges");

    obj.refundableCredits = JsonUtil.getLong(json, "refundable_credits");

    obj.excessPayments = JsonUtil.getLong(json, "excess_payments");

    obj.isEinvoiceEnabled = JsonUtil.getBoolean(json, "is_einvoice_enabled");

    obj.einvoicingMethod =
        EinvoicingMethod.fromString(JsonUtil.getString(json, "einvoicing_method"));

    obj.metaData = JsonUtil.getObject(json, "meta_data");

    obj.deleted = JsonUtil.getBoolean(json, "deleted");

    obj.registeredForGst = JsonUtil.getBoolean(json, "registered_for_gst");

    obj.consolidatedInvoicing = JsonUtil.getBoolean(json, "consolidated_invoicing");

    obj.customerType = CustomerType.fromString(JsonUtil.getString(json, "customer_type"));

    obj.businessCustomerWithoutVatNumber =
        JsonUtil.getBoolean(json, "business_customer_without_vat_number");

    obj.clientProfileId = JsonUtil.getString(json, "client_profile_id");

    obj.useDefaultHierarchySettings = JsonUtil.getBoolean(json, "use_default_hierarchy_settings");

    obj.vatNumberPrefix = JsonUtil.getString(json, "vat_number_prefix");

    obj.entityIdentifierScheme = JsonUtil.getString(json, "entity_identifier_scheme");

    obj.entityIdentifierStandard = JsonUtil.getString(json, "entity_identifier_standard");

    String __billingAddressJson = JsonUtil.getObject(json, "billing_address");
    if (__billingAddressJson != null) {
      obj.billingAddress = BillingAddress.fromJson(__billingAddressJson);
    }

    obj.referralUrls =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "referral_urls")).stream()
            .map(ReferralUrls::fromJson)
            .collect(java.util.stream.Collectors.toList());

    obj.contacts =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "contacts")).stream()
            .map(Contacts::fromJson)
            .collect(java.util.stream.Collectors.toList());

    String __paymentMethodJson = JsonUtil.getObject(json, "payment_method");
    if (__paymentMethodJson != null) {
      obj.paymentMethod = PaymentMethod.fromJson(__paymentMethodJson);
    }

    obj.balances =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "balances")).stream()
            .map(Balances::fromJson)
            .collect(java.util.stream.Collectors.toList());

    obj.entityIdentifiers =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "entity_identifiers")).stream()
            .map(EntityIdentifiers::fromJson)
            .collect(java.util.stream.Collectors.toList());

    obj.taxProvidersFields =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "tax_providers_fields")).stream()
            .map(TaxProvidersFields::fromJson)
            .collect(java.util.stream.Collectors.toList());

    String __relationshipJson = JsonUtil.getObject(json, "relationship");
    if (__relationshipJson != null) {
      obj.relationship = Relationship.fromJson(__relationshipJson);
    }

    String __parentAccountAccessJson = JsonUtil.getObject(json, "parent_account_access");
    if (__parentAccountAccessJson != null) {
      obj.parentAccountAccess = ParentAccountAccess.fromJson(__parentAccountAccessJson);
    }

    String __childAccountAccessJson = JsonUtil.getObject(json, "child_account_access");
    if (__childAccountAccessJson != null) {
      obj.childAccountAccess = ChildAccountAccess.fromJson(__childAccountAccessJson);
    }

    return obj;
  }

  public static class BillingAddress {

    private String firstName;
    private String lastName;
    private String email;
    private String company;
    private String phone;
    private String line1;
    private String line2;
    private String line3;
    private String city;
    private String stateCode;
    private String state;
    private String country;
    private String zip;
    private ValidationStatus validationStatus;

    public String getFirstName() {
      return firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public String getEmail() {
      return email;
    }

    public String getCompany() {
      return company;
    }

    public String getPhone() {
      return phone;
    }

    public String getLine1() {
      return line1;
    }

    public String getLine2() {
      return line2;
    }

    public String getLine3() {
      return line3;
    }

    public String getCity() {
      return city;
    }

    public String getStateCode() {
      return stateCode;
    }

    public String getState() {
      return state;
    }

    public String getCountry() {
      return country;
    }

    public String getZip() {
      return zip;
    }

    public ValidationStatus getValidationStatus() {
      return validationStatus;
    }

    public enum ValidationStatus {
      NotValidated("not_validated"),

      Valid("valid"),

      PartiallyValid("partially_valid"),

      Invalid("invalid"),

      /** An enum member indicating that ValidationStatus was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ValidationStatus(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ValidationStatus fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ValidationStatus enumValue : ValidationStatus.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static BillingAddress fromJson(String json) {
      BillingAddress obj = new BillingAddress();

      obj.firstName = JsonUtil.getString(json, "first_name");

      obj.lastName = JsonUtil.getString(json, "last_name");

      obj.email = JsonUtil.getString(json, "email");

      obj.company = JsonUtil.getString(json, "company");

      obj.phone = JsonUtil.getString(json, "phone");

      obj.line1 = JsonUtil.getString(json, "line1");

      obj.line2 = JsonUtil.getString(json, "line2");

      obj.line3 = JsonUtil.getString(json, "line3");

      obj.city = JsonUtil.getString(json, "city");

      obj.stateCode = JsonUtil.getString(json, "state_code");

      obj.state = JsonUtil.getString(json, "state");

      obj.country = JsonUtil.getString(json, "country");

      obj.zip = JsonUtil.getString(json, "zip");

      obj.validationStatus =
          ValidationStatus.fromString(JsonUtil.getString(json, "validation_status"));

      return obj;
    }
  }

  public static class ReferralUrls {

    private String externalCustomerId;
    private String referralSharingUrl;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private String referralCampaignId;
    private String referralAccountId;
    private String referralExternalCampaignId;
    private ReferralSystem referralSystem;

    public String getExternalCustomerId() {
      return externalCustomerId;
    }

    public String getReferralSharingUrl() {
      return referralSharingUrl;
    }

    public Timestamp getCreatedAt() {
      return createdAt;
    }

    public Timestamp getUpdatedAt() {
      return updatedAt;
    }

    public String getReferralCampaignId() {
      return referralCampaignId;
    }

    public String getReferralAccountId() {
      return referralAccountId;
    }

    public String getReferralExternalCampaignId() {
      return referralExternalCampaignId;
    }

    public ReferralSystem getReferralSystem() {
      return referralSystem;
    }

    public enum ReferralSystem {
      ReferralCandy("referral_candy"),

      ReferralSaasquatch("referral_saasquatch"),

      Friendbuy("friendbuy"),

      /** An enum member indicating that ReferralSystem was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ReferralSystem(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ReferralSystem fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ReferralSystem enumValue : ReferralSystem.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static ReferralUrls fromJson(String json) {
      ReferralUrls obj = new ReferralUrls();

      obj.externalCustomerId = JsonUtil.getString(json, "external_customer_id");

      obj.referralSharingUrl = JsonUtil.getString(json, "referral_sharing_url");

      obj.createdAt = JsonUtil.getTimestamp(json, "created_at");

      obj.updatedAt = JsonUtil.getTimestamp(json, "updated_at");

      obj.referralCampaignId = JsonUtil.getString(json, "referral_campaign_id");

      obj.referralAccountId = JsonUtil.getString(json, "referral_account_id");

      obj.referralExternalCampaignId = JsonUtil.getString(json, "referral_external_campaign_id");

      obj.referralSystem = ReferralSystem.fromString(JsonUtil.getString(json, "referral_system"));

      return obj;
    }
  }

  public static class Contacts {

    private String id;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String label;
    private Boolean enabled;
    private Boolean sendAccountEmail;
    private Boolean sendBillingEmail;

    public String getId() {
      return id;
    }

    public String getFirstName() {
      return firstName;
    }

    public String getLastName() {
      return lastName;
    }

    public String getEmail() {
      return email;
    }

    public String getPhone() {
      return phone;
    }

    public String getLabel() {
      return label;
    }

    public Boolean getEnabled() {
      return enabled;
    }

    public Boolean getSendAccountEmail() {
      return sendAccountEmail;
    }

    public Boolean getSendBillingEmail() {
      return sendBillingEmail;
    }

    public static Contacts fromJson(String json) {
      Contacts obj = new Contacts();

      obj.id = JsonUtil.getString(json, "id");

      obj.firstName = JsonUtil.getString(json, "first_name");

      obj.lastName = JsonUtil.getString(json, "last_name");

      obj.email = JsonUtil.getString(json, "email");

      obj.phone = JsonUtil.getString(json, "phone");

      obj.label = JsonUtil.getString(json, "label");

      obj.enabled = JsonUtil.getBoolean(json, "enabled");

      obj.sendAccountEmail = JsonUtil.getBoolean(json, "send_account_email");

      obj.sendBillingEmail = JsonUtil.getBoolean(json, "send_billing_email");

      return obj;
    }
  }

  public static class PaymentMethod {

    private Type type;
    private Gateway gateway;
    private String gatewayAccountId;
    private Status status;
    private String referenceId;

    public Type getType() {
      return type;
    }

    public Gateway getGateway() {
      return gateway;
    }

    public String getGatewayAccountId() {
      return gatewayAccountId;
    }

    public Status getStatus() {
      return status;
    }

    public String getReferenceId() {
      return referenceId;
    }

    public enum Type {
      Card("card"),

      PaypalExpressCheckout("paypal_express_checkout"),

      AmazonPayments("amazon_payments"),

      DirectDebit("direct_debit"),

      Generic("generic"),

      Alipay("alipay"),

      Unionpay("unionpay"),

      ApplePay("apple_pay"),

      WechatPay("wechat_pay"),

      Ideal("ideal"),

      GooglePay("google_pay"),

      Sofort("sofort"),

      Bancontact("bancontact"),

      Giropay("giropay"),

      Dotpay("dotpay"),

      Upi("upi"),

      NetbankingEmandates("netbanking_emandates"),

      Venmo("venmo"),

      PayTo("pay_to"),

      FasterPayments("faster_payments"),

      SepaInstantTransfer("sepa_instant_transfer"),

      AutomatedBankTransfer("automated_bank_transfer"),

      KlarnaPayNow("klarna_pay_now"),

      OnlineBankingPoland("online_banking_poland"),

      PayconiqByBancontact("payconiq_by_bancontact"),

      /** An enum member indicating that Type was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      Type(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static Type fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (Type enumValue : Type.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum Gateway {
      Chargebee("chargebee"),

      ChargebeePayments("chargebee_payments"),

      Adyen("adyen"),

      Stripe("stripe"),

      Wepay("wepay"),

      Braintree("braintree"),

      AuthorizeNet("authorize_net"),

      PaypalPro("paypal_pro"),

      Pin("pin"),

      Eway("eway"),

      EwayRapid("eway_rapid"),

      Worldpay("worldpay"),

      BalancedPayments("balanced_payments"),

      Beanstream("beanstream"),

      Bluepay("bluepay"),

      Elavon("elavon"),

      FirstDataGlobal("first_data_global"),

      Hdfc("hdfc"),

      Migs("migs"),

      Nmi("nmi"),

      Ogone("ogone"),

      Paymill("paymill"),

      PaypalPayflowPro("paypal_payflow_pro"),

      SagePay("sage_pay"),

      Tco("tco"),

      Wirecard("wirecard"),

      AmazonPayments("amazon_payments"),

      PaypalExpressCheckout("paypal_express_checkout"),

      Gocardless("gocardless"),

      Orbital("orbital"),

      MonerisUs("moneris_us"),

      Moneris("moneris"),

      Bluesnap("bluesnap"),

      Cybersource("cybersource"),

      Vantiv("vantiv"),

      CheckoutCom("checkout_com"),

      Paypal("paypal"),

      IngenicoDirect("ingenico_direct"),

      Exact("exact"),

      Mollie("mollie"),

      Quickbooks("quickbooks"),

      Razorpay("razorpay"),

      GlobalPayments("global_payments"),

      BankOfAmerica("bank_of_america"),

      Ecentric("ecentric"),

      MetricsGlobal("metrics_global"),

      Windcave("windcave"),

      PayCom("pay_com"),

      Ebanx("ebanx"),

      Dlocal("dlocal"),

      Nuvei("nuvei"),

      Solidgate("solidgate"),

      Paystack("paystack"),

      JpMorgan("jp_morgan"),

      NotApplicable("not_applicable"),

      /** An enum member indicating that Gateway was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      Gateway(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static Gateway fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (Gateway enumValue : Gateway.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum Status {
      Valid("valid"),

      Expiring("expiring"),

      Expired("expired"),

      Invalid("invalid"),

      PendingVerification("pending_verification"),

      /** An enum member indicating that Status was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      Status(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static Status fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (Status enumValue : Status.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static PaymentMethod fromJson(String json) {
      PaymentMethod obj = new PaymentMethod();

      obj.type = Type.fromString(JsonUtil.getString(json, "type"));

      obj.gateway = Gateway.fromString(JsonUtil.getString(json, "gateway"));

      obj.gatewayAccountId = JsonUtil.getString(json, "gateway_account_id");

      obj.status = Status.fromString(JsonUtil.getString(json, "status"));

      obj.referenceId = JsonUtil.getString(json, "reference_id");

      return obj;
    }
  }

  public static class Balances {

    private Long promotionalCredits;
    private Long excessPayments;
    private Long refundableCredits;
    private Long unbilledCharges;
    private String currencyCode;
    private String balanceCurrencyCode;
    private String businessEntityId;

    public Long getPromotionalCredits() {
      return promotionalCredits;
    }

    public Long getExcessPayments() {
      return excessPayments;
    }

    public Long getRefundableCredits() {
      return refundableCredits;
    }

    public Long getUnbilledCharges() {
      return unbilledCharges;
    }

    public String getCurrencyCode() {
      return currencyCode;
    }

    public String getBalanceCurrencyCode() {
      return balanceCurrencyCode;
    }

    public String getBusinessEntityId() {
      return businessEntityId;
    }

    public static Balances fromJson(String json) {
      Balances obj = new Balances();

      obj.promotionalCredits = JsonUtil.getLong(json, "promotional_credits");

      obj.excessPayments = JsonUtil.getLong(json, "excess_payments");

      obj.refundableCredits = JsonUtil.getLong(json, "refundable_credits");

      obj.unbilledCharges = JsonUtil.getLong(json, "unbilled_charges");

      obj.currencyCode = JsonUtil.getString(json, "currency_code");

      obj.balanceCurrencyCode = JsonUtil.getString(json, "balance_currency_code");

      obj.businessEntityId = JsonUtil.getString(json, "business_entity_id");

      return obj;
    }
  }

  public static class EntityIdentifiers {

    private String id;
    private String value;
    private String scheme;
    private String standard;

    public String getId() {
      return id;
    }

    public String getValue() {
      return value;
    }

    public String getScheme() {
      return scheme;
    }

    public String getStandard() {
      return standard;
    }

    public static EntityIdentifiers fromJson(String json) {
      EntityIdentifiers obj = new EntityIdentifiers();

      obj.id = JsonUtil.getString(json, "id");

      obj.value = JsonUtil.getString(json, "value");

      obj.scheme = JsonUtil.getString(json, "scheme");

      obj.standard = JsonUtil.getString(json, "standard");

      return obj;
    }
  }

  public static class TaxProvidersFields {

    private String providerName;
    private String fieldId;
    private String fieldValue;

    public String getProviderName() {
      return providerName;
    }

    public String getFieldId() {
      return fieldId;
    }

    public String getFieldValue() {
      return fieldValue;
    }

    public static TaxProvidersFields fromJson(String json) {
      TaxProvidersFields obj = new TaxProvidersFields();

      obj.providerName = JsonUtil.getString(json, "provider_name");

      obj.fieldId = JsonUtil.getString(json, "field_id");

      obj.fieldValue = JsonUtil.getString(json, "field_value");

      return obj;
    }
  }

  public static class Relationship {

    private String parentId;
    private String paymentOwnerId;
    private String invoiceOwnerId;

    public String getParentId() {
      return parentId;
    }

    public String getPaymentOwnerId() {
      return paymentOwnerId;
    }

    public String getInvoiceOwnerId() {
      return invoiceOwnerId;
    }

    public static Relationship fromJson(String json) {
      Relationship obj = new Relationship();

      obj.parentId = JsonUtil.getString(json, "parent_id");

      obj.paymentOwnerId = JsonUtil.getString(json, "payment_owner_id");

      obj.invoiceOwnerId = JsonUtil.getString(json, "invoice_owner_id");

      return obj;
    }
  }

  public static class ParentAccountAccess {

    private PortalEditChildSubscriptions portalEditChildSubscriptions;
    private PortalDownloadChildInvoices portalDownloadChildInvoices;
    private Boolean sendSubscriptionEmails;
    private Boolean sendInvoiceEmails;
    private Boolean sendPaymentEmails;

    public PortalEditChildSubscriptions getPortalEditChildSubscriptions() {
      return portalEditChildSubscriptions;
    }

    public PortalDownloadChildInvoices getPortalDownloadChildInvoices() {
      return portalDownloadChildInvoices;
    }

    public Boolean getSendSubscriptionEmails() {
      return sendSubscriptionEmails;
    }

    public Boolean getSendInvoiceEmails() {
      return sendInvoiceEmails;
    }

    public Boolean getSendPaymentEmails() {
      return sendPaymentEmails;
    }

    public enum PortalEditChildSubscriptions {
      Yes("yes"),

      ViewOnly("view_only"),

      No("no"),

      /**
       * An enum member indicating that PortalEditChildSubscriptions was instantiated with an
       * unknown value.
       */
      _UNKNOWN(null);
      private final String value;

      PortalEditChildSubscriptions(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PortalEditChildSubscriptions fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PortalEditChildSubscriptions enumValue : PortalEditChildSubscriptions.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum PortalDownloadChildInvoices {
      Yes("yes"),

      ViewOnly("view_only"),

      No("no"),

      /**
       * An enum member indicating that PortalDownloadChildInvoices was instantiated with an unknown
       * value.
       */
      _UNKNOWN(null);
      private final String value;

      PortalDownloadChildInvoices(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PortalDownloadChildInvoices fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PortalDownloadChildInvoices enumValue : PortalDownloadChildInvoices.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static ParentAccountAccess fromJson(String json) {
      ParentAccountAccess obj = new ParentAccountAccess();

      obj.portalEditChildSubscriptions =
          PortalEditChildSubscriptions.fromString(
              JsonUtil.getString(json, "portal_edit_child_subscriptions"));

      obj.portalDownloadChildInvoices =
          PortalDownloadChildInvoices.fromString(
              JsonUtil.getString(json, "portal_download_child_invoices"));

      obj.sendSubscriptionEmails = JsonUtil.getBoolean(json, "send_subscription_emails");

      obj.sendInvoiceEmails = JsonUtil.getBoolean(json, "send_invoice_emails");

      obj.sendPaymentEmails = JsonUtil.getBoolean(json, "send_payment_emails");

      return obj;
    }
  }

  public static class ChildAccountAccess {

    private PortalEditSubscriptions portalEditSubscriptions;
    private PortalDownloadInvoices portalDownloadInvoices;
    private Boolean sendSubscriptionEmails;
    private Boolean sendInvoiceEmails;
    private Boolean sendPaymentEmails;

    public PortalEditSubscriptions getPortalEditSubscriptions() {
      return portalEditSubscriptions;
    }

    public PortalDownloadInvoices getPortalDownloadInvoices() {
      return portalDownloadInvoices;
    }

    public Boolean getSendSubscriptionEmails() {
      return sendSubscriptionEmails;
    }

    public Boolean getSendInvoiceEmails() {
      return sendInvoiceEmails;
    }

    public Boolean getSendPaymentEmails() {
      return sendPaymentEmails;
    }

    public enum PortalEditSubscriptions {
      Yes("yes"),

      ViewOnly("view_only"),

      /**
       * An enum member indicating that PortalEditSubscriptions was instantiated with an unknown
       * value.
       */
      _UNKNOWN(null);
      private final String value;

      PortalEditSubscriptions(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PortalEditSubscriptions fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PortalEditSubscriptions enumValue : PortalEditSubscriptions.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum PortalDownloadInvoices {
      Yes("yes"),

      ViewOnly("view_only"),

      No("no"),

      /**
       * An enum member indicating that PortalDownloadInvoices was instantiated with an unknown
       * value.
       */
      _UNKNOWN(null);
      private final String value;

      PortalDownloadInvoices(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PortalDownloadInvoices fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PortalDownloadInvoices enumValue : PortalDownloadInvoices.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static ChildAccountAccess fromJson(String json) {
      ChildAccountAccess obj = new ChildAccountAccess();

      obj.portalEditSubscriptions =
          PortalEditSubscriptions.fromString(JsonUtil.getString(json, "portal_edit_subscriptions"));

      obj.portalDownloadInvoices =
          PortalDownloadInvoices.fromString(JsonUtil.getString(json, "portal_download_invoices"));

      obj.sendSubscriptionEmails = JsonUtil.getBoolean(json, "send_subscription_emails");

      obj.sendInvoiceEmails = JsonUtil.getBoolean(json, "send_invoice_emails");

      obj.sendPaymentEmails = JsonUtil.getBoolean(json, "send_payment_emails");

      return obj;
    }
  }
}
