/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.core.models.thirdPartyEntityMapping.params;

import com.chargebee.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class ThirdPartyEntityMappingUpdateEntityParams {

  private final Map<String, Object> formData;

  private ThirdPartyEntityMappingUpdateEntityParams(
      ThirdPartyEntityMappingUpdateEntityBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for ThirdPartyEntityMappingUpdateEntityParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static ThirdPartyEntityMappingUpdateEntityBuilder builder() {
    return new ThirdPartyEntityMappingUpdateEntityBuilder();
  }

  public static final class ThirdPartyEntityMappingUpdateEntityBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private ThirdPartyEntityMappingUpdateEntityBuilder() {}

    public ThirdPartyEntityMappingUpdateEntityBuilder entityType(EntityType value) {
      formData.put("entity_type", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder entityId(String value) {
      formData.put("entity_id", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder thirdPartyEntityId(String value) {
      formData.put("third_party_entity_id", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder integrationName(String value) {
      formData.put("integration_name", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder status(Status value) {
      formData.put("status", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder oldResource(Object value) {
      formData.put("old_resource", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder mappingMeta(Object value) {
      formData.put("mapping_meta", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder failedDependentEntityId(String value) {
      formData.put("failed_dependent_entity_id", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder failedDependentEntityType(
        FailedDependentEntityType value) {
      formData.put("failed_dependent_entity_type", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder errorMessage(String value) {
      formData.put("error_message", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityBuilder url(String value) {
      formData.put("url", value);
      return this;
    }

    public ThirdPartyEntityMappingUpdateEntityParams build() {
      return new ThirdPartyEntityMappingUpdateEntityParams(this);
    }

    public enum EntityType {
      Customer("customer"),

      Invoice("invoice"),

      CreditNote("credit_note"),

      Transaction("transaction"),

      Plan("plan"),

      Addon("addon"),

      Coupon("coupon"),

      Subscription("subscription"),

      Order("order"),

      Quote("quote"),

      ItemFamily("item_family"),

      Item("item"),

      ItemPrice("item_price"),

      TaxRate("tax_rate"),

      TaxGroup("tax_group"),

      /** An enum member indicating that EntityType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      EntityType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static EntityType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (EntityType enumValue : EntityType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum Status {
      Synced("synced"),

      PartiallySynced("partially_synced"),

      CreateFailed("create_failed"),

      UpdateFailed("update_failed"),

      Stopped("stopped"),

      Ignored("ignored"),

      ToBePicked("to_be_picked"),

      ForceSync("force_sync"),

      Mismatch("mismatch"),

      Deleted("deleted"),

      Queued("queued"),

      DeleteFailed("delete_failed"),

      DeleteSuccess("delete_success"),

      /** An enum member indicating that Status was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      Status(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static Status fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (Status enumValue : Status.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public enum FailedDependentEntityType {
      Customer("customer"),

      Invoice("invoice"),

      CreditNote("credit_note"),

      Transaction("transaction"),

      Plan("plan"),

      Addon("addon"),

      Coupon("coupon"),

      Subscription("subscription"),

      Order("order"),

      Quote("quote"),

      ItemFamily("item_family"),

      Item("item"),

      ItemPrice("item_price"),

      TaxRate("tax_rate"),

      TaxGroup("tax_group"),

      /**
       * An enum member indicating that FailedDependentEntityType was instantiated with an unknown
       * value.
       */
      _UNKNOWN(null);
      private final String value;

      FailedDependentEntityType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static FailedDependentEntityType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (FailedDependentEntityType enumValue : FailedDependentEntityType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }
  }
}
