/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.timeMachine;

import com.chargebee.v4.internal.JsonUtil;
import java.sql.Timestamp;

public class TimeMachine {

  private String name;
  private TimeTravelStatus timeTravelStatus;
  private Timestamp genesisTime;
  private Timestamp destinationTime;
  private String failureCode;
  private String failureReason;
  private String errorJson;

  public String getName() {
    return name;
  }

  public TimeTravelStatus getTimeTravelStatus() {
    return timeTravelStatus;
  }

  public Timestamp getGenesisTime() {
    return genesisTime;
  }

  public Timestamp getDestinationTime() {
    return destinationTime;
  }

  public String getFailureCode() {
    return failureCode;
  }

  public String getFailureReason() {
    return failureReason;
  }

  public String getErrorJson() {
    return errorJson;
  }

  public enum TimeTravelStatus {
    NOT_ENABLED("not_enabled"),

    IN_PROGRESS("in_progress"),

    SUCCEEDED("succeeded"),

    FAILED("failed"),

    /** An enum member indicating that TimeTravelStatus was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    TimeTravelStatus(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static TimeTravelStatus fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (TimeTravelStatus enumValue : TimeTravelStatus.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static TimeMachine fromJson(String json) {
    TimeMachine obj = new TimeMachine();

    obj.name = JsonUtil.getString(json, "name");

    obj.timeTravelStatus =
        TimeTravelStatus.fromString(JsonUtil.getString(json, "time_travel_status"));

    obj.genesisTime = JsonUtil.getTimestamp(json, "genesis_time");

    obj.destinationTime = JsonUtil.getTimestamp(json, "destination_time");

    obj.failureCode = JsonUtil.getString(json, "failure_code");

    obj.failureReason = JsonUtil.getString(json, "failure_reason");

    obj.errorJson = JsonUtil.getString(json, "error_json");

    return obj;
  }
}
