/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.quotedCharge;

import com.chargebee.v4.internal.JsonUtil;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.util.List;

public class QuotedCharge {

  private List<Charges> charges;
  private List<InvoiceItems> invoiceItems;
  private List<ItemTiers> itemTiers;
  private List<Coupons> coupons;
  private List<CouponApplicabilityMappings> couponApplicabilityMappings;
  private List<Addons> addons;

  public List<Charges> getCharges() {
    return charges;
  }

  public List<InvoiceItems> getInvoiceItems() {
    return invoiceItems;
  }

  public List<ItemTiers> getItemTiers() {
    return itemTiers;
  }

  public List<Coupons> getCoupons() {
    return coupons;
  }

  public List<CouponApplicabilityMappings> getCouponApplicabilityMappings() {
    return couponApplicabilityMappings;
  }

  public List<Addons> getAddons() {
    return addons;
  }

  public static QuotedCharge fromJson(String json) {
    return fromJson(JsonUtil.parse(json));
  }

  public static QuotedCharge fromJson(java.util.Map<String, Object> map) {
    return fromJson(JsonUtil.toJson(map));
  }

  public static QuotedCharge fromJson(JsonObject jsonObj) {
    QuotedCharge obj = new QuotedCharge();

    obj.charges = JsonUtil.mapArray(JsonUtil.getJsonArray(jsonObj, "charges"), Charges::fromJson);

    obj.invoiceItems =
        JsonUtil.mapArray(JsonUtil.getJsonArray(jsonObj, "invoice_items"), InvoiceItems::fromJson);

    obj.itemTiers =
        JsonUtil.mapArray(JsonUtil.getJsonArray(jsonObj, "item_tiers"), ItemTiers::fromJson);

    obj.coupons = JsonUtil.mapArray(JsonUtil.getJsonArray(jsonObj, "coupons"), Coupons::fromJson);

    obj.couponApplicabilityMappings =
        JsonUtil.mapArray(
            JsonUtil.getJsonArray(jsonObj, "coupon_applicability_mappings"),
            CouponApplicabilityMappings::fromJson);

    obj.addons = JsonUtil.mapArray(JsonUtil.getJsonArray(jsonObj, "addons"), Addons::fromJson);

    return obj;
  }

  @Override
  public String toString() {
    return "QuotedCharge{"
        + "charges="
        + charges
        + ", invoiceItems="
        + invoiceItems
        + ", itemTiers="
        + itemTiers
        + ", coupons="
        + coupons
        + ", couponApplicabilityMappings="
        + couponApplicabilityMappings
        + ", addons="
        + addons
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    QuotedCharge that = (QuotedCharge) o;
    return java.util.Objects.equals(charges, that.charges)
        && java.util.Objects.equals(invoiceItems, that.invoiceItems)
        && java.util.Objects.equals(itemTiers, that.itemTiers)
        && java.util.Objects.equals(coupons, that.coupons)
        && java.util.Objects.equals(couponApplicabilityMappings, that.couponApplicabilityMappings)
        && java.util.Objects.equals(addons, that.addons);
  }

  @Override
  public int hashCode() {

    return java.util.Objects.hash(
        charges, invoiceItems, itemTiers, coupons, couponApplicabilityMappings, addons);
  }

  public static class Charges {

    private Long amount;
    private String amountInDecimal;
    private String description;
    private Integer servicePeriodInDays;
    private AvalaraSaleType avalaraSaleType;
    private Integer avalaraTransactionType;
    private Integer avalaraServiceType;

    public Long getAmount() {
      return amount;
    }

    public String getAmountInDecimal() {
      return amountInDecimal;
    }

    public String getDescription() {
      return description;
    }

    public Integer getServicePeriodInDays() {
      return servicePeriodInDays;
    }

    public AvalaraSaleType getAvalaraSaleType() {
      return avalaraSaleType;
    }

    public Integer getAvalaraTransactionType() {
      return avalaraTransactionType;
    }

    public Integer getAvalaraServiceType() {
      return avalaraServiceType;
    }

    public enum AvalaraSaleType {
      WHOLESALE("wholesale"),

      RETAIL("retail"),

      CONSUMED("consumed"),

      VENDOR_USE("vendor_use"),

      /** An enum member indicating that AvalaraSaleType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      AvalaraSaleType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static AvalaraSaleType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (AvalaraSaleType enumValue : AvalaraSaleType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static Charges fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static Charges fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static Charges fromJson(JsonObject jsonObj) {
      Charges obj = new Charges();

      obj.amount = JsonUtil.getLong(jsonObj, "amount");

      obj.amountInDecimal = JsonUtil.getString(jsonObj, "amount_in_decimal");

      obj.description = JsonUtil.getString(jsonObj, "description");

      obj.servicePeriodInDays = JsonUtil.getInteger(jsonObj, "service_period_in_days");

      obj.avalaraSaleType =
          AvalaraSaleType.fromString(JsonUtil.getString(jsonObj, "avalara_sale_type"));

      obj.avalaraTransactionType = JsonUtil.getInteger(jsonObj, "avalara_transaction_type");

      obj.avalaraServiceType = JsonUtil.getInteger(jsonObj, "avalara_service_type");

      return obj;
    }

    @Override
    public String toString() {
      return "Charges{"
          + "amount="
          + amount
          + ", amountInDecimal="
          + amountInDecimal
          + ", description="
          + description
          + ", servicePeriodInDays="
          + servicePeriodInDays
          + ", avalaraSaleType="
          + avalaraSaleType
          + ", avalaraTransactionType="
          + avalaraTransactionType
          + ", avalaraServiceType="
          + avalaraServiceType
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      Charges that = (Charges) o;
      return java.util.Objects.equals(amount, that.amount)
          && java.util.Objects.equals(amountInDecimal, that.amountInDecimal)
          && java.util.Objects.equals(description, that.description)
          && java.util.Objects.equals(servicePeriodInDays, that.servicePeriodInDays)
          && java.util.Objects.equals(avalaraSaleType, that.avalaraSaleType)
          && java.util.Objects.equals(avalaraTransactionType, that.avalaraTransactionType)
          && java.util.Objects.equals(avalaraServiceType, that.avalaraServiceType);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(
          amount,
          amountInDecimal,
          description,
          servicePeriodInDays,
          avalaraSaleType,
          avalaraTransactionType,
          avalaraServiceType);
    }
  }

  public static class InvoiceItems {

    private String itemPriceId;
    private Integer quantity;
    private String quantityInDecimal;
    private Long unitPrice;
    private String unitPriceInDecimal;
    private Integer servicePeriodDays;

    public String getItemPriceId() {
      return itemPriceId;
    }

    public Integer getQuantity() {
      return quantity;
    }

    public String getQuantityInDecimal() {
      return quantityInDecimal;
    }

    public Long getUnitPrice() {
      return unitPrice;
    }

    public String getUnitPriceInDecimal() {
      return unitPriceInDecimal;
    }

    public Integer getServicePeriodDays() {
      return servicePeriodDays;
    }

    public static InvoiceItems fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static InvoiceItems fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static InvoiceItems fromJson(JsonObject jsonObj) {
      InvoiceItems obj = new InvoiceItems();

      obj.itemPriceId = JsonUtil.getString(jsonObj, "item_price_id");

      obj.quantity = JsonUtil.getInteger(jsonObj, "quantity");

      obj.quantityInDecimal = JsonUtil.getString(jsonObj, "quantity_in_decimal");

      obj.unitPrice = JsonUtil.getLong(jsonObj, "unit_price");

      obj.unitPriceInDecimal = JsonUtil.getString(jsonObj, "unit_price_in_decimal");

      obj.servicePeriodDays = JsonUtil.getInteger(jsonObj, "service_period_days");

      return obj;
    }

    @Override
    public String toString() {
      return "InvoiceItems{"
          + "itemPriceId="
          + itemPriceId
          + ", quantity="
          + quantity
          + ", quantityInDecimal="
          + quantityInDecimal
          + ", unitPrice="
          + unitPrice
          + ", unitPriceInDecimal="
          + unitPriceInDecimal
          + ", servicePeriodDays="
          + servicePeriodDays
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      InvoiceItems that = (InvoiceItems) o;
      return java.util.Objects.equals(itemPriceId, that.itemPriceId)
          && java.util.Objects.equals(quantity, that.quantity)
          && java.util.Objects.equals(quantityInDecimal, that.quantityInDecimal)
          && java.util.Objects.equals(unitPrice, that.unitPrice)
          && java.util.Objects.equals(unitPriceInDecimal, that.unitPriceInDecimal)
          && java.util.Objects.equals(servicePeriodDays, that.servicePeriodDays);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(
          itemPriceId,
          quantity,
          quantityInDecimal,
          unitPrice,
          unitPriceInDecimal,
          servicePeriodDays);
    }
  }

  public static class ItemTiers {

    private String itemPriceId;
    private Integer startingUnit;
    private Integer endingUnit;
    private Long price;
    private String startingUnitInDecimal;
    private String endingUnitInDecimal;
    private String priceInDecimal;
    private PricingType pricingType;
    private Integer packageSize;
    private Integer index;

    public String getItemPriceId() {
      return itemPriceId;
    }

    public Integer getStartingUnit() {
      return startingUnit;
    }

    public Integer getEndingUnit() {
      return endingUnit;
    }

    public Long getPrice() {
      return price;
    }

    public String getStartingUnitInDecimal() {
      return startingUnitInDecimal;
    }

    public String getEndingUnitInDecimal() {
      return endingUnitInDecimal;
    }

    public String getPriceInDecimal() {
      return priceInDecimal;
    }

    public PricingType getPricingType() {
      return pricingType;
    }

    public Integer getPackageSize() {
      return packageSize;
    }

    public Integer getIndex() {
      return index;
    }

    public enum PricingType {
      PER_UNIT("per_unit"),

      FLAT_FEE("flat_fee"),

      PACKAGE("package"),

      /** An enum member indicating that PricingType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      PricingType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static PricingType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (PricingType enumValue : PricingType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static ItemTiers fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static ItemTiers fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static ItemTiers fromJson(JsonObject jsonObj) {
      ItemTiers obj = new ItemTiers();

      obj.itemPriceId = JsonUtil.getString(jsonObj, "item_price_id");

      obj.startingUnit = JsonUtil.getInteger(jsonObj, "starting_unit");

      obj.endingUnit = JsonUtil.getInteger(jsonObj, "ending_unit");

      obj.price = JsonUtil.getLong(jsonObj, "price");

      obj.startingUnitInDecimal = JsonUtil.getString(jsonObj, "starting_unit_in_decimal");

      obj.endingUnitInDecimal = JsonUtil.getString(jsonObj, "ending_unit_in_decimal");

      obj.priceInDecimal = JsonUtil.getString(jsonObj, "price_in_decimal");

      obj.pricingType = PricingType.fromString(JsonUtil.getString(jsonObj, "pricing_type"));

      obj.packageSize = JsonUtil.getInteger(jsonObj, "package_size");

      obj.index = JsonUtil.getInteger(jsonObj, "index");

      return obj;
    }

    @Override
    public String toString() {
      return "ItemTiers{"
          + "itemPriceId="
          + itemPriceId
          + ", startingUnit="
          + startingUnit
          + ", endingUnit="
          + endingUnit
          + ", price="
          + price
          + ", startingUnitInDecimal="
          + startingUnitInDecimal
          + ", endingUnitInDecimal="
          + endingUnitInDecimal
          + ", priceInDecimal="
          + priceInDecimal
          + ", pricingType="
          + pricingType
          + ", packageSize="
          + packageSize
          + ", index="
          + index
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ItemTiers that = (ItemTiers) o;
      return java.util.Objects.equals(itemPriceId, that.itemPriceId)
          && java.util.Objects.equals(startingUnit, that.startingUnit)
          && java.util.Objects.equals(endingUnit, that.endingUnit)
          && java.util.Objects.equals(price, that.price)
          && java.util.Objects.equals(startingUnitInDecimal, that.startingUnitInDecimal)
          && java.util.Objects.equals(endingUnitInDecimal, that.endingUnitInDecimal)
          && java.util.Objects.equals(priceInDecimal, that.priceInDecimal)
          && java.util.Objects.equals(pricingType, that.pricingType)
          && java.util.Objects.equals(packageSize, that.packageSize)
          && java.util.Objects.equals(index, that.index);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(
          itemPriceId,
          startingUnit,
          endingUnit,
          price,
          startingUnitInDecimal,
          endingUnitInDecimal,
          priceInDecimal,
          pricingType,
          packageSize,
          index);
    }
  }

  public static class Coupons {

    private String couponId;

    public String getCouponId() {
      return couponId;
    }

    public static Coupons fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static Coupons fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static Coupons fromJson(JsonObject jsonObj) {
      Coupons obj = new Coupons();

      obj.couponId = JsonUtil.getString(jsonObj, "coupon_id");

      return obj;
    }

    @Override
    public String toString() {
      return "Coupons{" + "couponId=" + couponId + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      Coupons that = (Coupons) o;
      return java.util.Objects.equals(couponId, that.couponId);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(couponId);
    }
  }

  public static class CouponApplicabilityMappings {

    private String couponId;
    private List<String> applicableItemPriceIds;

    public String getCouponId() {
      return couponId;
    }

    public List<String> getApplicableItemPriceIds() {
      return applicableItemPriceIds;
    }

    public static CouponApplicabilityMappings fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static CouponApplicabilityMappings fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static CouponApplicabilityMappings fromJson(JsonObject jsonObj) {
      CouponApplicabilityMappings obj = new CouponApplicabilityMappings();

      obj.couponId = JsonUtil.getString(jsonObj, "coupon_id");

      JsonArray __applicableItemPriceIdsArr =
          JsonUtil.getJsonArray(jsonObj, "applicable_item_price_ids");
      if (__applicableItemPriceIdsArr != null) {
        obj.applicableItemPriceIds = JsonUtil.parseArrayOfString(__applicableItemPriceIdsArr);
      }

      return obj;
    }

    @Override
    public String toString() {
      return "CouponApplicabilityMappings{"
          + "couponId="
          + couponId
          + ", applicableItemPriceIds="
          + applicableItemPriceIds
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      CouponApplicabilityMappings that = (CouponApplicabilityMappings) o;
      return java.util.Objects.equals(couponId, that.couponId)
          && java.util.Objects.equals(applicableItemPriceIds, that.applicableItemPriceIds);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(couponId, applicableItemPriceIds);
    }
  }

  public static class Addons {

    private String id;
    private Integer quantity;
    private Long unitPrice;
    private String quantityInDecimal;
    private String unitPriceInDecimal;
    private ProrationType prorationType;
    private Integer servicePeriod;

    public String getId() {
      return id;
    }

    public Integer getQuantity() {
      return quantity;
    }

    public Long getUnitPrice() {
      return unitPrice;
    }

    public String getQuantityInDecimal() {
      return quantityInDecimal;
    }

    public String getUnitPriceInDecimal() {
      return unitPriceInDecimal;
    }

    public ProrationType getProrationType() {
      return prorationType;
    }

    public Integer getServicePeriod() {
      return servicePeriod;
    }

    public enum ProrationType {
      FULL_TERM("full_term"),

      PARTIAL_TERM("partial_term"),

      NONE("none"),

      /** An enum member indicating that ProrationType was instantiated with an unknown value. */
      _UNKNOWN(null);
      private final String value;

      ProrationType(String value) {
        this.value = value;
      }

      public String getValue() {
        return value;
      }

      public static ProrationType fromString(String value) {
        if (value == null) return _UNKNOWN;
        for (ProrationType enumValue : ProrationType.values()) {
          if (enumValue.value != null && enumValue.value.equals(value)) {
            return enumValue;
          }
        }
        return _UNKNOWN;
      }
    }

    public static Addons fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static Addons fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static Addons fromJson(JsonObject jsonObj) {
      Addons obj = new Addons();

      obj.id = JsonUtil.getString(jsonObj, "id");

      obj.quantity = JsonUtil.getInteger(jsonObj, "quantity");

      obj.unitPrice = JsonUtil.getLong(jsonObj, "unit_price");

      obj.quantityInDecimal = JsonUtil.getString(jsonObj, "quantity_in_decimal");

      obj.unitPriceInDecimal = JsonUtil.getString(jsonObj, "unit_price_in_decimal");

      obj.prorationType = ProrationType.fromString(JsonUtil.getString(jsonObj, "proration_type"));

      obj.servicePeriod = JsonUtil.getInteger(jsonObj, "service_period");

      return obj;
    }

    @Override
    public String toString() {
      return "Addons{"
          + "id="
          + id
          + ", quantity="
          + quantity
          + ", unitPrice="
          + unitPrice
          + ", quantityInDecimal="
          + quantityInDecimal
          + ", unitPriceInDecimal="
          + unitPriceInDecimal
          + ", prorationType="
          + prorationType
          + ", servicePeriod="
          + servicePeriod
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      Addons that = (Addons) o;
      return java.util.Objects.equals(id, that.id)
          && java.util.Objects.equals(quantity, that.quantity)
          && java.util.Objects.equals(unitPrice, that.unitPrice)
          && java.util.Objects.equals(quantityInDecimal, that.quantityInDecimal)
          && java.util.Objects.equals(unitPriceInDecimal, that.unitPriceInDecimal)
          && java.util.Objects.equals(prorationType, that.prorationType)
          && java.util.Objects.equals(servicePeriod, that.servicePeriod);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(
          id,
          quantity,
          unitPrice,
          quantityInDecimal,
          unitPriceInDecimal,
          prorationType,
          servicePeriod);
    }
  }
}
