/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.core.models.feature;

import com.chargebee.internal.JsonUtil;
import java.sql.Timestamp;
import java.util.List;

public class Feature {

  private String id;
  private String name;
  private String description;
  private Status status;
  private Type type;
  private String unit;
  private Long resourceVersion;
  private Timestamp updatedAt;
  private Timestamp createdAt;
  private List<Levels> levels;

  public String getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public String getDescription() {
    return description;
  }

  public Status getStatus() {
    return status;
  }

  public Type getType() {
    return type;
  }

  public String getUnit() {
    return unit;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public Timestamp getUpdatedAt() {
    return updatedAt;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public List<Levels> getLevels() {
    return levels;
  }

  public enum Status {
    Active("active"),

    Archived("archived"),

    Draft("draft"),

    /** An enum member indicating that Status was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Status(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Status fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Status enumValue : Status.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public enum Type {
    Switch("switch"),

    Custom("custom"),

    Quantity("quantity"),

    Range("range"),

    /** An enum member indicating that Type was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    Type(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Type fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (Type enumValue : Type.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static Feature fromJson(String json) {
    Feature obj = new Feature();

    obj.id = JsonUtil.getString(json, "id");

    obj.name = JsonUtil.getString(json, "name");

    obj.description = JsonUtil.getString(json, "description");

    obj.status = Status.fromString(JsonUtil.getString(json, "status"));

    obj.type = Type.fromString(JsonUtil.getString(json, "type"));

    obj.unit = JsonUtil.getString(json, "unit");

    obj.resourceVersion = JsonUtil.getLong(json, "resource_version");

    obj.updatedAt = JsonUtil.getTimestamp(json, "updated_at");

    obj.createdAt = JsonUtil.getTimestamp(json, "created_at");

    obj.levels =
        JsonUtil.parseObjectArray(JsonUtil.getArray(json, "levels")).stream()
            .map(Levels::fromJson)
            .collect(java.util.stream.Collectors.toList());

    return obj;
  }

  public static class Levels {

    private String name;
    private String value;
    private Integer level;
    private Boolean isUnlimited;

    public String getName() {
      return name;
    }

    public String getValue() {
      return value;
    }

    public Integer getLevel() {
      return level;
    }

    public Boolean getIsUnlimited() {
      return isUnlimited;
    }

    public static Levels fromJson(String json) {
      Levels obj = new Levels();

      obj.name = JsonUtil.getString(json, "name");

      obj.value = JsonUtil.getString(json, "value");

      obj.level = JsonUtil.getInteger(json, "level");

      obj.isUnlimited = JsonUtil.getBoolean(json, "is_unlimited");

      return obj;
    }
  }
}
