/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.core.models.usageEvent;

import com.chargebee.v4.internal.JsonUtil;

public class UsageEvent {

  private String subscriptionId;
  private String deduplicationId;
  private Long usageTimestamp;
  private java.util.Map<String, Object> properties;

  public String getSubscriptionId() {
    return subscriptionId;
  }

  public String getDeduplicationId() {
    return deduplicationId;
  }

  public Long getUsageTimestamp() {
    return usageTimestamp;
  }

  public java.util.Map<String, Object> getProperties() {
    return properties;
  }

  public static UsageEvent fromJson(String json) {
    UsageEvent obj = new UsageEvent();

    obj.subscriptionId = JsonUtil.getString(json, "subscription_id");

    obj.deduplicationId = JsonUtil.getString(json, "deduplication_id");

    obj.usageTimestamp = JsonUtil.getLong(json, "usage_timestamp");

    String __propertiesJson = JsonUtil.getObject(json, "properties");
    obj.properties =
        __propertiesJson != null
            ? JsonUtil.parseJsonObjectToMap(__propertiesJson)
            : new java.util.HashMap<>();

    return obj;
  }
}
