/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.impactedItem;

import com.chargebee.v4.internal.JsonUtil;
import java.sql.Timestamp;
import java.util.List;

public class ImpactedItem {

  private Integer count;
  private List<Object> items;
  private Download download;

  public Integer getCount() {
    return count;
  }

  public List<Object> getItems() {
    return items;
  }

  public Download getDownload() {
    return download;
  }

  public static ImpactedItem fromJson(String json) {
    ImpactedItem obj = new ImpactedItem();

    obj.count = JsonUtil.getInteger(json, "count");

    String __itemsJson = JsonUtil.getArray(json, "items");
    obj.items =
        __itemsJson != null
            ? JsonUtil.parseObjectArray(__itemsJson).stream()
                .map(JsonUtil::parseJsonObjectToMap)
                .collect(java.util.stream.Collectors.toList())
            : null;

    String __downloadJson = JsonUtil.getObject(json, "download");
    if (__downloadJson != null) {
      obj.download = Download.fromJson(__downloadJson);
    }

    return obj;
  }

  @Override
  public String toString() {
    return "ImpactedItem{" + "count=" + count + ", items=" + items + ", download=" + download + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    ImpactedItem that = (ImpactedItem) o;
    return java.util.Objects.equals(count, that.count)
        && java.util.Objects.equals(items, that.items)
        && java.util.Objects.equals(download, that.download);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(count, items, download);
  }

  public static class Download {

    private String downloadUrl;
    private Timestamp validTill;
    private String mimeType;

    public String getDownloadUrl() {
      return downloadUrl;
    }

    public Timestamp getValidTill() {
      return validTill;
    }

    public String getMimeType() {
      return mimeType;
    }

    public static Download fromJson(String json) {
      Download obj = new Download();

      obj.downloadUrl = JsonUtil.getString(json, "download_url");

      obj.validTill = JsonUtil.getTimestamp(json, "valid_till");

      obj.mimeType = JsonUtil.getString(json, "mime_type");

      return obj;
    }

    @Override
    public String toString() {
      return "Download{"
          + "downloadUrl="
          + downloadUrl
          + ", validTill="
          + validTill
          + ", mimeType="
          + mimeType
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;
      Download that = (Download) o;
      return java.util.Objects.equals(downloadUrl, that.downloadUrl)
          && java.util.Objects.equals(validTill, that.validTill)
          && java.util.Objects.equals(mimeType, that.mimeType);
    }

    @Override
    public int hashCode() {
      return java.util.Objects.hash(downloadUrl, validTill, mimeType);
    }
  }
}
