/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.core.models.couponSet.params;

import com.chargebee.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class CouponSetDeleteParams {

  private final Map<String, Object> formData;

  private CouponSetDeleteParams(CouponSetDeleteBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for CouponSetDeleteParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static CouponSetDeleteBuilder builder() {
    return new CouponSetDeleteBuilder();
  }

  public static final class CouponSetDeleteBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private CouponSetDeleteBuilder() {}

    public CouponSetDeleteParams build() {
      return new CouponSetDeleteParams(this);
    }
  }
}
