/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.core.models.customer.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class CustomerMergeParams {

  private final Map<String, Object> formData;

  private CustomerMergeParams(CustomerMergeBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for CustomerMergeParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static CustomerMergeBuilder builder() {
    return new CustomerMergeBuilder();
  }

  public static final class CustomerMergeBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private CustomerMergeBuilder() {}

    public CustomerMergeBuilder fromCustomerId(String value) {

      formData.put("from_customer_id", value);

      return this;
    }

    public CustomerMergeBuilder toCustomerId(String value) {

      formData.put("to_customer_id", value);

      return this;
    }

    public CustomerMergeParams build() {
      return new CustomerMergeParams(this);
    }
  }
}
