/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.ledgerAccountBalance;

import com.chargebee.v4.internal.JsonUtil;
import com.google.gson.JsonObject;
import java.sql.Timestamp;

public class LedgerAccountBalance {

  private String subscriptionId;
  private String unitId;
  private UnitType unitType;
  private Timestamp createdAt;
  private Timestamp modifiedAt;
  private Long resourceVersion;
  private ProvisionedBalance provisionedBalance;
  private OverdraftBalance overdraftBalance;

  public String getSubscriptionId() {
    return subscriptionId;
  }

  public String getUnitId() {
    return unitId;
  }

  public UnitType getUnitType() {
    return unitType;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public Timestamp getModifiedAt() {
    return modifiedAt;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public ProvisionedBalance getProvisionedBalance() {
    return provisionedBalance;
  }

  public OverdraftBalance getOverdraftBalance() {
    return overdraftBalance;
  }

  public enum UnitType {
    CREDIT_UNIT("credit_unit"),

    /** An enum member indicating that UnitType was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    UnitType(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static UnitType fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (UnitType enumValue : UnitType.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static LedgerAccountBalance fromJson(String json) {
    return fromJson(JsonUtil.parse(json));
  }

  public static LedgerAccountBalance fromJson(java.util.Map<String, Object> map) {
    return fromJson(JsonUtil.toJson(map));
  }

  public static LedgerAccountBalance fromJson(JsonObject jsonObj) {
    LedgerAccountBalance obj = new LedgerAccountBalance();

    obj.subscriptionId = JsonUtil.getString(jsonObj, "subscription_id");

    obj.unitId = JsonUtil.getString(jsonObj, "unit_id");

    obj.unitType = UnitType.fromString(JsonUtil.getString(jsonObj, "unit_type"));

    obj.createdAt = JsonUtil.getTimestamp(jsonObj, "created_at");

    obj.modifiedAt = JsonUtil.getTimestamp(jsonObj, "modified_at");

    obj.resourceVersion = JsonUtil.getLong(jsonObj, "resource_version");

    JsonObject __provisionedBalanceObj = JsonUtil.getJsonObject(jsonObj, "provisioned_balance");
    if (__provisionedBalanceObj != null) {
      obj.provisionedBalance = ProvisionedBalance.fromJson(__provisionedBalanceObj);
    }

    JsonObject __overdraftBalanceObj = JsonUtil.getJsonObject(jsonObj, "overdraft_balance");
    if (__overdraftBalanceObj != null) {
      obj.overdraftBalance = OverdraftBalance.fromJson(__overdraftBalanceObj);
    }

    return obj;
  }

  @Override
  public String toString() {
    return "LedgerAccountBalance{"
        + "subscriptionId="
        + subscriptionId
        + ", unitId="
        + unitId
        + ", unitType="
        + unitType
        + ", createdAt="
        + createdAt
        + ", modifiedAt="
        + modifiedAt
        + ", resourceVersion="
        + resourceVersion
        + ", provisionedBalance="
        + provisionedBalance
        + ", overdraftBalance="
        + overdraftBalance
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    LedgerAccountBalance that = (LedgerAccountBalance) o;
    return java.util.Objects.equals(subscriptionId, that.subscriptionId)
        && java.util.Objects.equals(unitId, that.unitId)
        && java.util.Objects.equals(unitType, that.unitType)
        && java.util.Objects.equals(createdAt, that.createdAt)
        && java.util.Objects.equals(modifiedAt, that.modifiedAt)
        && java.util.Objects.equals(resourceVersion, that.resourceVersion)
        && java.util.Objects.equals(provisionedBalance, that.provisionedBalance)
        && java.util.Objects.equals(overdraftBalance, that.overdraftBalance);
  }

  @Override
  public int hashCode() {

    return java.util.Objects.hash(
        subscriptionId,
        unitId,
        unitType,
        createdAt,
        modifiedAt,
        resourceVersion,
        provisionedBalance,
        overdraftBalance);
  }

  public static class ProvisionedBalance {

    private String totalBalance;
    private String usableBalance;
    private String holdAmount;

    public String getTotalBalance() {
      return totalBalance;
    }

    public String getUsableBalance() {
      return usableBalance;
    }

    public String getHoldAmount() {
      return holdAmount;
    }

    public static ProvisionedBalance fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static ProvisionedBalance fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static ProvisionedBalance fromJson(JsonObject jsonObj) {
      ProvisionedBalance obj = new ProvisionedBalance();

      obj.totalBalance = JsonUtil.getString(jsonObj, "total_balance");

      obj.usableBalance = JsonUtil.getString(jsonObj, "usable_balance");

      obj.holdAmount = JsonUtil.getString(jsonObj, "hold_amount");

      return obj;
    }

    @Override
    public String toString() {
      return "ProvisionedBalance{"
          + "totalBalance="
          + totalBalance
          + ", usableBalance="
          + usableBalance
          + ", holdAmount="
          + holdAmount
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ProvisionedBalance that = (ProvisionedBalance) o;
      return java.util.Objects.equals(totalBalance, that.totalBalance)
          && java.util.Objects.equals(usableBalance, that.usableBalance)
          && java.util.Objects.equals(holdAmount, that.holdAmount);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(totalBalance, usableBalance, holdAmount);
    }
  }

  public static class OverdraftBalance {

    private Boolean isUnlimited;
    private String limit;
    private String totalBalance;
    private String usableBalance;
    private String usedAmount;
    private String holdAmount;

    public Boolean getIsUnlimited() {
      return isUnlimited;
    }

    public String getLimit() {
      return limit;
    }

    public String getTotalBalance() {
      return totalBalance;
    }

    public String getUsableBalance() {
      return usableBalance;
    }

    public String getUsedAmount() {
      return usedAmount;
    }

    public String getHoldAmount() {
      return holdAmount;
    }

    public static OverdraftBalance fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static OverdraftBalance fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static OverdraftBalance fromJson(JsonObject jsonObj) {
      OverdraftBalance obj = new OverdraftBalance();

      obj.isUnlimited = JsonUtil.getBoolean(jsonObj, "is_unlimited");

      obj.limit = JsonUtil.getString(jsonObj, "limit");

      obj.totalBalance = JsonUtil.getString(jsonObj, "total_balance");

      obj.usableBalance = JsonUtil.getString(jsonObj, "usable_balance");

      obj.usedAmount = JsonUtil.getString(jsonObj, "used_amount");

      obj.holdAmount = JsonUtil.getString(jsonObj, "hold_amount");

      return obj;
    }

    @Override
    public String toString() {
      return "OverdraftBalance{"
          + "isUnlimited="
          + isUnlimited
          + ", limit="
          + limit
          + ", totalBalance="
          + totalBalance
          + ", usableBalance="
          + usableBalance
          + ", usedAmount="
          + usedAmount
          + ", holdAmount="
          + holdAmount
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      OverdraftBalance that = (OverdraftBalance) o;
      return java.util.Objects.equals(isUnlimited, that.isUnlimited)
          && java.util.Objects.equals(limit, that.limit)
          && java.util.Objects.equals(totalBalance, that.totalBalance)
          && java.util.Objects.equals(usableBalance, that.usableBalance)
          && java.util.Objects.equals(usedAmount, that.usedAmount)
          && java.util.Objects.equals(holdAmount, that.holdAmount);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(
          isUnlimited, limit, totalBalance, usableBalance, usedAmount, holdAmount);
    }
  }
}
