/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.impactedItemPrice;

import com.chargebee.v4.internal.JsonUtil;
import java.sql.Timestamp;
import java.util.List;

public class ImpactedItemPrice {

  private Integer count;
  private List<Object> itemPrices;
  private Download download;

  public Integer getCount() {
    return count;
  }

  public List<Object> getItemPrices() {
    return itemPrices;
  }

  public Download getDownload() {
    return download;
  }

  public static ImpactedItemPrice fromJson(String json) {
    ImpactedItemPrice obj = new ImpactedItemPrice();

    obj.count = JsonUtil.getInteger(json, "count");

    String __itemPricesJson = JsonUtil.getArray(json, "item_prices");
    obj.itemPrices =
        __itemPricesJson != null
            ? JsonUtil.parseObjectArray(__itemPricesJson).stream()
                .map(JsonUtil::parseJsonObjectToMap)
                .collect(java.util.stream.Collectors.toList())
            : null;

    String __downloadJson = JsonUtil.getObject(json, "download");
    if (__downloadJson != null) {
      obj.download = Download.fromJson(__downloadJson);
    }

    return obj;
  }

  @Override
  public String toString() {
    return "ImpactedItemPrice{"
        + "count="
        + count
        + ", itemPrices="
        + itemPrices
        + ", download="
        + download
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    ImpactedItemPrice that = (ImpactedItemPrice) o;
    return java.util.Objects.equals(count, that.count)
        && java.util.Objects.equals(itemPrices, that.itemPrices)
        && java.util.Objects.equals(download, that.download);
  }

  @Override
  public int hashCode() {

    return java.util.Objects.hash(count, itemPrices, download);
  }

  public static class Download {

    private String downloadUrl;
    private Timestamp validTill;
    private String mimeType;

    public String getDownloadUrl() {
      return downloadUrl;
    }

    public Timestamp getValidTill() {
      return validTill;
    }

    public String getMimeType() {
      return mimeType;
    }

    public static Download fromJson(String json) {
      Download obj = new Download();

      obj.downloadUrl = JsonUtil.getString(json, "download_url");

      obj.validTill = JsonUtil.getTimestamp(json, "valid_till");

      obj.mimeType = JsonUtil.getString(json, "mime_type");

      return obj;
    }

    @Override
    public String toString() {
      return "Download{"
          + "downloadUrl="
          + downloadUrl
          + ", validTill="
          + validTill
          + ", mimeType="
          + mimeType
          + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      Download that = (Download) o;
      return java.util.Objects.equals(downloadUrl, that.downloadUrl)
          && java.util.Objects.equals(validTill, that.validTill)
          && java.util.Objects.equals(mimeType, that.mimeType);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(downloadUrl, validTill, mimeType);
    }
  }
}
