/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */
package com.chargebee.v4.core.models.paymentSource.params;

import com.chargebee.v4.internal.Recommended;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class PaymentSourceExportPaymentSourceParams {

  private final Map<String, Object> formData;

  private PaymentSourceExportPaymentSourceParams(PaymentSourceExportPaymentSourceBuilder builder) {
    this.formData = Collections.unmodifiableMap(new LinkedHashMap<>(builder.formData));
  }

  /** Get the form data for this request. */
  public Map<String, Object> toFormData() {
    return formData;
  }

  /** Create a new builder for PaymentSourceExportPaymentSourceParams. */
  @Recommended(reason = "Preferred for reusability, validation, and LLM-friendliness")
  public static PaymentSourceExportPaymentSourceBuilder builder() {
    return new PaymentSourceExportPaymentSourceBuilder();
  }

  public static final class PaymentSourceExportPaymentSourceBuilder {
    private final Map<String, Object> formData = new LinkedHashMap<>();

    private PaymentSourceExportPaymentSourceBuilder() {}

    public PaymentSourceExportPaymentSourceBuilder gatewayAccountId(String value) {
      formData.put("gateway_account_id", value);
      return this;
    }

    public PaymentSourceExportPaymentSourceParams build() {
      return new PaymentSourceExportPaymentSourceParams(this);
    }
  }
}
