/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.models.omnichannelSubscriptionItemScheduledChange;

import com.chargebee.v4.internal.JsonUtil;
import com.google.gson.JsonObject;
import java.sql.Timestamp;

public class OmnichannelSubscriptionItemScheduledChange {

  private String id;
  private String omnichannelSubscriptionItemId;
  private Timestamp scheduledAt;
  private ChangeType changeType;
  private Timestamp createdAt;
  private Timestamp modifiedAt;
  private Long resourceVersion;
  private CurrentState currentState;
  private ScheduledState scheduledState;

  public String getId() {
    return id;
  }

  public String getOmnichannelSubscriptionItemId() {
    return omnichannelSubscriptionItemId;
  }

  public Timestamp getScheduledAt() {
    return scheduledAt;
  }

  public ChangeType getChangeType() {
    return changeType;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public Timestamp getModifiedAt() {
    return modifiedAt;
  }

  public Long getResourceVersion() {
    return resourceVersion;
  }

  public CurrentState getCurrentState() {
    return currentState;
  }

  public ScheduledState getScheduledState() {
    return scheduledState;
  }

  public enum ChangeType {
    DOWNGRADE("downgrade"),

    PAUSE("pause"),

    /** An enum member indicating that ChangeType was instantiated with an unknown value. */
    _UNKNOWN(null);
    private final String value;

    ChangeType(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static ChangeType fromString(String value) {
      if (value == null) return _UNKNOWN;
      for (ChangeType enumValue : ChangeType.values()) {
        if (enumValue.value != null && enumValue.value.equals(value)) {
          return enumValue;
        }
      }
      return _UNKNOWN;
    }
  }

  public static OmnichannelSubscriptionItemScheduledChange fromJson(String json) {
    return fromJson(JsonUtil.parse(json));
  }

  public static OmnichannelSubscriptionItemScheduledChange fromJson(
      java.util.Map<String, Object> map) {
    return fromJson(JsonUtil.toJson(map));
  }

  public static OmnichannelSubscriptionItemScheduledChange fromJson(JsonObject jsonObj) {
    OmnichannelSubscriptionItemScheduledChange obj =
        new OmnichannelSubscriptionItemScheduledChange();

    obj.id = JsonUtil.getString(jsonObj, "id");

    obj.omnichannelSubscriptionItemId =
        JsonUtil.getString(jsonObj, "omnichannel_subscription_item_id");

    obj.scheduledAt = JsonUtil.getTimestamp(jsonObj, "scheduled_at");

    obj.changeType = ChangeType.fromString(JsonUtil.getString(jsonObj, "change_type"));

    obj.createdAt = JsonUtil.getTimestamp(jsonObj, "created_at");

    obj.modifiedAt = JsonUtil.getTimestamp(jsonObj, "modified_at");

    obj.resourceVersion = JsonUtil.getLong(jsonObj, "resource_version");

    JsonObject __currentStateObj = JsonUtil.getJsonObject(jsonObj, "current_state");
    if (__currentStateObj != null) {
      obj.currentState = CurrentState.fromJson(__currentStateObj);
    }

    JsonObject __scheduledStateObj = JsonUtil.getJsonObject(jsonObj, "scheduled_state");
    if (__scheduledStateObj != null) {
      obj.scheduledState = ScheduledState.fromJson(__scheduledStateObj);
    }

    return obj;
  }

  @Override
  public String toString() {
    return "OmnichannelSubscriptionItemScheduledChange{"
        + "id="
        + id
        + ", omnichannelSubscriptionItemId="
        + omnichannelSubscriptionItemId
        + ", scheduledAt="
        + scheduledAt
        + ", changeType="
        + changeType
        + ", createdAt="
        + createdAt
        + ", modifiedAt="
        + modifiedAt
        + ", resourceVersion="
        + resourceVersion
        + ", currentState="
        + currentState
        + ", scheduledState="
        + scheduledState
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    OmnichannelSubscriptionItemScheduledChange that =
        (OmnichannelSubscriptionItemScheduledChange) o;
    return java.util.Objects.equals(id, that.id)
        && java.util.Objects.equals(
            omnichannelSubscriptionItemId, that.omnichannelSubscriptionItemId)
        && java.util.Objects.equals(scheduledAt, that.scheduledAt)
        && java.util.Objects.equals(changeType, that.changeType)
        && java.util.Objects.equals(createdAt, that.createdAt)
        && java.util.Objects.equals(modifiedAt, that.modifiedAt)
        && java.util.Objects.equals(resourceVersion, that.resourceVersion)
        && java.util.Objects.equals(currentState, that.currentState)
        && java.util.Objects.equals(scheduledState, that.scheduledState);
  }

  @Override
  public int hashCode() {

    return java.util.Objects.hash(
        id,
        omnichannelSubscriptionItemId,
        scheduledAt,
        changeType,
        createdAt,
        modifiedAt,
        resourceVersion,
        currentState,
        scheduledState);
  }

  public static class CurrentState {

    private String itemIdAtSource;

    public String getItemIdAtSource() {
      return itemIdAtSource;
    }

    public static CurrentState fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static CurrentState fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static CurrentState fromJson(JsonObject jsonObj) {
      CurrentState obj = new CurrentState();

      obj.itemIdAtSource = JsonUtil.getString(jsonObj, "item_id_at_source");

      return obj;
    }

    @Override
    public String toString() {
      return "CurrentState{" + "itemIdAtSource=" + itemIdAtSource + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      CurrentState that = (CurrentState) o;
      return java.util.Objects.equals(itemIdAtSource, that.itemIdAtSource);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(itemIdAtSource);
    }
  }

  public static class ScheduledState {

    private String itemIdAtSource;

    public String getItemIdAtSource() {
      return itemIdAtSource;
    }

    public static ScheduledState fromJson(String json) {
      return fromJson(JsonUtil.parse(json));
    }

    public static ScheduledState fromJson(java.util.Map<String, Object> map) {
      return fromJson(JsonUtil.toJson(map));
    }

    public static ScheduledState fromJson(JsonObject jsonObj) {
      ScheduledState obj = new ScheduledState();

      obj.itemIdAtSource = JsonUtil.getString(jsonObj, "item_id_at_source");

      return obj;
    }

    @Override
    public String toString() {
      return "ScheduledState{" + "itemIdAtSource=" + itemIdAtSource + "}";
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ScheduledState that = (ScheduledState) o;
      return java.util.Objects.equals(itemIdAtSource, that.itemIdAtSource);
    }

    @Override
    public int hashCode() {

      return java.util.Objects.hash(itemIdAtSource);
    }
  }
}
