/*
 * This file is auto-generated by Chargebee.
 * Copyright 2025 Chargebee Inc.
 */

package com.chargebee.v4.exceptions;

import com.chargebee.v4.exceptions.codes.ApiErrorCode;
import com.chargebee.v4.transport.Request;
import com.chargebee.v4.transport.Response;

/**
 * Exception thrown for invalid request errors including validation failures.
 *
 * <p>This exception is thrown when the API returns an error with type: "invalid_request"
 *
 * <p>Example usage:
 *
 * <pre>{@code
 * try {
 *     // API call
 * } catch (InvalidRequestException e) {
 *     System.out.println("Error code: " + e.getApiErrorCodeRaw());
 *     System.out.println("Message: " + e.getMessage());
 *     System.out.println("Params: " + e.getParams());
 *     System.out.println("Request URL: " + e.getRequest().getUrl());
 * }
 * }</pre>
 */
public class InvalidRequestException extends APIException {

  public InvalidRequestException(
      int statusCode,
      String type,
      ApiErrorCode apiErrorCode,
      String message,
      String jsonResponse,
      Request request,
      Response response) {
    super(statusCode, type, apiErrorCode, message, jsonResponse, request, response);
  }

  /**
   * Get the error type value that this exception represents.
   *
   * @return the error type string "invalid_request"
   */
  public static String getExpectedErrorType() {
    return "invalid_request";
  }
}
